
@startuml
start
while (is connected?) is(yes)
  :read message;
  if (message is a response?) is (yes) then
    :notify the requesting message's\nresponse handler;
  else (no)
    :call the default message handler;
  endif
endwhile(disconnected)
stop
@enduml
