.TH "ver14.SharedClasses.UI.MyLbl" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.MyLbl
.SH SYNOPSIS
.br
.PP
.PP
Inherits JLabel\&.
.PP
Inherited by \fBver14\&.SharedClasses\&.UI\&.LinkLabel\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBStringModifier\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyLbl\fP (String text, Font font)"
.br
.ti -1c
.RI "\fBMyLbl\fP (String text)"
.br
.ti -1c
.RI "\fBMyLbl\fP (String text, Icon icon, int horizontalAlignment)"
.br
.ti -1c
.RI "void \fBsetText\fP (String text)"
.br
.ti -1c
.RI "\fBMyLbl\fP (Icon icon, Font font)"
.br
.ti -1c
.RI "void \fBunderline\fP ()"
.br
.ti -1c
.RI "void \fBsetAllSizes\fP (Dimension size)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtoggle\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
