.TH "ver14.SharedClasses.Game.Moves.CastlingRights.Side" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.Moves.CastlingRights.Side
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSide\fP (int \fBcastledKingCol\fP, int \fBrookStartingCol\fP, int \fBcastledRookCol\fP)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "\fBLocation\fP \fBkingFinalLoc\fP (\fBLocation\fP currentKingLoc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKING\fP =(Location\&.G, Location\&.H, Location\&.F)"
.br
.ti -1c
.RI "\fBQUEEN\fP =(Location\&.C, Location\&.A, Location\&.D)"
.br
.ti -1c
.RI "final int \fBrookStartingCol\fP"
.br
.ti -1c
.RI "final int \fBcastledRookCol\fP"
.br
.ti -1c
.RI "final int \fBcastledKingCol\fP"
.br
.ti -1c
.RI "final int \fBkingTravelDistance\fP"
.br
.ti -1c
.RI "final String \fBcastlingNotation\fP"
.br
.ti -1c
.RI "final int \fBasInt\fP"
.br
.ti -1c
.RI "final int \fBmult\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final \fBSide\fP[] \fBSIDES\fP = {\fBKING\fP, \fBQUEEN\fP}"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSide\fP - Castling side\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.Side (int castledKingCol, int rookStartingCol, int castledRookCol)"
Instantiates a new \fBSide\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIcastledKingCol\fP the castled king col 
.br
\fIrookStartingCol\fP the rook starting col 
.br
\fIcastledRookCol\fP the castled rook col 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBLocation\fP ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.kingFinalLoc (\fBLocation\fP currentKingLoc)"
King final loc location\&.
.PP
\fBParameters\fP
.RS 4
\fIcurrentKingLoc\fP the current king loc 
.RE
.PP
\fBReturns\fP
.RS 4
the location 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string @hidden 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.asInt"
The As int\&. 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.castledKingCol"
The Castled king col\&. 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.castledRookCol"
The Castled rook col\&. 
.SS "final String ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.castlingNotation"
The Castling notation\&. 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.KING =(Location\&.G, Location\&.H, Location\&.F)"
King side\&. 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.kingTravelDistance"
The King travel distance\&. 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.mult"
The King Movement \fBDirection\fP Mult 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.QUEEN =(Location\&.C, Location\&.A, Location\&.D)"
Queen side\&. 
.SS "final int ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.rookStartingCol"
The Rook starting col\&. 
.SS " final \fBSide\fP [] ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.Side\&.SIDES = {\fBKING\fP, \fBQUEEN\fP}\fC [static]\fP"
The constant SIDES\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
