.TH "ver14.SharedClasses.Misc.Question.QuestionType" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Misc.Question.QuestionType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDRAW_OFFER\fP"
.br
.ti -1c
.RI "\fBTHREEFOLD\fP"
.br
.ti -1c
.RI "\fBREMATCH\fP"
.br
.ti -1c
.RI "\fBNO_TYPE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQuestion\fP type\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Misc\&.Question\&.QuestionType\&.DRAW_OFFER"
Draw offer question type\&. 
.SS "ver14\&.SharedClasses\&.Misc\&.Question\&.QuestionType\&.NO_TYPE"
No type question type\&. 
.SS "ver14\&.SharedClasses\&.Misc\&.Question\&.QuestionType\&.REMATCH"
Rematch question type\&. 
.SS "ver14\&.SharedClasses\&.Misc\&.Question\&.QuestionType\&.THREEFOLD"
Threefold question type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
