.TH "ver14.SharedClasses.Game.GameSetup.TimeFormat" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.GameSetup.TimeFormat
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeFormat\fP (\fBTimeFormat\fP other)"
.br
.ti -1c
.RI "\fBTimeFormat\fP (long timeInMillis)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final long \fBtimeInMillis\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final \fBTimeFormat\fP \fBRAPID\fP = new \fBTimeFormat\fP(TimeUnit\&.MINUTES\&.toMillis(10))"
.br
.ti -1c
.RI "static final \fBTimeFormat\fP \fBULTRA_BULLET\fP = new \fBTimeFormat\fP(TimeUnit\&.SECONDS\&.toMillis(2))"
.br
.ti -1c
.RI "static final \fBTimeFormat\fP \fBBULLET\fP = new \fBTimeFormat\fP(TimeUnit\&.MINUTES\&.toMillis(1))"
.br
.ti -1c
.RI "static final \fBTimeFormat\fP \fBBULLET2\fP = new \fBTimeFormat\fP(TimeUnit\&.MINUTES\&.toMillis(2))"
.br
.ti -1c
.RI "static final \fBTimeFormat\fP[] \fBPRESETS\fP = {RAPID, ULTRA_BULLET, BULLET, BULLET2}"
.br
.ti -1c
.RI "static final int \fBnumOfFields\fP = 2"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
