.TH "ver14.SharedClasses.Misc.IDsGenerator" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Misc.IDsGenerator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "synchronized String \fBgenerate\fP ()"
.br
.ti -1c
.RI "boolean \fBcanUseId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
IDs generator\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean ver14\&.SharedClasses\&.Misc\&.IDsGenerator\&.canUseId (String id)"
Can use id boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIid\fP the id 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "synchronized String ver14\&.SharedClasses\&.Misc\&.IDsGenerator\&.generate ()"
Generate id\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
