.TH "ver14.SharedClasses.Callbacks.Callback< T >" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Callbacks.Callback< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcallback\fP (T obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCallback\fP - an object callback\&.
.PP
\fBParameters\fP
.RS 4
\fI<T>\fP the object's type 
.RE
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void \fBver14\&.SharedClasses\&.Callbacks\&.Callback\fP< T >\&.callback (T obj)"
\fBCallback\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIobj\fP the obj 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
