.TH "ver14.SharedClasses.Threads.ErrorHandling.MyError" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Threads.ErrorHandling.MyError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Error\&.
.PP
Inherited by ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.DBErr, and ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.DisconnectedError\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDBErr\fP"
.br
.ti -1c
.RI "class \fBDisconnectedError\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyError\fP ()"
.br
.ti -1c
.RI "\fBMyError\fP (Throwable throwable)"
.br
.ti -1c
.RI "\fBMyError\fP (String message)"
.br
.ti -1c
.RI "\fBMyError\fP (String message, Throwable cause)"
.br
.ti -1c
.RI "String \fBgetHandledStr\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBerrToString\fP (Throwable error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
My error - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.MyError ()"
Instantiates a new My error\&. 
.SS "ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.MyError (Throwable throwable)"
Instantiates a new My error\&.
.PP
\fBParameters\fP
.RS 4
\fIthrowable\fP the throwable 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.MyError (String message)"
Instantiates a new My error\&.
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the message 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.MyError (String message, Throwable cause)"
Instantiates a new My error\&.
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the message 
.br
\fIcause\fP the cause 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.errToString (Throwable error)\fC [static]\fP"
Err to string string\&.
.PP
\fBParameters\fP
.RS 4
\fIerror\fP the error 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.getHandledStr ()"
Gets handled str\&.
.PP
\fBReturns\fP
.RS 4
the handled str 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.MyError\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
