.TH "ver14.SharedClasses.Game.Moves.MoveAnnotation" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.Moves.MoveAnnotation
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBannotate\fP (\fBMove\fP move, \fBPiece\fP movingPiece)"
.br
.ti -1c
.RI "static String \fBannotate\fP (\fBMove\fP move, \fBPiece\fP movingPiece, String unique)"
.br
.ti -1c
.RI "static String \fBbasicAnnotate\fP (\fBBasicMove\fP move)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMove\fP annotation - utility class that annotates moves\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String ver14\&.SharedClasses\&.Game\&.Moves\&.MoveAnnotation\&.annotate (\fBMove\fP move, \fBPiece\fP movingPiece)\fC [static]\fP"
Annotate move\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.br
\fImovingPiece\fP the moving piece 
.RE
.PP
\fBReturns\fP
.RS 4
the annotation 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Game\&.Moves\&.MoveAnnotation\&.annotate (\fBMove\fP move, \fBPiece\fP movingPiece, String unique)\fC [static]\fP"
Annotate move with a unique string\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.br
\fImovingPiece\fP the moving piece 
.br
\fIunique\fP the unique string 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Game\&.Moves\&.MoveAnnotation\&.basicAnnotate (\fBBasicMove\fP move)\fC [static]\fP"
Basic annotate a move\&. just the source and destination\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
