.TH "ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSUCCESS\fP"
.br
.ti -1c
.RI "\fBERROR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBStatus\fP - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\&.Status\&.ERROR"
Error status\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\&.Status\&.SUCCESS"
Success status\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
