.TH "ver14.SharedClasses.DBActions.DBResponse.Graphable.GraphableDBResponse" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.DBResponse.Graphable.GraphableDBResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP, and \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.Graphable\&.Graphable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphableDBResponse\fP (\fBStatus\fP \fBstatus\fP, \fBDBRequest\fP \fBrequest\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.Graphable\&.GraphableDBResponse\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
