.TH "ver14.SharedClasses.UI.LinkLabel" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.LinkLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.UI\&.MyLbl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkLabel\fP (String text, \fBVoidCallback\fP onClick)"
.br
.ti -1c
.RI "void \fBsetText\fP (String text)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ver14\&.SharedClasses\&.UI\&.LinkLabel\&.setText (String text)"

.PP
Reimplemented from \fBver14\&.SharedClasses\&.UI\&.MyLbl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
