.TH "ver14.SharedClasses.UI.Buttons.ValueBtn< T >" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.Buttons.ValueBtn< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueBtn\fP (String text, Font font, T value, \fBCallback\fP< T > onClick)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Value btn - a value holding button\&.
.PP
\fBParameters\fP
.RS 4
\fI<T>\fP the value's type 
.RE
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBver14\&.SharedClasses\&.UI\&.Buttons\&.ValueBtn\fP< T >\&.\fBValueBtn\fP (String text, Font font, T value, \fBCallback\fP< T > onClick)"
Instantiates a new Value btn\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.br
\fIfont\fP the font 
.br
\fIvalue\fP the value 
.br
\fIonClick\fP the on click 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
