.TH "ver14.SharedClasses.Callbacks.AnswerCallback" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Callbacks.AnswerCallback
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.Callbacks\&.Callback< Question\&.Answer >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Answer callback - an answer callback\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
