.TH "ver14.SharedClasses.Game.Moves.PremovesGenerator" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.Moves.PremovesGenerator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static \fBMovesList\fP \fBgeneratePreMoves\fP (\fBBoard\fP board, \fBPlayerColor\fP clr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
