.TH "ver14.SharedClasses.Game.SavedGames.ArchivedGameInfo" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.SavedGames.ArchivedGameInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.EstablishedGameInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArchivedGameInfo\fP (String \fBgameId\fP, String \fBcreatorUsername\fP, String \fBopponentUsername\fP, \fBGameSettings\fP \fBgameSettings\fP, String winner, Stack< \fBMove\fP > moveStack)"
.br
.ti -1c
.RI "String \fBgetWinner\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Archived game info\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Game\&.SavedGames\&.ArchivedGameInfo\&.ArchivedGameInfo (String gameId, String creatorUsername, String opponentUsername, \fBGameSettings\fP gameSettings, String winner, Stack< \fBMove\fP > moveStack)"
Instantiates a new Archived game info\&.
.PP
\fBParameters\fP
.RS 4
\fIgameId\fP the game id 
.br
\fIcreatorUsername\fP the creator username 
.br
\fIopponentUsername\fP the opponent username 
.br
\fIgameSettings\fP the game settings 
.br
\fIwinner\fP the winner 
.br
\fImoveStack\fP the move stack 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.Game\&.SavedGames\&.ArchivedGameInfo\&.getWinner ()"
Gets winner\&.
.PP
\fBReturns\fP
.RS 4
the winner 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Game\&.SavedGames\&.ArchivedGameInfo\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.EstablishedGameInfo\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
