.TH "ver14.SharedClasses.UI.MyJFrame.StringClosing" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.MyJFrame.StringClosing
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.UI\&.MyJFrame\&.Closing< String >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "default String \fBshow\fP ()"
.br
.ti -1c
.RI "default boolean \fBcheckClosingVal\fP (String val)"
.br
.ti -1c
.RI "String \fBinitialValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The interface String closing\&. 
.SH "Member Function Documentation"
.PP 
.SS "default boolean ver14\&.SharedClasses\&.UI\&.MyJFrame\&.StringClosing\&.checkClosingVal (String val)"
Check closing val boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIval\fP the val 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "default String ver14\&.SharedClasses\&.UI\&.MyJFrame\&.StringClosing\&.show ()"
Show string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
