.TH "ver14.SharedClasses.Threads.HandledThread" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Threads.HandledThread
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.Threads\&.MyThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHandledThread\fP ()"
.br
.ti -1c
.RI "\fBHandledThread\fP (\fBThrowingRunnable\fP runnable)"
.br
.ti -1c
.RI "void \fBsetRunnable\fP (\fBThrowingRunnable\fP runnable)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBHandledThread\fP \fBrunInHandledThread\fP (\fBThrowingRunnable\fP runnable)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandledRun\fP ()  throws Throwable "
.br
.in -1c
.SH "Detailed Description"
.PP 
The type Handled thread\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Threads\&.HandledThread\&.HandledThread ()"
Instantiates a new Handled thread\&. 
.SS "ver14\&.SharedClasses\&.Threads\&.HandledThread\&.HandledThread (\fBThrowingRunnable\fP runnable)"
Instantiates a new Handled thread\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ver14\&.SharedClasses\&.Threads\&.HandledThread\&.handledRun () throws Throwable\fC [protected]\fP"
Handled run\&.
.PP
\fBExceptions\fP
.RS 4
\fIThrowable\fP the throwable 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.Threads\&.MyThread\fP\&.
.SS "static \fBHandledThread\fP ver14\&.SharedClasses\&.Threads\&.HandledThread\&.runInHandledThread (\fBThrowingRunnable\fP runnable)\fC [static]\fP"
Run in handled thread handled thread\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.RE
.PP
\fBReturns\fP
.RS 4
the handled thread 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Threads\&.HandledThread\&.setRunnable (\fBThrowingRunnable\fP runnable)"
Sets runnable\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
