.TH "ver14.SharedClasses.UI.Buttons.MyJButton" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.Buttons.MyJButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits JButton\&.
.PP
Inherited by \fBver14\&.SharedClasses\&.UI\&.Buttons\&.ValueBtn< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyJButton\fP (String text, \fBVoidCallback\fP callback)"
.br
.ti -1c
.RI "\fBMyJButton\fP (String text)"
.br
.ti -1c
.RI "void \fBsetOnClick\fP (\fBVoidCallback\fP onClick)"
.br
.ti -1c
.RI "void \fBsetText\fP (String text)"
.br
.ti -1c
.RI "\fBMyJButton\fP ()"
.br
.ti -1c
.RI "\fBMyJButton\fP (String text, Font font, \fBVoidCallback\fP onClick, JPanel addTo)"
.br
.ti -1c
.RI "\fBMyJButton\fP (String text, Font font, \fBVoidCallback\fP onClick)"
.br
.ti -1c
.RI "\fBMyJButton\fP (String text, Font font)"
.br
.ti -1c
.RI "void \fBsetFont\fP (Font font)"
.br
.ti -1c
.RI "int \fBgetMinSize\fP ()"
.br
.ti -1c
.RI "void \fBreplaceWithCancel\fP (\fBVoidCallback\fP onCancelled)"
.br
.ti -1c
.RI "void \fBresetState\fP (boolean e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
MyJButton- represents a button\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton (String text, \fBVoidCallback\fP callback)"
Instantiates a new My j button\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.br
\fIcallback\fP the callback 
.RE
.PP

.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton (String text)"
Instantiates a new My j button\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.RE
.PP

.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton ()"
Instantiates a new My j button\&. 
.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton (String text, Font font, \fBVoidCallback\fP onClick, JPanel addTo)"
Instantiates a new My j button\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.br
\fIfont\fP the font 
.br
\fIonClick\fP the on click 
.br
\fIaddTo\fP the add to 
.RE
.PP

.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton (String text, Font font, \fBVoidCallback\fP onClick)"
Instantiates a new My j button\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.br
\fIfont\fP the font 
.br
\fIonClick\fP the on click 
.RE
.PP

.SS "ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.MyJButton (String text, Font font)"
Instantiates a new My j button\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.br
\fIfont\fP the font 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.getMinSize ()"
Gets min size\&.
.PP
\fBReturns\fP
.RS 4
the min size 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.replaceWithCancel (\fBVoidCallback\fP onCancelled)"
Replace with cancel\&.
.PP
\fBParameters\fP
.RS 4
\fIonCancelled\fP the on cancelled 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.resetState (boolean e)"
Reset state\&.
.PP
\fBParameters\fP
.RS 4
\fIe\fP the e 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.setFont (Font font)"
Sets font\&.
.PP
\fBParameters\fP
.RS 4
\fIfont\fP the font 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.setOnClick (\fBVoidCallback\fP onClick)"
Sets on click\&.
.PP
\fBParameters\fP
.RS 4
\fIonClick\fP the on click 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.Buttons\&.MyJButton\&.setText (String text)"
Sets text\&.
.PP
\fBParameters\fP
.RS 4
\fItext\fP the text 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
