.TH "ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNONE\fP"
.br
.ti -1c
.RI "\fBCAN_CLAIM\fP"
.br
.ti -1c
.RI "\fBCLAIMED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Threefold status - represents a threefold draw status\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.Move\&.ThreefoldStatus\&.CAN_CLAIM"
Can claim threefold status\&. 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.Move\&.ThreefoldStatus\&.CLAIMED"
Claimed threefold status\&. 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.Move\&.ThreefoldStatus\&.NONE"
None threefold status\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
