.TH "ver14.SharedClasses.DBActions.Table.SwitchCase" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.Table.SwitchCase
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchCase\fP (\fBCondition\fP condition, \fBCol\fP ifTrue)"
.br
.ti -1c
.RI "\fBCondition\fP \fBcondition\fP ()"
.br
.ti -1c
.RI "\fBCol\fP \fBifTrue\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSwitchCase\fP \fBequals\fP (\fBCol\fP col, String value, \fBCol\fP ifTrue)"
.br
.ti -1c
.RI "static \fBSwitchCase\fP \fBdefaultCase\fP (\fBCol\fP ifTrue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Switch case - represents a case that is meant to be used inside a switch case col\&. if the \fC\fBcondition\fP\fP is true, the \fC\fBifTrue\fP\fP col will display in the switch case col
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.SwitchCase (\fBCondition\fP condition, \fBCol\fP ifTrue)"
Instantiates a new Switch case\&.
.PP
\fBParameters\fP
.RS 4
\fIcondition\fP the condition 
.br
\fIifTrue\fP the if true 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBCondition\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.condition ()"
\fBCondition\fP condition\&.
.PP
\fBReturns\fP
.RS 4
the condition 
.RE
.PP

.SS "static \fBSwitchCase\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.defaultCase (\fBCol\fP ifTrue)\fC [static]\fP"
Default case switch case\&.
.PP
\fBParameters\fP
.RS 4
\fIifTrue\fP the if true 
.RE
.PP
\fBReturns\fP
.RS 4
the switch case 
.RE
.PP

.SS "static \fBSwitchCase\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.equals (\fBCol\fP col, String value, \fBCol\fP ifTrue)\fC [static]\fP"
Equals switch case\&.
.PP
\fBParameters\fP
.RS 4
\fIcol\fP the col 
.br
\fIvalue\fP the value 
.br
\fIifTrue\fP the if true 
.RE
.PP
\fBReturns\fP
.RS 4
the switch case 
.RE
.PP

.SS "\fBCol\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.ifTrue ()"
If true col\&.
.PP
\fBReturns\fP
.RS 4
the col 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.DBActions\&.Table\&.SwitchCase\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
