.TH "ver14.SharedClasses.DBActions.Statements.CustomStatement" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.Statements.CustomStatement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.DBActions\&.Statements\&.SQLStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomStatement\fP (DBRequest\&.Type \fBtype\fP, @Language('SQL') String statement)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "String \fBcreateStatement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Custom statement - a custom sql statement\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.Statements\&.CustomStatement\&.CustomStatement (DBRequest\&.Type type, @Language('SQL') String statement)"
Instantiates a new Custom statement\&.
.PP
\fBParameters\fP
.RS 4
\fItype\fP the type 
.br
\fIstatement\fP the statement 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.DBActions\&.Statements\&.CustomStatement\&.createStatement ()\fC [protected]\fP"
Create statement string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.Statements\&.SQLStatement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
