.TH "ver14.SharedClasses.Game.GameSetup.GameTime" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.GameSetup.GameTime
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRunningTime\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameTime\fP (\fBGameTime\fP other)"
.br
.ti -1c
.RI "\fBGameTime\fP (TimeFormat\&.\&.\&. timeFormats)"
.br
.ti -1c
.RI "\fBTimeFormat\fP \fBgetTimeFormat\fP (\fBPlayerColor\fP clr)"
.br
.ti -1c
.RI "void \fBstartRunning\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "RunningTime \fBgetRunningTime\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "void \fBstopRunning\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "\fBGameTime\fP \fBclean\fP ()"
.br
.ti -1c
.RI "void \fBsyncMe\fP (\fBGameTime\fP other)"
.br
.ti -1c
.RI "long \fBgetTimeLeft\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "\fBPlayerColor\fP \fBgetCurrentlyRunning\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
