.TH "ver14.SharedClasses.DBActions.Arg.ArgType" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.Arg.ArgType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgType\fP ()"
.br
.ti -1c
.RI "\fBArgType\fP (boolean \fBisUserInput\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDate\fP"
.br
.ti -1c
.RI "\fBDateRange\fP"
.br
.ti -1c
.RI "\fBText\fP"
.br
.ti -1c
.RI "\fBServerAddress\fP"
.br
.ti -1c
.RI "\fBNumber\fP"
.br
.ti -1c
.RI "\fBUsername\fP =(false)"
.br
.ti -1c
.RI "\fBPassword\fP"
.br
.ti -1c
.RI "\fBUrl\fP"
.br
.ti -1c
.RI "\fBPictureUrl\fP"
.br
.ti -1c
.RI "final boolean \fBisUserInput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBArg\fP type - argument type\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.ArgType ()"
Instantiates a new \fBArg\fP type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.ArgType (boolean isUserInput)"
Instantiates a new \fBArg\fP type\&.
.PP
\fBParameters\fP
.RS 4
\fIisUserInput\fP the is user input 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Date"
Date arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.DateRange"
Date range arg type\&. 
.SS "final boolean ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.isUserInput"
The Is user input\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Number"
Number arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Password"
Password arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.PictureUrl"
Picture url arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.ServerAddress"
Server address arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Text"
Text arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Url"
Url arg type\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Arg\&.ArgType\&.Username =(false)"
Username arg type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
