.TH "ver14.SharedClasses.Login.LoginInfo" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Login.LoginInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginInfo\fP ()"
.br
.ti -1c
.RI "\fBLoginInfo\fP (String username, String password, \fBLoginType\fP loginType)"
.br
.ti -1c
.RI "\fBLoginInfo\fP (\fBLoginType\fP loginType)"
.br
.ti -1c
.RI "String \fBgetProfilePic\fP ()"
.br
.ti -1c
.RI "void \fBsetProfilePic\fP (String profilePic)"
.br
.ti -1c
.RI "boolean \fBisGuest\fP ()"
.br
.ti -1c
.RI "\fBLoginType\fP \fBgetLoginType\fP ()"
.br
.ti -1c
.RI "void \fBsetLoginType\fP (\fBLoginType\fP loginType)"
.br
.ti -1c
.RI "String \fBgetUsername\fP ()"
.br
.ti -1c
.RI "void \fBsetUsername\fP (String username)"
.br
.ti -1c
.RI "String \fBgetPassword\fP ()"
.br
.ti -1c
.RI "void \fBsetPassword\fP (String password)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "boolean \fBasUser\fP ()"
.br
.ti -1c
.RI "void \fBinitDebugLoginValues\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Login info\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Login\&.LoginInfo\&.LoginInfo ()"
Instantiates a new Login info\&. 
.SS "ver14\&.SharedClasses\&.Login\&.LoginInfo\&.LoginInfo (String username, String password, \fBLoginType\fP loginType)"
Instantiates a new Login info\&.
.PP
\fBParameters\fP
.RS 4
\fIusername\fP the username 
.br
\fIpassword\fP the password 
.br
\fIloginType\fP the login type 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Login\&.LoginInfo\&.LoginInfo (\fBLoginType\fP loginType)"
Instantiates a new Login info\&.
.PP
\fBParameters\fP
.RS 4
\fIloginType\fP the login type 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean ver14\&.SharedClasses\&.Login\&.LoginInfo\&.asUser ()"
As user boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "\fBLoginType\fP ver14\&.SharedClasses\&.Login\&.LoginInfo\&.getLoginType ()"
Gets login type\&.
.PP
\fBReturns\fP
.RS 4
the login type 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Login\&.LoginInfo\&.getPassword ()"
Gets password\&.
.PP
\fBReturns\fP
.RS 4
the password 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Login\&.LoginInfo\&.getProfilePic ()"
Gets profile pic\&.
.PP
\fBReturns\fP
.RS 4
the profile pic 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Login\&.LoginInfo\&.getUsername ()"
Gets username\&.
.PP
\fBReturns\fP
.RS 4
the username 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Login\&.LoginInfo\&.initDebugLoginValues ()"
Init debug login values\&. 
.SS "boolean ver14\&.SharedClasses\&.Login\&.LoginInfo\&.isGuest ()"
Is guest boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Login\&.LoginInfo\&.setLoginType (\fBLoginType\fP loginType)"
Sets login type\&.
.PP
\fBParameters\fP
.RS 4
\fIloginType\fP the login type 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Login\&.LoginInfo\&.setPassword (String password)"
Sets password\&.
.PP
\fBParameters\fP
.RS 4
\fIpassword\fP the password 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Login\&.LoginInfo\&.setProfilePic (String profilePic)"
Sets profile pic\&.
.PP
\fBParameters\fP
.RS 4
\fIprofilePic\fP the profile pic 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Login\&.LoginInfo\&.setUsername (String username)"
Sets username\&.
.PP
\fBParameters\fP
.RS 4
\fIusername\fP the username 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Login\&.LoginInfo\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
