.TH "ver14.SharedClasses.Threads.MyThread" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Threads.MyThread
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.PP
Inherited by \fBver14\&.SharedClasses\&.Networking\&.AppSocket\fP, and \fBver14\&.SharedClasses\&.Threads\&.HandledThread\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBThreadStatus\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyThread\fP ()"
.br
.ti -1c
.RI "boolean \fBisIgnoreErrs\fP ()"
.br
.ti -1c
.RI "void \fBstopRun\fP ()"
.br
.ti -1c
.RI "final void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBignoreErrs\fP ()"
.br
.ti -1c
.RI "void \fBreactivateErrs\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcurrentThread\fP (\fBCallback\fP< \fBMyThread\fP > run)"
.br
.ti -1c
.RI "static void \fBsetEnvManager\fP (\fBEnvManager\fP manager)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBhandledRun\fP ()  throws Throwable"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type My thread\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Threads\&.MyThread\&.MyThread ()"
Instantiates a new My thread\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void ver14\&.SharedClasses\&.Threads\&.MyThread\&.currentThread (\fBCallback\fP< \fBMyThread\fP > run)\fC [static]\fP"
Current thread\&. will only execute code if inside a \fBMyThread\fP
.PP
\fBParameters\fP
.RS 4
\fIrun\fP the run 
.RE
.PP

.SS "abstract void ver14\&.SharedClasses\&.Threads\&.MyThread\&.handledRun () throws Throwable\fC [abstract]\fP, \fC [protected]\fP"
Handled run\&.
.PP
\fBExceptions\fP
.RS 4
\fIThrowable\fP the throwable 
.RE
.PP

.PP
Reimplemented in \fBver14\&.SharedClasses\&.Networking\&.AppSocket\fP, and \fBver14\&.SharedClasses\&.Threads\&.HandledThread\fP\&.
.SS "void ver14\&.SharedClasses\&.Threads\&.MyThread\&.ignoreErrs ()"
Ignore errs\&. 
.SS "void ver14\&.SharedClasses\&.Threads\&.MyThread\&.reactivateErrs ()"
Reactivate errs\&. 
.SS "void ver14\&.SharedClasses\&.Threads\&.MyThread\&.stopRun ()"
Stop run\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
