.TH "ver14.SharedClasses.Game.SavedGames.CreatedGame" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.SavedGames.CreatedGame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.GameInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreatedGame\fP (String \fBgameId\fP, String \fBcreatorUsername\fP, \fBGameSettings\fP \fBgameSettings\fP)"
.br
.ti -1c
.RI "String \fBgetGameDesc\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Created game\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Game\&.SavedGames\&.CreatedGame\&.CreatedGame (String gameId, String creatorUsername, \fBGameSettings\fP gameSettings)"
Instantiates a new Created game\&.
.PP
\fBParameters\fP
.RS 4
\fIgameId\fP the game id 
.br
\fIcreatorUsername\fP the creator username 
.br
\fIgameSettings\fP the game settings 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.Game\&.SavedGames\&.CreatedGame\&.getGameDesc ()"
Gets game desc\&.
.PP
\fBReturns\fP
.RS 4
the game desc 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.GameInfo\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
