.TH "ver14.SharedClasses.Networking.Messages.MessageType" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Networking.Messages.MessageType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageType\fP (boolean chronologicalImportance)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLOGIN\fP"
.br
.ti -1c
.RI "\fBRESIGN\fP"
.br
.ti -1c
.RI "\fBADD_TIME\fP"
.br
.ti -1c
.RI "\fBWELCOME_MESSAGE\fP"
.br
.ti -1c
.RI "\fBGET_GAME_SETTINGS\fP"
.br
.ti -1c
.RI "\fBWAIT_FOR_MATCH\fP"
.br
.ti -1c
.RI "\fBINIT_GAME\fP =(true)"
.br
.ti -1c
.RI "\fBWAIT_TURN\fP =(true)"
.br
.ti -1c
.RI "\fBGET_MOVE\fP =(true)"
.br
.ti -1c
.RI "\fBTHROW_ERROR\fP"
.br
.ti -1c
.RI "\fBUPDATE_BY_MOVE\fP =(true)"
.br
.ti -1c
.RI "\fBGAME_OVER\fP"
.br
.ti -1c
.RI "\fBERROR\fP"
.br
.ti -1c
.RI "\fBQUESTION\fP"
.br
.ti -1c
.RI "\fBBYE\fP =(true)"
.br
.ti -1c
.RI "\fBUSERNAME_AVAILABILITY\fP"
.br
.ti -1c
.RI "\fBDB_REQUEST\fP"
.br
.ti -1c
.RI "\fBDB_RESPONSE\fP"
.br
.ti -1c
.RI "\fBUPDATE_SYNCED_LIST\fP"
.br
.ti -1c
.RI "\fBCANCEL_QUESTION\fP"
.br
.ti -1c
.RI "\fBINTERRUPT\fP"
.br
.ti -1c
.RI "final boolean \fBchronologicalImportance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
