.TH "ver14.SharedClasses.UI.FontManager" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.FontManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.ti -1c
.RI "class \fBDialogs\fP"
.br
.ti -1c
.RI "class \fBJMenus\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final Font \fBstatusLbl\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBdbResponseTable\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBdbResponseTableHeader\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBsidePanel\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBcoordinates\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBboardButtons\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBstatistics\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBbackOk\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBxLarge\fP = Base\&.xLarge"
.br
.ti -1c
.RI "static final Font \fBnormal\fP = Base\&.normal"
.br
.ti -1c
.RI "static final Font \fBlarge\fP = Base\&.large"
.br
.ti -1c
.RI "static final Font \fBsmall\fP = Base\&.small"
.br
.ti -1c
.RI "static final Font \fBerror\fP = Base\&.error"
.br
.ti -1c
.RI "static final Font \fBdefaultLinkLbl\fP = Base\&.normal"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
