.TH "ver14.SharedClasses.Threads.ErrorHandling.ErrorHandler< E extends MyError >" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Threads.ErrorHandling.ErrorHandler< E extends MyError >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBMyError\fP err)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBignore\fP (\fBThrowingRunnable\fP runnable)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The interface Error handler\&.
.PP
\fBParameters\fP
.RS 4
\fI<E>\fP the type parameter 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void \fBver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.ErrorHandler\fP< E extends \fBMyError\fP >\&.handle (\fBMyError\fP err)"
Handle\&.
.PP
\fBParameters\fP
.RS 4
\fIerr\fP the err 
.RE
.PP

.SS "static boolean \fBver14\&.SharedClasses\&.Threads\&.ErrorHandling\&.ErrorHandler\fP< E extends \fBMyError\fP >\&.ignore (\fBThrowingRunnable\fP runnable)\fC [static]\fP"
Ignore boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.RE
.PP
\fBReturns\fP
.RS 4
true if the runnable threw, false otherwise 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
