.TH "ver14.SharedClasses.UI.dialogs.ConfirmDialogs" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.dialogs.ConfirmDialogs
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBconfirm\fP (Component parent, String title, String message, ImageIcon icon)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static String \fBconfirm\fP (Component parent, String title, String header, String message, ImageIcon icon, String initialValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The utility class Confirm dialogs\&. 
.SH "Member Function Documentation"
.PP 
.SS "static String ver14\&.SharedClasses\&.UI\&.dialogs\&.ConfirmDialogs\&.confirm (Component parent, String title, String header, String message, ImageIcon icon, String initialValue)\fC [static]\fP"
Confirm string\&.
.PP
\fBParameters\fP
.RS 4
\fIparent\fP the parent 
.br
\fIheader\fP the header 
.br
\fImessage\fP the message 
.br
\fItitle\fP the title 
.br
\fIicon\fP the icon 
.br
\fIinitialValue\fP the initial value 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static boolean ver14\&.SharedClasses\&.UI\&.dialogs\&.ConfirmDialogs\&.confirm (Component parent, String title, String message, ImageIcon icon)\fC [static]\fP"
Confirm boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIparent\fP the parent 
.br
\fItitle\fP the title 
.br
\fImessage\fP the message 
.br
\fIicon\fP the icon 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "static void ver14\&.SharedClasses\&.UI\&.dialogs\&.ConfirmDialogs\&.main (String[] args)\fC [static]\fP"
The entry point of application\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP the input arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
