.TH "ver14.SharedClasses.Game.GameSetup.AiParameters" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.GameSetup.AiParameters
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable, and \fBver14\&.SharedClasses\&.Game\&.GameSetup\&.TimeFormatSettable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBAiType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAiParameters\fP (\fBAiParameters\fP other)"
.br
.ti -1c
.RI "\fBAiParameters\fP (\fBAiType\fP aiType, \fBTimeFormat\fP moveSearchTimeout)"
.br
.ti -1c
.RI "\fBAiType\fP \fBgetAiType\fP ()"
.br
.ti -1c
.RI "void \fBsetAiType\fP (\fBAiType\fP aiType)"
.br
.ti -1c
.RI "\fBTimeFormat\fP \fBgetMoveSearchTimeout\fP ()"
.br
.ti -1c
.RI "void \fBsetMoveSearchTimeout\fP (\fBTimeFormat\fP moveSearchTimeout)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "void \fBsetTimeFormat\fP (\fBTimeFormat\fP timeFormat)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final \fBAiParameters\fP \fBEZ_MY_AI\fP = new \fBAiParameters\fP(AiType\&.MyAi, TimeFormat\&.ULTRA_BULLET)"
.br
.ti -1c
.RI "static final \fBAiParameters\fP \fBEZ_STOCKFISH\fP = new \fBAiParameters\fP(AiType\&.Stockfish, TimeFormat\&.ULTRA_BULLET)"
.br
.ti -1c
.RI "static final int \fBnumOfFields\fP = 1 + TimeFormat\&.numOfFields"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ver14\&.SharedClasses\&.Game\&.GameSetup\&.AiParameters\&.setTimeFormat (\fBTimeFormat\fP timeFormat)"

.PP
Implements \fBver14\&.SharedClasses\&.Game\&.GameSetup\&.TimeFormatSettable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
