.TH "ver14.SharedClasses.Utils.ArgsUtil" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Utils.ArgsUtil
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionalArg\fP \fBequalsSign\fP (String preEqualStr)"
.br
.ti -1c
.RI "\fBOptionalArg\fP \fBplainTextIgnoreCase\fP (String str)"
.br
.ti -1c
.RI "record \fBOptionalArg\fP (String str)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBArgsUtil\fP \fBcreate\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type Args utils\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBArgsUtil\fP ver14\&.SharedClasses\&.Utils\&.ArgsUtil\&.create (String[] args)\fC [static]\fP"
Create args util\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP the args 
.RE
.PP
\fBReturns\fP
.RS 4
the args util 
.RE
.PP

.SS "\fBOptionalArg\fP ver14\&.SharedClasses\&.Utils\&.ArgsUtil\&.equalsSign (String preEqualStr)"
Equals sign optional arg\&. for any arg of this format: preEqualStr=argval%
.PP
\fBParameters\fP
.RS 4
\fIpreEqualStr\fP the pre equal str 
.RE
.PP
\fBReturns\fP
.RS 4
the optional arg value(assuming there is one) argval% in the example above 
.RE
.PP

.SS "record ver14\&.SharedClasses\&.Utils\&.ArgsUtil\&.OptionalArg (String str)"
Optional arg\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP
Gets string\&.
.PP
\fBReturns\fP
.RS 4
the string
.RE
.PP
Gets boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIifErr\fP the if err 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean
.RE
.PP
Check exists\&.
.PP
\fBExceptions\fP
.RS 4
\fIException\fP the exception
.RE
.PP
Exists boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean
.RE
.PP
Gets int\&.
.PP
\fBReturns\fP
.RS 4
the int
.RE
.PP
Gets int\&.
.PP
\fBParameters\fP
.RS 4
\fIifErr\fP the if err 
.RE
.PP
\fBReturns\fP
.RS 4
the int
.RE
.PP

.SS "\fBOptionalArg\fP ver14\&.SharedClasses\&.Utils\&.ArgsUtil\&.plainTextIgnoreCase (String str)"
Plain text ignore case optional arg\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the optional arg 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
