.TH "ver14.SharedClasses.Networking.MessagesHandler" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Networking.MessagesHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessagesHandler\fP (\fBAppSocket\fP \fBsocket\fP)"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonCancelQuestion\fP ()"
.br
.ti -1c
.RI "void \fBinterruptBlocking\fP (\fBMyError\fP err)"
.br
.ti -1c
.RI "\fBMessage\fP \fBblockTilRes\fP (\fBMessage\fP request)"
.br
.ti -1c
.RI "void \fBnoBlockRequest\fP (\fBMessage\fP request, \fBMessageCallback\fP onRes)"
.br
.ti -1c
.RI "void \fBreceivedMessage\fP (\fBMessage\fP message)"
.br
.ti -1c
.RI "void \fBprepareForDisconnect\fP ()"
.br
.ti -1c
.RI "void \fBonAnyMsg\fP (\fBMessage\fP message)"
.br
.ti -1c
.RI "final void \fBonDisconnected\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonLogin\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonResign\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonAddTime\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonOfferDraw\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonWelcomeMessage\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonGetGameSettings\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonWaitForMatch\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonInitGame\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonWaitTurn\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonGetMove\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonUpdateByMove\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonGameOver\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonError\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonQuestion\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonBye\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonUsernameAvailability\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonDBRequest\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonDBResponse\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonUpdateSyncedList\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonInterrupt\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonIsAlive\fP ()"
.br
.ti -1c
.RI "\fBMessageCallback\fP \fBonAlive\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonAnyDisconnection\fP ()"
.br
.ti -1c
.RI "void \fBonPlannedDisconnect\fP ()"
.br
.ti -1c
.RI "void \fBonUnplannedDisconnect\fP ()"
.br
.ti -1c
.RI "MyError\&.DisconnectedError \fBcreateDisconnectedError\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "final \fBAppSocket\fP \fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type Messages handler\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.MessagesHandler (\fBAppSocket\fP socket)"
Instantiates a new Messages handler\&.
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP the socket 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBMessage\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.blockTilRes (\fBMessage\fP request)"
Block til res message\&.
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP the request 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "MyError\&.DisconnectedError ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.createDisconnectedError ()\fC [protected]\fP"
Create disconnected error my error \&. disconnected error\&.
.PP
\fBReturns\fP
.RS 4
the my error \&. disconnected error 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.interruptBlocking (\fBMyError\fP err)"
Interrupt blocking\&.
.PP
\fBParameters\fP
.RS 4
\fIerr\fP the err 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.noBlockRequest (\fBMessage\fP request, \fBMessageCallback\fP onRes)"
No block request\&.
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP the request 
.br
\fIonRes\fP the on res 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onAddTime ()"
On add time message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onAlive ()"
On alive message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onAnyDisconnection ()\fC [protected]\fP"
On any disconnection\&. 
.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onAnyMsg (\fBMessage\fP message)"
On any msg\&.
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the message 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onBye ()"
On bye message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onCancelQuestion ()"
On cancel question message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onDBRequest ()"
On db request message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onDBResponse ()"
On db response message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "final void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onDisconnected ()"
On disconnected\&. 
.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onError ()"
On error message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onGameOver ()"
On game over message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onGetGameSettings ()"
On get game settings message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onGetMove ()"
On get move message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onInitGame ()"
On init game message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onInterrupt ()"
On interrupt message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onIsAlive ()"
On is alive message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onLogin ()"
On login message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onOfferDraw ()"
On offer draw message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onPlannedDisconnect ()\fC [protected]\fP"
On planned disconnect\&. 
.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onQuestion ()"
On question message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onResign ()"
On resign message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onUnplannedDisconnect ()\fC [protected]\fP"
On unplanned disconnect\&. 
.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onUpdateByMove ()"
On update by move message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onUpdateSyncedList ()"
On update synced list message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onUsernameAvailability ()"
On username availability message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onWaitForMatch ()"
On wait for match message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onWaitTurn ()"
On wait turn message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "\fBMessageCallback\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.onWelcomeMessage ()"
On welcome message message callback\&.
.PP
\fBReturns\fP
.RS 4
the message callback 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.prepareForDisconnect ()"
Prepare for disconnect\&. 
.SS "void ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.receivedMessage (\fBMessage\fP message)"
Received message\&.
.PP
\fBParameters\fP
.RS 4
\fImessage\fP the message 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final \fBAppSocket\fP ver14\&.SharedClasses\&.Networking\&.MessagesHandler\&.socket\fC [protected]\fP"
The Socket\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
