.TH "ver14.SharedClasses.Sync.SyncableItem" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Sync.SyncableItem
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.GameInfo\fP, and \fBver14\&.SharedClasses\&.Sync\&.UserInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "default \fBSyncableItem\fP \fBgetSyncableItem\fP ()"
.br
.ti -1c
.RI "String \fBID\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.Sync\&.SyncableItem\&.ID ()"

.PP
Implemented in \fBver14\&.SharedClasses\&.Game\&.SavedGames\&.GameInfo\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
