.TH "ver14.SharedClasses.DBActions.DBResponse.StatusResponse" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.DBResponse.StatusResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatusResponse\fP (\fBStatus\fP \fBstatus\fP, \fBDBRequest\fP \fBrequest\fP, int updatedRows)"
.br
.ti -1c
.RI "\fBStatusResponse\fP (\fBStatus\fP \fBstatus\fP, String details, \fBDBRequest\fP \fBrequest\fP, int updatedRows)"
.br
.ti -1c
.RI "String \fBgetDetails\fP ()"
.br
.ti -1c
.RI "boolean \fBisAnyData\fP ()"
.br
.ti -1c
.RI "\fBDBResponse\fP \fBclean\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Status response - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.StatusResponse\&.StatusResponse (\fBStatus\fP status, \fBDBRequest\fP request, int updatedRows)"
Instantiates a new Status response\&.
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP the status 
.br
\fIrequest\fP the request 
.br
\fIupdatedRows\fP the updated rows 
.RE
.PP

.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.StatusResponse\&.StatusResponse (\fBStatus\fP status, String details, \fBDBRequest\fP request, int updatedRows)"
Instantiates a new Status response\&.
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP the status 
.br
\fIdetails\fP the details 
.br
\fIrequest\fP the request 
.br
\fIupdatedRows\fP the updated rows 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBDBResponse\fP ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.StatusResponse\&.clean ()"
Clean db response\&.
.PP
\fBReturns\fP
.RS 4
the db response 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.StatusResponse\&.getDetails ()"
Gets details\&.
.PP
\fBReturns\fP
.RS 4
the details 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.StatusResponse\&.isAnyData ()"
Is any data boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
