.TH "ver14.SharedClasses.Networking.Messages.Message" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Networking.Messages.Message
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (\fBMessageType\fP messageType)"
.br
.ti -1c
.RI "\fBMessage\fP (\fBMessageType\fP messageType, String subject, String respondingToMsgId)"
.br
.ti -1c
.RI "\fBMessage\fP (\fBMessageType\fP messageType, \fBMessage\fP respondingTo)"
.br
.ti -1c
.RI "\fBMessage\fP (\fBMessageType\fP messageType, String subject)"
.br
.ti -1c
.RI "void \fBsetDbRequest\fP (\fBDBRequest\fP dbRequest)"
.br
.ti -1c
.RI "String \fBgetCancelingQuestionCause\fP ()"
.br
.ti -1c
.RI "void \fBsetCancelingQuestionCause\fP (String cancelingQuestionCause)"
.br
.ti -1c
.RI "\fBQuestion\&.Answer\fP \fBgetAnswer\fP ()"
.br
.ti -1c
.RI "void \fBsetAnswer\fP (\fBQuestion\&.Answer\fP answer)"
.br
.ti -1c
.RI "\fBMyError\fP \fBgetError\fP ()"
.br
.ti -1c
.RI "void \fBsetError\fP (\fBMyError\fP error)"
.br
.ti -1c
.RI "\fBDBRequest\fP \fBgetDBRequest\fP ()"
.br
.ti -1c
.RI "ArrayList< String > \fBgetUsernameSuggestions\fP ()"
.br
.ti -1c
.RI "void \fBsetUsernameSuggestions\fP (ArrayList< String > usernameSuggestions)"
.br
.ti -1c
.RI "\fBDBResponse\fP \fBgetDBResponse\fP ()"
.br
.ti -1c
.RI "void \fBsetDBResponse\fP (\fBDBResponse\fP requestedStats)"
.br
.ti -1c
.RI "Stack< \fBMove\fP > \fBgetMoveStack\fP ()"
.br
.ti -1c
.RI "void \fBsetMoveStack\fP (Stack< \fBMove\fP > moveStack)"
.br
.ti -1c
.RI "\fBSyncedItems\fP<?>[] \fBgetSyncedLists\fP ()"
.br
.ti -1c
.RI "void \fBsetSyncedLists\fP (\fBSyncedItems\fP<?>\&.\&.\&. syncedLists)"
.br
.ti -1c
.RI "String \fBgetRespondingToMsgId\fP ()"
.br
.ti -1c
.RI "void \fBsetRespondingToMsgId\fP (String respondingToMsgId)"
.br
.ti -1c
.RI "void \fBsetRespondingTo\fP (\fBMessage\fP msg)"
.br
.ti -1c
.RI "boolean \fBisResponse\fP ()"
.br
.ti -1c
.RI "String \fBgetOtherPlayer\fP ()"
.br
.ti -1c
.RI "void \fBsetOtherPlayer\fP (String otherPlayer)"
.br
.ti -1c
.RI "\fBQuestion\fP \fBgetQuestion\fP ()"
.br
.ti -1c
.RI "void \fBsetQuestion\fP (\fBQuestion\fP question)"
.br
.ti -1c
.RI "Boolean \fBgetAvailable\fP ()"
.br
.ti -1c
.RI "void \fBsetAvailable\fP (Boolean available)"
.br
.ti -1c
.RI "String \fBgetUsername\fP ()"
.br
.ti -1c
.RI "void \fBsetUsername\fP (String username)"
.br
.ti -1c
.RI "\fBGameSettings\fP \fBgetGameSettings\fP ()"
.br
.ti -1c
.RI "void \fBsetGameSettings\fP (\fBGameSettings\fP gameSettings)"
.br
.ti -1c
.RI "ArrayList< \fBMove\fP > \fBgetPreMoves\fP ()"
.br
.ti -1c
.RI "void \fBsetPreMoves\fP (ArrayList< \fBMove\fP > preMoves)"
.br
.ti -1c
.RI "String \fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBPlayerColor\fP \fBgetPlayerColor\fP ()"
.br
.ti -1c
.RI "void \fBsetPlayerColor\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "\fBMove\fP \fBgetMove\fP ()"
.br
.ti -1c
.RI "void \fBsetMove\fP (\fBMove\fP move)"
.br
.ti -1c
.RI "\fBGameTime\fP \fBgetGameTime\fP ()"
.br
.ti -1c
.RI "void \fBsetGameTime\fP (\fBGameTime\fP gameTime)"
.br
.ti -1c
.RI "\fBGameStatus\fP \fBgetGameStatus\fP ()"
.br
.ti -1c
.RI "void \fBsetGameStatus\fP (\fBGameStatus\fP gameStatus)"
.br
.ti -1c
.RI "\fBMovesList\fP \fBgetPossibleMoves\fP ()"
.br
.ti -1c
.RI "void \fBsetPossibleMoves\fP (\fBMovesList\fP possibleMoves)"
.br
.ti -1c
.RI "\fBBoard\fP \fBgetBoard\fP ()"
.br
.ti -1c
.RI "void \fBsetBoard\fP (\fBBoard\fP board)"
.br
.ti -1c
.RI "\fBLoginInfo\fP \fBgetLoginInfo\fP ()"
.br
.ti -1c
.RI "void \fBsetLoginInfo\fP (\fBLoginInfo\fP loginInfo)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "\fBMessageType\fP \fBgetMessageType\fP ()"
.br
.ti -1c
.RI "boolean \fBisSubject\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMessage\fP \fBaskForLogin\fP ()"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnLogin\fP (\fBLoginInfo\fP loginInfo, \fBMessage\fP respondingTo)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBcancelQuestion\fP (\fBQuestion\fP question, String cause)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBwelcomeMessage\fP (String str, \fBLoginInfo\fP loginInfo)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBinitGame\fP (\fBBoard\fP board, String opponent, \fBPlayerColor\fP player, \fBGameTime\fP gameTime, Stack< \fBMove\fP > moveStack)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBthrowError\fP (\fBMyError\fP error)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBaskForMove\fP (\fBMovesList\fP possibleMoves, \fBGameTime\fP gameTime)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBupdateByMove\fP (\fBMove\fP move, \fBGameTime\fP gameTime)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBwaitForYourTurn\fP (String waitingForName, \fBGameTime\fP gameTime)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBwaitForMatch\fP ()"
.br
.ti -1c
.RI "static \fBMessage\fP \fBgameOver\fP (\fBGameStatus\fP gameStatus)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBaskForGameSettings\fP (\fBSyncedItems\fP joinableGames, \fBSyncedItems\fP resumableGames)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnGameSettings\fP (\fBGameSettings\fP gameSettings, \fBMessage\fP respondingTo)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBinterrupt\fP ()"
.br
.ti -1c
.RI "static \fBMessage\fP \fBbye\fP (String subject)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBerror\fP (String err)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnMove\fP (\fBMove\fP move, \fBMessage\fP respondingTo)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBanswerQuestion\fP (\fBQuestion\&.Answer\fP answer, \fBMessage\fP respondingTo)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBaskQuestion\fP (\fBQuestion\fP question)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBcheckUsernameAvailability\fP (String username)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnUsernameNotAvailable\fP (ArrayList< String > usernameSuggestions, \fBMessage\fP request)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnUsernameAvailable\fP (\fBMessage\fP request)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBdbRequest\fP (\fBDBRequest\fP dbRequest)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBreturnDBResponse\fP (\fBDBResponse\fP \fBDBResponse\fP, \fBMessage\fP request)"
.br
.ti -1c
.RI "static \fBMessage\fP \fBsyncLists\fP (\fBSyncedItems\fP<?>\&.\&.\&. syncedLists)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final String \fBmessageID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "Message\&."
by Ilan Peretz (ilanperets@gmail.com) 10/11/2021 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.Message (\fBMessageType\fP messageType)"
Instantiates a new \fBMessage\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImessageType\fP the message type 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.Message (\fBMessageType\fP messageType, String subject, String respondingToMsgId)"
Instantiates a new \fBMessage\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImessageType\fP the message type 
.br
\fIsubject\fP the subject 
.br
\fIrespondingToMsgId\fP the responding to msg id 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.Message (\fBMessageType\fP messageType, \fBMessage\fP respondingTo)"
Instantiates a new \fBMessage\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImessageType\fP the message type 
.br
\fIrespondingTo\fP the responding to 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.Message (\fBMessageType\fP messageType, String subject)"
Instantiates a new \fBMessage\fP\&.
.PP
\fBParameters\fP
.RS 4
\fImessageType\fP the message type 
.br
\fIsubject\fP the subject 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.answerQuestion (\fBQuestion\&.Answer\fP answer, \fBMessage\fP respondingTo)\fC [static]\fP"
Answer question message\&.
.PP
\fBParameters\fP
.RS 4
\fIrespondingTo\fP the responding to 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.askForGameSettings (\fBSyncedItems\fP joinableGames, \fBSyncedItems\fP resumableGames)\fC [static]\fP"
Ask for game settings message\&.
.PP
\fBParameters\fP
.RS 4
\fIjoinableGames\fP the joinable games 
.br
\fIresumableGames\fP the resumable games 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.askForLogin ()\fC [static]\fP"
Ask for login message\&.
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.askQuestion (\fBQuestion\fP question)\fC [static]\fP"
Ask question message\&.
.PP
\fBParameters\fP
.RS 4
\fIquestion\fP the question 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.bye (String subject)\fC [static]\fP"
Bye message\&.
.PP
\fBParameters\fP
.RS 4
\fIsubject\fP the subject 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.checkUsernameAvailability (String username)\fC [static]\fP"
Check username availability message\&.
.PP
\fBParameters\fP
.RS 4
\fIusername\fP the username 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.dbRequest (\fBDBRequest\fP dbRequest)\fC [static]\fP"
Db request message\&.
.PP
\fBParameters\fP
.RS 4
\fIdbRequest\fP the db request 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.error (String err)\fC [static]\fP"
Error message\&.
.PP
\fBParameters\fP
.RS 4
\fIerr\fP the err 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.gameOver (\fBGameStatus\fP gameStatus)\fC [static]\fP"
Game over message\&.
.PP
\fBParameters\fP
.RS 4
\fIgameStatus\fP the game status 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "Boolean ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getAvailable ()"
Gets available\&.
.PP
\fBReturns\fP
.RS 4
the available 
.RE
.PP

.SS "\fBBoard\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getBoard ()"
Gets board\&.
.PP
\fBReturns\fP
.RS 4
the board 
.RE
.PP

.SS "\fBDBRequest\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getDBRequest ()"
Gets db request\&.
.PP
\fBReturns\fP
.RS 4
the db request 
.RE
.PP

.SS "\fBDBResponse\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getDBResponse ()"
Gets db response\&.
.PP
\fBReturns\fP
.RS 4
the db response 
.RE
.PP

.SS "\fBMyError\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getError ()"
Gets error\&.
.PP
\fBReturns\fP
.RS 4
the error 
.RE
.PP

.SS "\fBGameSettings\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getGameSettings ()"
Gets game settings\&.
.PP
\fBReturns\fP
.RS 4
the game settings 
.RE
.PP

.SS "\fBGameStatus\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getGameStatus ()"
Gets game status\&.
.PP
\fBReturns\fP
.RS 4
the game status 
.RE
.PP

.SS "\fBGameTime\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getGameTime ()"
Gets game time\&.
.PP
\fBReturns\fP
.RS 4
the game time 
.RE
.PP

.SS "\fBLoginInfo\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getLoginInfo ()"
Gets login info\&.
.PP
\fBReturns\fP
.RS 4
the login info 
.RE
.PP

.SS "\fBMessageType\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getMessageType ()"
Gets message type\&.
.PP
\fBReturns\fP
.RS 4
the message type 
.RE
.PP

.SS "\fBMove\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getMove ()"
Gets move\&.
.PP
\fBReturns\fP
.RS 4
the move 
.RE
.PP

.SS "Stack< \fBMove\fP > ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getMoveStack ()"
Gets move stack\&.
.PP
\fBReturns\fP
.RS 4
the move stack 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getOtherPlayer ()"
Gets other player\&.
.PP
\fBReturns\fP
.RS 4
the other player 
.RE
.PP

.SS "\fBPlayerColor\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getPlayerColor ()"
Gets player color\&.
.PP
\fBReturns\fP
.RS 4
the player color 
.RE
.PP

.SS "\fBMovesList\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getPossibleMoves ()"
Gets possible moves\&.
.PP
\fBReturns\fP
.RS 4
the possible moves 
.RE
.PP

.SS "ArrayList< \fBMove\fP > ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getPreMoves ()"
Gets pre moves\&.
.PP
\fBReturns\fP
.RS 4
the pre moves 
.RE
.PP

.SS "\fBQuestion\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getQuestion ()"
Gets question\&.
.PP
\fBReturns\fP
.RS 4
the question 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getRespondingToMsgId ()"
Gets responding to msg id\&.
.PP
\fBReturns\fP
.RS 4
the responding to msg id 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getSubject ()"
Gets subject\&.
.PP
\fBReturns\fP
.RS 4
the subject 
.RE
.PP

.SS "\fBSyncedItems\fP<?>[] ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getSyncedLists ()"
Get synced lists synced items [ ]\&.
.PP
\fBReturns\fP
.RS 4
the synced items [ ] 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getUsername ()"
Gets username\&.
.PP
\fBReturns\fP
.RS 4
the username 
.RE
.PP

.SS "ArrayList< String > ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.getUsernameSuggestions ()"
Gets username suggestions\&.
.PP
\fBReturns\fP
.RS 4
the username suggestions 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.initGame (\fBBoard\fP board, String opponent, \fBPlayerColor\fP player, \fBGameTime\fP gameTime, Stack< \fBMove\fP > moveStack)\fC [static]\fP"
Init game message\&.
.PP
\fBParameters\fP
.RS 4
\fIboard\fP the board 
.br
\fIopponent\fP the opponent 
.br
\fIplayer\fP the player 
.br
\fIgameTime\fP the game time 
.br
\fImoveStack\fP the move stack 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.interrupt ()\fC [static]\fP"
Interrupt message\&.
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.isResponse ()"
Is response boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.isSubject ()"
Is subject boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnDBResponse (\fBDBResponse\fP DBResponse, \fBMessage\fP request)\fC [static]\fP"
Return db response message\&.
.PP
\fBParameters\fP
.RS 4
\fIDBResponse\fP the db response 
.br
\fIrequest\fP the request 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnGameSettings (\fBGameSettings\fP gameSettings, \fBMessage\fP respondingTo)\fC [static]\fP"
Return game settings message\&.
.PP
\fBParameters\fP
.RS 4
\fIgameSettings\fP the game settings 
.br
\fIrespondingTo\fP the responding to 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnLogin (\fBLoginInfo\fP loginInfo, \fBMessage\fP respondingTo)\fC [static]\fP"
Return login message\&.
.PP
\fBParameters\fP
.RS 4
\fIloginInfo\fP the login info 
.br
\fIrespondingTo\fP the responding to 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnMove (\fBMove\fP move, \fBMessage\fP respondingTo)\fC [static]\fP"
Return move message\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.br
\fIrespondingTo\fP the responding to 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnUsernameAvailable (\fBMessage\fP request)\fC [static]\fP"
Return username available message\&.
.PP
\fBParameters\fP
.RS 4
\fIrequest\fP the request 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.returnUsernameNotAvailable (ArrayList< String > usernameSuggestions, \fBMessage\fP request)\fC [static]\fP"
Return username not available message\&.
.PP
\fBParameters\fP
.RS 4
\fIusernameSuggestions\fP the username suggestions 
.br
\fIrequest\fP the request 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setAvailable (Boolean available)"
Sets available\&.
.PP
\fBParameters\fP
.RS 4
\fIavailable\fP the available 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setBoard (\fBBoard\fP board)"
Sets board\&.
.PP
\fBParameters\fP
.RS 4
\fIboard\fP the board 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setDbRequest (\fBDBRequest\fP dbRequest)"
Sets db request\&.
.PP
\fBParameters\fP
.RS 4
\fIdbRequest\fP the db request 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setDBResponse (\fBDBResponse\fP requestedStats)"
Sets db response\&.
.PP
\fBParameters\fP
.RS 4
\fIrequestedStats\fP the requested stats 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setError (\fBMyError\fP error)"
Sets error\&.
.PP
\fBParameters\fP
.RS 4
\fIerror\fP the error 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setGameSettings (\fBGameSettings\fP gameSettings)"
Sets game settings\&.
.PP
\fBParameters\fP
.RS 4
\fIgameSettings\fP the game settings 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setGameStatus (\fBGameStatus\fP gameStatus)"
Sets game status\&.
.PP
\fBParameters\fP
.RS 4
\fIgameStatus\fP the game status 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setGameTime (\fBGameTime\fP gameTime)"
Sets game time\&.
.PP
\fBParameters\fP
.RS 4
\fIgameTime\fP the game time 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setLoginInfo (\fBLoginInfo\fP loginInfo)"
Sets login info\&.
.PP
\fBParameters\fP
.RS 4
\fIloginInfo\fP the login info 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setMove (\fBMove\fP move)"
Sets move\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setMoveStack (Stack< \fBMove\fP > moveStack)"
Sets move stack\&.
.PP
\fBParameters\fP
.RS 4
\fImoveStack\fP the move stack 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setOtherPlayer (String otherPlayer)"
Sets other player\&.
.PP
\fBParameters\fP
.RS 4
\fIotherPlayer\fP the other player 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setPlayerColor (\fBPlayerColor\fP playerColor)"
Sets player color\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setPossibleMoves (\fBMovesList\fP possibleMoves)"
Sets possible moves\&.
.PP
\fBParameters\fP
.RS 4
\fIpossibleMoves\fP the possible moves 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setPreMoves (ArrayList< \fBMove\fP > preMoves)"
Sets pre moves\&.
.PP
\fBParameters\fP
.RS 4
\fIpreMoves\fP the pre moves 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setQuestion (\fBQuestion\fP question)"
Sets question\&.
.PP
\fBParameters\fP
.RS 4
\fIquestion\fP the question 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setRespondingTo (\fBMessage\fP msg)"
Sets responding to\&.
.PP
\fBParameters\fP
.RS 4
\fImsg\fP the msg 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setRespondingToMsgId (String respondingToMsgId)"
Sets responding to msg id\&.
.PP
\fBParameters\fP
.RS 4
\fIrespondingToMsgId\fP the responding to msg id 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setSyncedLists (\fBSyncedItems\fP<?>\&.\&.\&. syncedLists)"
Sets synced lists\&.
.PP
\fBParameters\fP
.RS 4
\fIsyncedLists\fP the synced lists 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setUsername (String username)"
Sets username\&.
.PP
\fBParameters\fP
.RS 4
\fIusername\fP the username 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.setUsernameSuggestions (ArrayList< String > usernameSuggestions)"
Sets username suggestions\&.
.PP
\fBParameters\fP
.RS 4
\fIusernameSuggestions\fP the username suggestions 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.syncLists (\fBSyncedItems\fP<?>\&.\&.\&. syncedLists)\fC [static]\fP"
Sync lists message\&.
.PP
\fBParameters\fP
.RS 4
\fIsyncedLists\fP the synced lists 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.throwError (\fBMyError\fP error)\fC [static]\fP"
Throw error message\&.
.PP
\fBParameters\fP
.RS 4
\fIerror\fP if null interrupts 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.updateByMove (\fBMove\fP move, \fBGameTime\fP gameTime)\fC [static]\fP"
Update by move message\&.
.PP
\fBParameters\fP
.RS 4
\fImove\fP the move 
.br
\fIgameTime\fP the game time 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.waitForMatch ()\fC [static]\fP"
Wait for match message\&.
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.waitForYourTurn (String waitingForName, \fBGameTime\fP gameTime)\fC [static]\fP"
Wait for your turn message\&.
.PP
\fBParameters\fP
.RS 4
\fIwaitingForName\fP the waiting for name 
.br
\fIgameTime\fP the game time 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SS "static \fBMessage\fP ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.welcomeMessage (String str, \fBLoginInfo\fP loginInfo)\fC [static]\fP"
Welcome message message\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.br
\fIloginInfo\fP the login info 
.RE
.PP
\fBReturns\fP
.RS 4
the message 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String ver14\&.SharedClasses\&.Networking\&.Messages\&.Message\&.messageID"
The \fBMessage\fP id\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
