.TH "ver14.SharedClasses.Sync.SyncedItems< E extends SyncableItem >.Remover< L >" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Sync.SyncedItems< E extends SyncableItem >.Remover< L >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBremove\fP (L item)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
