.TH "ver14.SharedClasses.DBActions.DBRequest.PreMadeRequest.VariationCreator" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.DBRequest.PreMadeRequest.VariationCreator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Variation \fBcreate\fP (\fBRequestBuilder\fP actualBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Variation creator - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Variation ver14\&.SharedClasses\&.DBActions\&.DBRequest\&.PreMadeRequest\&.VariationCreator\&.create (\fBRequestBuilder\fP actualBuilder)"
Create variation\&.
.PP
\fBParameters\fP
.RS 4
\fIactualBuilder\fP the actual builder 
.RE
.PP
\fBReturns\fP
.RS 4
the variation 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
