.TH "ver14.SharedClasses.DBActions.Table.Math" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.Table.Math
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCol\fP \fBexecute\fP (\fBCol\fP \fBcol\fP, Object value)"
.br
.ti -1c
.RI "\fBCol\fP \fBexecute\fP (\fBCol\fP \fBcol\fP, Object value, boolean changeSelf)"
.br
.ti -1c
.RI "String \fBstrSource\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBnullIf0\fP (Object val)"
.br
.ti -1c
.RI "static String \fBformatNum\fP (Object num)"
.br
.ti -1c
.RI "static String \fBstrVal\fP (Object val)"
.br
.ti -1c
.RI "static String \fBformatNum\fP (Object num, String format)"
.br
.ti -1c
.RI "static String \fBstr\fP (Object obj)"
.br
.ti -1c
.RI "static String \fBasFloat\fP (Object num)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPlus\fP"
.br
.ti -1c
.RI "\fBMult\fP"
.br
.ti -1c
.RI "\fBDiv\fP"
.br
.ti -1c
.RI "\fBCol\fP \fBcol\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBzeroIfNull\fP ()"
.br
.ti -1c
.RI "abstract void \fBapply\fP (Object value)"
.br
.ti -1c
.RI "void \fBsimpleOperation\fP (Object a, String operation, Object b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMath\fP - allows for math actions on columns and some math-related utilities for columns\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract void ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.apply (Object value)\fC [abstract]\fP, \fC [protected]\fP"
Apply\&.
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP the value 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.asFloat (Object num)\fC [static]\fP"
As float string\&.
.PP
\fBParameters\fP
.RS 4
\fInum\fP the num 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "\fBCol\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.execute (\fBCol\fP col, Object value)"
Execute col\&.
.PP
\fBParameters\fP
.RS 4
\fIcol\fP the col 
.br
\fIvalue\fP the value 
.RE
.PP
\fBReturns\fP
.RS 4
the col 
.RE
.PP

.SS "\fBCol\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.execute (\fBCol\fP col, Object value, boolean changeSelf)"
Execute col\&.
.PP
\fBParameters\fP
.RS 4
\fIcol\fP the col 
.br
\fIvalue\fP the value 
.br
\fIchangeSelf\fP the change self 
.RE
.PP
\fBReturns\fP
.RS 4
the col 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.formatNum (Object num)\fC [static]\fP"
Format num string\&.
.PP
\fBParameters\fP
.RS 4
\fInum\fP the num 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.formatNum (Object num, String format)\fC [static]\fP"
Format num string\&.
.PP
\fBParameters\fP
.RS 4
\fInum\fP the num 
.br
\fIformat\fP the format 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.nullIf0 (Object val)\fC [static]\fP"
Null if 0 string\&.
.PP
\fBParameters\fP
.RS 4
\fIval\fP the val 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.simpleOperation (Object a, String operation, Object b)\fC [protected]\fP"
Simple operation\&.
.PP
\fBParameters\fP
.RS 4
\fIa\fP the a 
.br
\fIoperation\fP the operation 
.br
\fIb\fP the b 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.str (Object obj)\fC [static]\fP"
Str string\&.
.PP
\fBParameters\fP
.RS 4
\fIobj\fP the obj 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.strSource ()"
Str source string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.strVal (Object val)\fC [static]\fP"
Str val string\&.
.PP
\fBParameters\fP
.RS 4
\fIval\fP the val 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.zeroIfNull ()\fC [protected]\fP"
Zero if null\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBCol\fP ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.col"
The \fBCol\fP\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.Div"
\fBInitial value:\fP
.PP
.nf
={
        @Override
        protected void apply(Object value) {
            simpleOperation(formatNum(strSource()), "/", nullIf0(value));
            zeroIfNull();
        }
    }
.fi
The Div\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.Mult"
\fBInitial value:\fP
.PP
.nf
={
        @Override
        protected void apply(Object value) {
            simpleOperation(formatNum(strSource()), "*", formatNum(strVal(value)));
        }
    }
.fi
The Mult\&. 
.SS "ver14\&.SharedClasses\&.DBActions\&.Table\&.Math\&.Plus"
\fBInitial value:\fP
.PP
.nf
={
        @Override
        protected void apply(Object value) {
            simpleOperation(strSource(), "+", strVal(value));
        }
    }
.fi
The Plus\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
