.TH "ver14.SharedClasses.DBActions.DBResponse.TableDBResponse" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.DBResponse.TableDBResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableDBResponse\fP (String[] \fBcolumns\fP, String[][] \fBrows\fP, \fBDBRequest\fP \fBrequest\fP)"
.br
.ti -1c
.RI "\fBTableDBResponse\fP (String[] \fBcolumns\fP, String[][] \fBrows\fP, \fBStatus\fP \fBstatus\fP, \fBDBRequest\fP \fBrequest\fP)"
.br
.ti -1c
.RI "int \fBnumOfRows\fP ()"
.br
.ti -1c
.RI "String[] \fBgetFirstRow\fP ()"
.br
.ti -1c
.RI "String \fBgetCell\fP (int row, String col)"
.br
.ti -1c
.RI "String \fBgetCell\fP (int row, \fBCol\fP col)"
.br
.ti -1c
.RI "boolean \fBisAnyData\fP ()"
.br
.ti -1c
.RI "\fBTableDBResponse\fP \fBclean\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBrowToString\fP (String[] row)"
.br
.ti -1c
.RI "String[] \fBgetColumns\fP ()"
.br
.ti -1c
.RI "String[][] \fBgetRows\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTableDBResponse\fP ()"
.br
.ti -1c
.RI "int \fBgetColumnIndex\fP (String column)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "String[] \fBcolumns\fP"
.br
.ti -1c
.RI "String[][] \fBrows\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table db response - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.TableDBResponse (String[] columns, String rows[][], \fBDBRequest\fP request)"
Instantiates a new Table db response\&.
.PP
\fBParameters\fP
.RS 4
\fIcolumns\fP the columns 
.br
\fIrows\fP the rows 
.br
\fIrequest\fP the request 
.RE
.PP

.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.TableDBResponse (String[] columns, String rows[][], \fBStatus\fP status, \fBDBRequest\fP request)"
Instantiates a new Table db response\&.
.PP
\fBParameters\fP
.RS 4
\fIcolumns\fP the columns 
.br
\fIrows\fP the rows 
.br
\fIstatus\fP the status 
.br
\fIrequest\fP the request 
.RE
.PP

.SS "ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.TableDBResponse ()\fC [protected]\fP"
Instantiates a new Table db response\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBTableDBResponse\fP ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.clean ()"
Clean table db response\&.
.PP
\fBReturns\fP
.RS 4
the table db response 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getCell (int row, \fBCol\fP col)"
Gets cell\&.
.PP
\fBParameters\fP
.RS 4
\fIrow\fP the row 
.br
\fIcol\fP the col 
.RE
.PP
\fBReturns\fP
.RS 4
the cell 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getCell (int row, String col)"
Gets cell\&.
.PP
\fBParameters\fP
.RS 4
\fIrow\fP the row 
.br
\fIcol\fP the col 
.RE
.PP
\fBReturns\fP
.RS 4
the cell 
.RE
.PP

.SS "int ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getColumnIndex (String column)\fC [protected]\fP"
Gets column index\&.
.PP
\fBParameters\fP
.RS 4
\fIcolumn\fP the column 
.RE
.PP
\fBReturns\fP
.RS 4
the column index 
.RE
.PP

.SS "String[] ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getColumns ()"
Get columns string [ ]\&.
.PP
\fBReturns\fP
.RS 4
the string [ ] 
.RE
.PP

.SS "String[] ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getFirstRow ()"
Get first row string [ ]\&.
.PP
\fBReturns\fP
.RS 4
the string [ ] 
.RE
.PP

.SS "String[][] ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.getRows ()"
Get rows string [ ] [ ]\&.
.PP
\fBReturns\fP
.RS 4
the string [ ] [ ] 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.isAnyData ()"
Is any data boolean\&.
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SS "int ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.numOfRows ()"
Num of rows int\&.
.PP
\fBReturns\fP
.RS 4
the int 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.rowToString (String[] row)"
Row to string string\&.
.PP
\fBParameters\fP
.RS 4
\fIrow\fP the row 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.PP
Reimplemented from \fBver14\&.SharedClasses\&.DBActions\&.DBResponse\&.DBResponse\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "String [] ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.columns\fC [protected]\fP"
The Columns\&. 
.SS "String [][] ver14\&.SharedClasses\&.DBActions\&.DBResponse\&.TableDBResponse\&.rows\fC [protected]\fP"
The Rows\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
