.TH "ver14.SharedClasses.UI.MyJFrame.MyAdapter.HeldDown" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.MyJFrame.MyAdapter.HeldDown
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstartPress\fP ()"
.br
.ti -1c
.RI "void \fBendPress\fP ()"
.br
.ti -1c
.RI "int \fBkey\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The interface Held down\&. 
.SH "Member Function Documentation"
.PP 
.SS "void ver14\&.SharedClasses\&.UI\&.MyJFrame\&.MyAdapter\&.HeldDown\&.endPress ()"
End press\&. 
.SS "int ver14\&.SharedClasses\&.UI\&.MyJFrame\&.MyAdapter\&.HeldDown\&.key ()"
Key int\&.
.PP
\fBReturns\fP
.RS 4
the int 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.MyJFrame\&.MyAdapter\&.HeldDown\&.startPress ()"
Start press\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
