.TH "ver14.SharedClasses.Game.Moves.CastlingRights" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Game.Moves.CastlingRights
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBSide\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCastlingRights\fP (byte rights)"
.br
.ti -1c
.RI "\fBCastlingRights\fP ()"
.br
.ti -1c
.RI "\fBCastlingRights\fP (\fBCastlingRights\fP other)"
.br
.ti -1c
.RI "void \fBenableCastling\fP (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "boolean \fBisEnabled\fP (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
.br
.ti -1c
.RI "byte \fBdisableCastling\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "byte \fBdisableCastling\fP (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
.br
.ti -1c
.RI "byte \fBgetRights\fP ()"
.br
.ti -1c
.RI "void \fBenable\fP (byte b)"
.br
.ti -1c
.RI "boolean \fBhasAny\fP (\fBPlayerColor\fP playerColor)"
.br
.ti -1c
.RI "byte \fBgetPlayersCastling\fP (\fBPlayerColor\fP playerColor)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCastlingRights\fP \fBcreateFromStr\fP (String castlingAbilityStr)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static \fBPlayerColor\fP \fBwhosCastling\fP (byte castlingRights)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBNO_CASTLING_ABILITY\fP = '\-'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Castling rights - \&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.CastlingRights (byte rights)"
Instantiates a new Castling rights\&.
.PP
\fBParameters\fP
.RS 4
\fIrights\fP the rights 
.RE
.PP

.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.CastlingRights ()"
Instantiates a new Castling rights\&. 
.SS "ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.CastlingRights (\fBCastlingRights\fP other)"
Instantiates a new Castling rights\&.
.PP
\fBParameters\fP
.RS 4
\fIother\fP the other 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBCastlingRights\fP ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.createFromStr (String castlingAbilityStr)\fC [static]\fP"
Create from str castling rights\&.
.PP
\fBParameters\fP
.RS 4
\fIcastlingAbilityStr\fP the castling ability str 
.RE
.PP
\fBReturns\fP
.RS 4
the castling rights 
.RE
.PP

.SS "byte ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.disableCastling (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
Disable castling byte\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.br
\fIside\fP the side 
.RE
.PP
\fBReturns\fP
.RS 4
the byte 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.enable (byte b)"
Enable\&.
.PP
\fBParameters\fP
.RS 4
\fIb\fP the b 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.enableCastling (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
Enable castling\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.br
\fIside\fP the side 
.RE
.PP

.SS "byte ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.getPlayersCastling (\fBPlayerColor\fP playerColor)"
Gets players castling\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.RE
.PP
\fBReturns\fP
.RS 4
the players castling 
.RE
.PP

.SS "byte ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.getRights ()"
Gets rights\&.
.PP
\fBReturns\fP
.RS 4
the rights 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.hasAny (\fBPlayerColor\fP playerColor)"
Has any boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "boolean ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.isEnabled (\fBPlayerColor\fP playerColor, \fBSide\fP side)"
Is enabled boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIplayerColor\fP the player color 
.br
\fIside\fP the side 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "static void ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.main (String[] args)\fC [static]\fP"
The entry point of application\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP the input arguments 
.RE
.PP

.SS "String ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.toString ()"
To string string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static \fBPlayerColor\fP ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.whosCastling (byte castlingRights)\fC [static]\fP"
Whos castling player color\&.
.PP
\fBParameters\fP
.RS 4
\fIcastlingRights\fP the castling rights 
.RE
.PP
\fBReturns\fP
.RS 4
the player color 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String ver14\&.SharedClasses\&.Game\&.Moves\&.CastlingRights\&.NO_CASTLING_ABILITY = '\-'\fC [static]\fP"
The constant NO_CASTLING_ABILITY\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
