.TH "ver14.SharedClasses.Threads.ThreadsManager" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Threads.ThreadsManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBaddThread\fP (\fBMyThread\fP thread)"
.br
.ti -1c
.RI "static void \fBstopAll\fP ()"
.br
.ti -1c
.RI "static void \fBhandleErrors\fP (\fBThrowingRunnable\fP runnable)"
.br
.ti -1c
.RI "static \fBMyThread\fP \fBcreateThread\fP (\fBThrowingRunnable\fP runnable, boolean start)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type Threads manager\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBMyThread\fP ver14\&.SharedClasses\&.Threads\&.ThreadsManager\&.createThread (\fBThrowingRunnable\fP runnable, boolean start)\fC [static]\fP"
Create thread my thread\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.br
\fIstart\fP the start 
.RE
.PP
\fBReturns\fP
.RS 4
the my thread 
.RE
.PP

.SS "static void ver14\&.SharedClasses\&.Threads\&.ThreadsManager\&.handleErrors (\fBThrowingRunnable\fP runnable)\fC [static]\fP"
Handle errors\&.
.PP
\fBParameters\fP
.RS 4
\fIrunnable\fP the runnable 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
