.TH "ver14.SharedClasses.DBActions.Statements.Selection.Join" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.DBActions.Statements.Selection.Join
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBLEFT\fP = 'LEFT JOIN'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJoin\fP - selection join\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "String ver14\&.SharedClasses\&.DBActions\&.Statements\&.Selection\&.Join\&.LEFT = 'LEFT JOIN'"
The constant LEFT\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
