.TH "ver14.SharedClasses.Utils.StrUtils" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.Utils.StrUtils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIterationThingy\fP"
.br
.ti -1c
.RI "enum \fBTimeRange\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBdontCapFull\fP (String str)"
.br
.ti -1c
.RI "static String \fBhtmlNewLines\fP (String str)"
.br
.ti -1c
.RI "static int \fBcountMatches\fP (String str, @Language('RegExp') String match)"
.br
.ti -1c
.RI "static String[][] \fBformat\fP (String[][] mat)"
.br
.ti -1c
.RI "static String[] \fBformat\fP (String[] arr)"
.br
.ti -1c
.RI "static String \fBformat\fP (String str)"
.br
.ti -1c
.RI "static boolean \fBisEmpty\fP (String str)"
.br
.ti -1c
.RI "static String \fBformatDate\fP (String longStr)"
.br
.ti -1c
.RI "static String \fBformatDate\fP (Date date)"
.br
.ti -1c
.RI "static String \fBformatDate\fP (Date date, String \fBformat\fP)"
.br
.ti -1c
.RI "static String \fBparseURLS\fP (String str)"
.br
.ti -1c
.RI "static String \fBuppercase\fP (String str)"
.br
.ti -1c
.RI "static String \fBdontCapWord\fP (String str)"
.br
.ti -1c
.RI "static String \fBformatDateSQL\fP (Date date)"
.br
.ti -1c
.RI "static int \fBgetPort\fP (Socket socket)"
.br
.ti -1c
.RI "static int \fBgetPort\fP (SocketAddress socketAddress)"
.br
.ti -1c
.RI "static String \fBgetUrl\fP (Socket socket)"
.br
.ti -1c
.RI "static String \fBgetUrl\fP (SocketAddress socketAddress)"
.br
.ti -1c
.RI "static String \fBfitInside\fP (String str, JComponent comp)"
.br
.ti -1c
.RI "static String \fBfixHtml\fP (String str)"
.br
.ti -1c
.RI "static String \fBstrINN\fP (Object\&.\&.\&. objs)"
.br
.ti -1c
.RI "static String \fBsplitArr\fP (Object[] arr)"
.br
.ti -1c
.RI "static String \fBsplitArr\fP (String divide, Object[] arr)"
.br
.ti -1c
.RI "static String \fBsplitArr\fP (String divide, Object[] arr, boolean \fBformat\fP)"
.br
.ti -1c
.RI "static String \fBclean\fP (String str)"
.br
.ti -1c
.RI "static String \fBcreateTimeGreeting\fP ()"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static String \fBcreateTimeStr\fP (long millis)"
.br
.ti -1c
.RI "static String \fBawful\fP (String og)"
.br
.ti -1c
.RI "static String \fBdateTimePrefix\fP (String str)"
.br
.ti -1c
.RI "static String \fBrepeat\fP (\fBIterationThingy\fP< String > iterationThingy, int numOfIterations)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Str utils\&.
.PP
\fBAuthor\fP
.RS 4
Bezalel Avrahami (bezalel3250@gmail.com) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.awful (String og)\fC [static]\fP"
Awful string\&.
.PP
\fBParameters\fP
.RS 4
\fIog\fP the og 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.clean (String str)\fC [static]\fP"
Clean string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static int ver14\&.SharedClasses\&.Utils\&.StrUtils\&.countMatches (String str, @Language('RegExp') String match)\fC [static]\fP"
Count matches int\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.br
\fImatch\fP the match 
.RE
.PP
\fBReturns\fP
.RS 4
the int 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.createTimeGreeting ()\fC [static]\fP"
Create time greeting string\&.
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.createTimeStr (long millis)\fC [static]\fP"
Create time str string\&.
.PP
\fBParameters\fP
.RS 4
\fImillis\fP the millis 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.dateTimePrefix (String str)\fC [static]\fP"
Date time prefix string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.dontCapFull (String str)\fC [static]\fP"
Dont cap full string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.dontCapWord (String str)\fC [static]\fP"
Dont cap word string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.fitInside (String str, JComponent comp)\fC [static]\fP"
Fit inside string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.br
\fIcomp\fP the comp 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.fixHtml (String str)\fC [static]\fP"
Fix html string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.format (String str)\fC [static]\fP"
Format string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String[] ver14\&.SharedClasses\&.Utils\&.StrUtils\&.format (String[] arr)\fC [static]\fP"
Format string [ ]\&.
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the arr 
.RE
.PP
\fBReturns\fP
.RS 4
the string [ ] 
.RE
.PP

.SS "static String[][] ver14\&.SharedClasses\&.Utils\&.StrUtils\&.format (String mat[][])\fC [static]\fP"
Format string [ ] [ ]\&.
.PP
\fBParameters\fP
.RS 4
\fImat\fP the mat 
.RE
.PP
\fBReturns\fP
.RS 4
the string [ ] [ ] 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.formatDate (Date date)\fC [static]\fP"
Format date string\&.
.PP
\fBParameters\fP
.RS 4
\fIdate\fP the date 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.formatDate (Date date, String format)\fC [static]\fP"
Format date string\&.
.PP
\fBParameters\fP
.RS 4
\fIdate\fP the date 
.br
\fIformat\fP the format 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.formatDate (String longStr)\fC [static]\fP"
Format date string\&.
.PP
\fBParameters\fP
.RS 4
\fIlongStr\fP the long str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.formatDateSQL (Date date)\fC [static]\fP"
Format date sql string\&.
.PP
\fBParameters\fP
.RS 4
\fIdate\fP the date 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static int ver14\&.SharedClasses\&.Utils\&.StrUtils\&.getPort (Socket socket)\fC [static]\fP"
Gets port\&.
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP the socket 
.RE
.PP
\fBReturns\fP
.RS 4
the port 
.RE
.PP

.SS "static int ver14\&.SharedClasses\&.Utils\&.StrUtils\&.getPort (SocketAddress socketAddress)\fC [static]\fP"
Gets port\&.
.PP
\fBParameters\fP
.RS 4
\fIsocketAddress\fP the socket address 
.RE
.PP
\fBReturns\fP
.RS 4
the port 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.getUrl (Socket socket)\fC [static]\fP"
Gets url\&.
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP the socket 
.RE
.PP
\fBReturns\fP
.RS 4
the url 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.getUrl (SocketAddress socketAddress)\fC [static]\fP"
Gets url\&.
.PP
\fBParameters\fP
.RS 4
\fIsocketAddress\fP the socket address 
.RE
.PP
\fBReturns\fP
.RS 4
the url 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.htmlNewLines (String str)\fC [static]\fP"
Html new lines string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static boolean ver14\&.SharedClasses\&.Utils\&.StrUtils\&.isEmpty (String str)\fC [static]\fP"
Is empty boolean\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the boolean 
.RE
.PP

.SS "static void ver14\&.SharedClasses\&.Utils\&.StrUtils\&.main (String[] args)\fC [static]\fP"
The entry point of application\&.
.PP
\fBParameters\fP
.RS 4
\fIargs\fP the input arguments 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.parseURLS (String str)\fC [static]\fP"
Parse urls string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.repeat (\fBIterationThingy\fP< String > iterationThingy, int numOfIterations)\fC [static]\fP"
Repeat string\&.
.PP
\fBParameters\fP
.RS 4
\fIiterationThingy\fP the iteration thingy 
.br
\fInumOfIterations\fP the num of iterations 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.splitArr (Object[] arr)\fC [static]\fP"
Split arr string\&.
.PP
\fBParameters\fP
.RS 4
\fIarr\fP the arr 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.splitArr (String divide, Object[] arr)\fC [static]\fP"
Split arr string\&.
.PP
\fBParameters\fP
.RS 4
\fIdivide\fP the divide 
.br
\fIarr\fP the arr 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.splitArr (String divide, Object[] arr, boolean format)\fC [static]\fP"
Split arr string\&.
.PP
\fBParameters\fP
.RS 4
\fIdivide\fP the divide 
.br
\fIarr\fP the arr 
.br
\fIformat\fP the format 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.strINN (Object\&.\&.\&. objs)\fC [static]\fP"
Str inn string\&.
.PP
\fBParameters\fP
.RS 4
\fIobjs\fP the objs 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP

.SS "static String ver14\&.SharedClasses\&.Utils\&.StrUtils\&.uppercase (String str)\fC [static]\fP"
Uppercase string\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the str 
.RE
.PP
\fBReturns\fP
.RS 4
the string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
