.TH "ver14.SharedClasses.UI.MyJFrame" 3 "Sun Apr 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ver14.SharedClasses.UI.MyJFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBBooleanClosing\fP"
.br
.ti -1c
.RI "interface \fBClosing\fP"
.br
.ti -1c
.RI "class \fBMyAdapter\fP"
.br
.ti -1c
.RI "interface \fBStringClosing\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyJFrame\fP ()  throws HeadlessException "
.br
.ti -1c
.RI "MyAdapter \fBgetMyAdapter\fP ()"
.br
.ti -1c
.RI "void \fBsetOnExit\fP (\fBClosing\fP<?> \fBonClose\fP)"
.br
.ti -1c
.RI "void \fBdoXClick\fP ()"
.br
.ti -1c
.RI "void \fBsetOnResize\fP (\fBVoidCallback\fP onResize)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static MyAdapter \fBdebugAdapter\fP (Window addTo)"
.br
.ti -1c
.RI "static void \fBaddResizeEvent\fP (JRootPane rootPane, \fBVoidCallback\fP onResize)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBClosing\fP<?> \fBonClose\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type My j frame\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ver14\&.SharedClasses\&.UI\&.MyJFrame\&.MyJFrame () throws HeadlessException"
Instantiates a new My j frame\&.
.PP
\fBExceptions\fP
.RS 4
\fIHeadlessException\fP the headless exception 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static MyAdapter ver14\&.SharedClasses\&.UI\&.MyJFrame\&.debugAdapter (Window addTo)\fC [static]\fP"
Debug adapter my adapter\&.
.PP
\fBParameters\fP
.RS 4
\fIaddTo\fP the add to 
.RE
.PP
\fBReturns\fP
.RS 4
the my adapter 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.MyJFrame\&.doXClick ()"
Do x click\&. 
.SS "MyAdapter ver14\&.SharedClasses\&.UI\&.MyJFrame\&.getMyAdapter ()"
Gets my adapter\&.
.PP
\fBReturns\fP
.RS 4
the my adapter 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.MyJFrame\&.setOnExit (\fBClosing\fP<?> onClose)"
Sets on exit\&.
.PP
\fBParameters\fP
.RS 4
\fIonClose\fP the on close 
.RE
.PP

.SS "void ver14\&.SharedClasses\&.UI\&.MyJFrame\&.setOnResize (\fBVoidCallback\fP onResize)"
Sets on resize\&.
.PP
\fBParameters\fP
.RS 4
\fIonResize\fP the on resize 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBClosing\fP<?> ver14\&.SharedClasses\&.UI\&.MyJFrame\&.onClose = null\fC [protected]\fP"
The On close\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
