ver14::SharedClasses::DBActions::DBResponse::DBResponse
final Status ver14.SharedClasses.DBActions.DBResponse.DBResponse.status
The Status.
Referenced by ver14.SharedClasses.DBActions.DBResponse.StatusResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.DBResponse.DBResponse, ver14.SharedClasses.DBActions.DBResponse.DBResponse.getStatus, ver14.SharedClasses.DBActions.DBResponse.DBResponse.isSuccess, ver14.SharedClasses.DBActions.DBResponse.StatusResponse.StatusResponse, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse, ver14.SharedClasses.DBActions.DBResponse.DBResponse.toString.
final DBRequest ver14.SharedClasses.DBActions.DBResponse.DBResponse.request
The Request.
Referenced by ver14.SharedClasses.DBActions.DBResponse.StatusResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.DBResponse.DBResponse, ver14.SharedClasses.DBActions.DBResponse.DBResponse.getRequest, ver14.SharedClasses.DBActions.DBResponse.StatusResponse.StatusResponse, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse.
DBResponse ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes
The Added res.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.DBResponse.getAddedRes, ver14.SharedClasses.DBActions.DBResponse.DBResponse.setAddedRes, ver14.SharedClasses.DBActions.DBResponse.DBResponse.toString, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.toString.
ver14.SharedClasses.DBActions.DBResponse.DBResponse.DBResponse(Status status, DBRequest request)
Instantiates a new Db response. status the status request the request
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.request, ver14.SharedClasses.DBActions.DBResponse.DBResponse.status.
DBRequest ver14.SharedClasses.DBActions.DBResponse.DBResponse.getRequest()
Gets request. the request
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.request.
Status ver14.SharedClasses.DBActions.DBResponse.DBResponse.getStatus()
Gets status. the status
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.status.
boolean ver14.SharedClasses.DBActions.DBResponse.DBResponse.isSuccess()
Is success boolean. the boolean
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.status, ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status.SUCCESS.
abstract boolean ver14.SharedClasses.DBActions.DBResponse.DBResponse.isAnyData()
Is any data boolean. the boolean
DBResponse ver14.SharedClasses.DBActions.DBResponse.DBResponse.getAddedRes()
Gets added res. the added res
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes.
void ver14.SharedClasses.DBActions.DBResponse.DBResponse.setAddedRes(DBResponse addedRes)
Sets added res. addedRes the added res
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean.
abstract DBResponse ver14.SharedClasses.DBActions.DBResponse.DBResponse.clean()
Clean db response. the db response
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.Networking.Messages.Message.setDBResponse.
void ver14.SharedClasses.DBActions.DBResponse.DBResponse.print()
Print.
String ver14.SharedClasses.DBActions.DBResponse.DBResponse.toString()
To string string. the string
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes, ver14.SharedClasses.DBActions.DBResponse.DBResponse.status.