ver14::SharedClasses::DBActions::RequestBuilder
final String ver14.SharedClasses.DBActions.RequestBuilder.TIE_STR
The constant TIE_STR.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
final Arg [] ver14.SharedClasses.DBActions.RequestBuilder.args
The request Arguments.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.getArgs, ver14.SharedClasses.DBActions.RequestBuilder.getArgVal, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
final SQLStatement ver14.SharedClasses.DBActions.RequestBuilder.statement
The Statement.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
final String ver14.SharedClasses.DBActions.RequestBuilder.name
The Name.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.getName, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
String ver14.SharedClasses.DBActions.RequestBuilder.postDescription
The Post description.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.getPostDescription, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
String ver14.SharedClasses.DBActions.RequestBuilder.preDescription
The Pre description.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.getPreDescription, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.subBuilder
The Sub builder.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.createVariation, ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder, ver14.SharedClasses.DBActions.RequestBuilder.statsByTimeOfDay.
final ArrayList<SyncedListType> ver14.SharedClasses.DBActions.RequestBuilder.shouldSync
The Should sync.
String [] ver14.SharedClasses.DBActions.RequestBuilder.builtArgsVals
The Built args vals.
ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder(DBRequest request, PreMadeRequest.Variation variation)
Instantiates a new Request builder. request the request variation the variation
References ver14.SharedClasses.DBActions.DBRequest.DBRequest.getBuilder, ver14.SharedClasses.DBActions.DBRequest.DBRequest.getRequest, ver14.SharedClasses.DBActions.RequestBuilder.postDescription, ver14.SharedClasses.DBActions.RequestBuilder.preDescription, ver14.SharedClasses.DBActions.DBRequest.DBRequest.type.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changePassword, ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic, ver14.SharedClasses.DBActions.RequestBuilder.createVariation, ver14.SharedClasses.DBActions.RequestBuilder.deleteAllUnFinishedGames, ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.RequestBuilder.statsByTimeOfDay, ver14.SharedClasses.DBActions.RequestBuilder.top.
ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder(SQLStatement statement, String name, Arg... args)
Instantiates a new Request builder. statement the statement name the name args the args
References ver14.SharedClasses.DBActions.RequestBuilder.args, ver14.SharedClasses.DBActions.RequestBuilder.name, ver14.SharedClasses.DBActions.RequestBuilder.statement.
ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder(SQLStatement statement, String name, String desc, Arg... args)
Instantiates a new Request builder. statement the statement name the name desc the desc args the args
References ver14.SharedClasses.DBActions.RequestBuilder.args, ver14.SharedClasses.DBActions.RequestBuilder.name, ver14.SharedClasses.DBActions.RequestBuilder.statement.
ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder(SQLStatement statement, String name, String postDescription, String preDescription, Arg... args)
Instantiates a new Request builder. statement the statement name the name postDescription the post description preDescription the pre description args the args
References ver14.SharedClasses.DBActions.RequestBuilder.args, ver14.SharedClasses.DBActions.RequestBuilder.name, ver14.SharedClasses.DBActions.RequestBuilder.postDescription, ver14.SharedClasses.DBActions.RequestBuilder.preDescription, ver14.SharedClasses.DBActions.RequestBuilder.statement.
void ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder(RequestBuilder subBuilder)
Sets sub builder. subBuilder the sub builder
References ver14.SharedClasses.DBActions.RequestBuilder.subBuilder.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.createVariation, ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.RequestBuilder.statsByTimeOfDay, ver14.SharedClasses.DBActions.RequestBuilder.top.
ArrayList< SyncedListType > ver14.SharedClasses.DBActions.RequestBuilder.getShouldSync()
Gets should sync. the should sync
String ver14.SharedClasses.DBActions.RequestBuilder.getArgVal(int index)
Gets arg val. index the index the arg val
References ver14.SharedClasses.DBActions.RequestBuilder.args.
DBResponse ver14.SharedClasses.DBActions.RequestBuilder.createResponse(ResultSet rs, DBRequest request)
Create response db response. rs the rs request the request the db response
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status.ERROR, ver14.SharedClasses.Utils.StrUtils.isEmpty.
String ver14.SharedClasses.DBActions.RequestBuilder.getPreDescription()
Gets pre description. the pre description
References ver14.SharedClasses.DBActions.RequestBuilder.preDescription.
String ver14.SharedClasses.DBActions.RequestBuilder.getPostDescription()
Gets post description. the post description
References ver14.SharedClasses.DBActions.RequestBuilder.postDescription.
String ver14.SharedClasses.DBActions.RequestBuilder.getName()
Gets name. the name
References ver14.SharedClasses.DBActions.RequestBuilder.name.
Arg[] ver14.SharedClasses.DBActions.RequestBuilder.getArgs()
Get args arg [ ]. the arg [ ]
References ver14.SharedClasses.DBActions.RequestBuilder.args.
DBRequest ver14.SharedClasses.DBActions.RequestBuilder.build(Object... argsVals)
Build db request. argsVals the args vals the db request
References ver14.SharedClasses.DBActions.RequestBuilder.args, ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.Arg.Arg.createVal, ver14.SharedClasses.DBActions.RequestBuilder.postDescription, ver14.SharedClasses.DBActions.RequestBuilder.preDescription, ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.Statements.SQLStatement.replace, ver14.SharedClasses.DBActions.DBRequest.DBRequest.setSubRequest, ver14.SharedClasses.DBActions.RequestBuilder.statement, ver14.SharedClasses.DBActions.RequestBuilder.subBuilder.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.createVariation.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.createVariation(ObjCallback< RequestBuilder > og, PreMadeRequest.VariationCreator variationCreator)
Create variation request builder. og the og variationCreator the variation creator the request builder
References ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder, ver14.SharedClasses.DBActions.RequestBuilder.subBuilder.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.changePassword()
Change password request builder. the request builder
References ver14.SharedClasses.DBActions.Condition.equals, ver14.SharedClasses.DBActions.Arg.ArgType.Password, ver14.SharedClasses.DBActions.Table.Col.Password, ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.Arg.Arg.setUserInput, ver14.SharedClasses.DBActions.Arg.ArgType.Username, ver14.SharedClasses.DBActions.Table.Col.Username, ver14.SharedClasses.DBActions.Table.Table.Users.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic()
Change profile pic request builder. the request builder
References ver14.SharedClasses.DBActions.RequestBuilder.addShouldSync, ver14.SharedClasses.DBActions.Condition.equals, ver14.SharedClasses.DBActions.Arg.ArgType.PictureUrl, ver14.SharedClasses.DBActions.Table.Col.ProfilePic, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.Arg.ArgType.Username, ver14.SharedClasses.DBActions.Table.Col.Username, ver14.SharedClasses.DBActions.Table.Table.Users.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.deleteAllUnFinishedGames()
Delete all un finished games request builder. the request builder
References ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.Table.Table.UnfinishedGames, ver14.SharedClasses.DBActions.Arg.ArgType.Username.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.games()
Games request builder. the request builder
References ver14.SharedClasses.DBActions.Condition.and, ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Condition.between, ver14.SharedClasses.DBActions.Table.Col.CreatedDateTime, ver14.SharedClasses.DBActions.Arg.ArgType.Date, ver14.SharedClasses.DBActions.Table.Col.date, ver14.SharedClasses.DBActions.Table.SwitchCase.defaultCase, ver14.SharedClasses.DBActions.Statements.Selection.Order.DESC, ver14.SharedClasses.DBActions.Table.SwitchCase.equals, ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.Table.Table.Games, ver14.SharedClasses.DBActions.Table.Col.of, ver14.SharedClasses.DBActions.Table.Col.Player1, ver14.SharedClasses.DBActions.Table.Col.Player2, ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder, ver14.SharedClasses.DBActions.Table.Col.switchCase, ver14.SharedClasses.DBActions.Arg.ArgType.Username.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.statsByTimeOfDay()
Stats by time of day request builder. the request builder
References ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder, ver14.SharedClasses.DBActions.RequestBuilder.subBuilder, ver14.SharedClasses.DBActions.Arg.ArgType.Username.
static RequestBuilder ver14.SharedClasses.DBActions.RequestBuilder.top()
Top request builder. the request builder
References ver14.SharedClasses.DBActions.Condition.and, ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.count, ver14.SharedClasses.DBActions.Table.Col.countIf, ver14.SharedClasses.DBActions.Statements.Selection.Order.DESC, ver14.SharedClasses.DBActions.Table.Math.Div, ver14.SharedClasses.DBActions.Condition.equals, ver14.SharedClasses.DBActions.Table.Table.Games, ver14.SharedClasses.DBActions.Statements.Selection.join, ver14.SharedClasses.DBActions.Table.Col.label, ver14.SharedClasses.DBActions.Statements.Selection.Join.LEFT, ver14.SharedClasses.DBActions.Table.Col.math, ver14.SharedClasses.DBActions.Table.Math.Mult, ver14.SharedClasses.DBActions.Statements.Selection.nestMe, ver14.SharedClasses.DBActions.Condition.notEquals, ver14.SharedClasses.DBActions.Arg.ArgType.Number, ver14.SharedClasses.DBActions.Table.Col.of, ver14.SharedClasses.DBActions.Statements.Selection.orderBy, ver14.SharedClasses.DBActions.Table.Math.Plus, ver14.SharedClasses.DBActions.Arg.Arg.repInStr, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.RequestBuilder.setSubBuilder, ver14.SharedClasses.DBActions.Table.Col.sum, ver14.SharedClasses.DBActions.RequestBuilder.TIE_STR, ver14.SharedClasses.DBActions.Statements.Selection.top, ver14.SharedClasses.DBActions.Table.Col.Username, ver14.SharedClasses.DBActions.Table.Table.Users, ver14.SharedClasses.DBActions.Table.Col.Winner.
void ver14.SharedClasses.DBActions.RequestBuilder.addShouldSync(SyncedListType listType)
Add should sync. listType the list type
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic.
static Condition ver14.SharedClasses.DBActions.RequestBuilder.p1_OR_p2(Object un, Table playersOf)
P 1 or p 2 condition. un the un playersOf the players of the condition
static Condition ver14.SharedClasses.DBActions.RequestBuilder.p1_OR_p2(Object un)
P 1 or p 2 condition. un the un the condition
static Selection ver14.SharedClasses.DBActions.RequestBuilder.gamesStats(Object username, Condition condition)
Win loss tie ratio formula username the username condition the condition selection
static Condition ver14.SharedClasses.DBActions.RequestBuilder.betweenHours(int start, int end)
Between hours condition. start the start end the end the condition
static Selection ver14.SharedClasses.DBActions.RequestBuilder.gamesStats(Object username)
Games stats selection. username the username the selection