ver14::SharedClasses::Game::Evaluation::Evaluation
final int ver14.SharedClasses.Game.Evaluation.Evaluation.TIE_EVAL
The constant TIE_EVAL.
final int ver14.SharedClasses.Game.Evaluation.Evaluation.WIN_EVAL
The constant WIN_EVAL.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.assertNotGameOver.
final int ver14.SharedClasses.Game.Evaluation.Evaluation.LOSS_EVAL
The constant LOSS_EVAL.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.assertNotGameOver.
final Map<GameStatus.GameStatusType, Integer> ver14.SharedClasses.Game.Evaluation.Evaluation.gameStatusEvalMap
The constant gameStatusEvalMap.
final boolean ver14.SharedClasses.Game.Evaluation.Evaluation.MAKE_DETAILED
The constant MAKE_DETAILED.
final ArrayList<EvaluationDetail> ver14.SharedClasses.Game.Evaluation.Evaluation.detailedEval
The Detailed eval.
final GameStatus ver14.SharedClasses.Game.Evaluation.Evaluation.gameStatus
The Game status.
int ver14.SharedClasses.Game.Evaluation.Evaluation.eval
The Eval.
PlayerColor ver14.SharedClasses.Game.Evaluation.Evaluation.evaluationFor
The Evaluation for.
Integer ver14.SharedClasses.Game.Evaluation.Evaluation.evaluationDepth
The Evaluation depth.
ver14.SharedClasses.Game.Evaluation.Evaluation.[static initializer]
ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation(GameStatus gameStatus, PlayerColor evaluationFor)
Instantiates a new Evaluation. gameStatus the game status evaluationFor the evaluation for
References ver14.SharedClasses.Game.Evaluation.GameStatus.getGameStatusType.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.book, ver14.SharedClasses.Game.Evaluation.Evaluation.equals.
ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation(int eval, GameStatus gameStatus, PlayerColor evaluationFor)
Instantiates a new Evaluation. eval the eval gameStatus the game status evaluationFor the evaluation for
ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation(PlayerColor evaluationFor)
Instantiates a new Evaluation. evaluationFor the evaluation for
References ver14.SharedClasses.Game.Evaluation.GameStatus.gameGoesOn.
ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation(Evaluation other)
Instantiates a new Evaluation. other the other
void ver14.SharedClasses.Game.Evaluation.Evaluation.addDetail(EvaluationParameters parm, int value)
Add detail. parm the parm value the value
References ver14.SharedClasses.Game.Evaluation.Evaluation.EvaluationDetail, ver14.SharedClasses.Game.Evaluation.EvaluationParameters.weight.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.book.
void ver14.SharedClasses.Game.Evaluation.Evaluation.assertNotGameOver()
Assert not game over.
References ver14.SharedClasses.Game.Evaluation.Evaluation.LOSS_EVAL, ver14.SharedClasses.Game.Evaluation.Evaluation.WIN_EVAL.
Integer ver14.SharedClasses.Game.Evaluation.Evaluation.getEvaluationDepth()
Gets evaluation depth. the evaluation depth
Referenced by ver14.SharedClasses.Game.Moves.MinimaxMove.MinimaxMove.
void ver14.SharedClasses.Game.Evaluation.Evaluation.setEvaluationDepth(Integer evaluationDepth)
Sets evaluation depth. evaluationDepth the evaluation depth
References ver14.SharedClasses.Game.Evaluation.GameStatus.setDepth.
boolean ver14.SharedClasses.Game.Evaluation.Evaluation.isGameOver()
Is game over boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.GameStatus.isGameOver.
boolean ver14.SharedClasses.Game.Evaluation.Evaluation.isCheck()
Is check boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.GameStatus.isCheck.
Referenced by ver14.SharedClasses.Game.Moves.Move.isCheck.
boolean ver14.SharedClasses.Game.Evaluation.Evaluation.isGreaterThan(Evaluation other)
Is greater than boolean. other the other the boolean
Referenced by ver14.SharedClasses.Game.Moves.MinimaxMove.isDeeperAndBetterThan.
int ver14.SharedClasses.Game.Evaluation.Evaluation.getEval()
Gets eval. the eval
Referenced by ver14.SharedClasses.Game.Moves.MinimaxMove.compareTo, ver14.SharedClasses.Game.Moves.Move.compareTo.
void ver14.SharedClasses.Game.Evaluation.Evaluation.setEval(int eval)
Sets eval. eval the eval
GameStatus ver14.SharedClasses.Game.Evaluation.Evaluation.getGameStatus()
Gets game status. the game status
boolean ver14.SharedClasses.Game.Evaluation.Evaluation.equals(Object o)
Equals boolean. o the o the boolean
References ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation.
String ver14.SharedClasses.Game.Evaluation.Evaluation.toString()
To string string. the string
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.EvaluationDetail.
PlayerColor ver14.SharedClasses.Game.Evaluation.Evaluation.getEvaluationFor()
Gets evaluation for. the evaluation for
Evaluation ver14.SharedClasses.Game.Evaluation.Evaluation.setPerspective(PlayerColor playerColor)
Sets perspective. playerColor the player color the perspective
References ver14.SharedClasses.Game.Evaluation.Evaluation.flipEval.
void ver14.SharedClasses.Game.Evaluation.Evaluation.flipEval()
Flip eval.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.setPerspective.
void ver14.SharedClasses.Game.Evaluation.Evaluation.print()
Print.
float ver14.SharedClasses.Game.Evaluation.Evaluation.convertFromCentipawns()
Convert from centipawns float. the float
record ver14.SharedClasses.Game.Evaluation.Evaluation.EvaluationDetail(EvaluationParameters parm, double eval) implements Serializable
Evaluation detail. Bezalel Avrahami (bezalel3250@gmail.com)
References ver14.SharedClasses.Game.Evaluation.Evaluation.toString.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.addDetail.
static Evaluation ver14.SharedClasses.Game.Evaluation.Evaluation.book()
Book evaluation. the evaluation
References ver14.SharedClasses.Game.Evaluation.Evaluation.addDetail, ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation, ver14.SharedClasses.Game.Evaluation.EvaluationParameters.STOCKFISH_SAYS, ver14.SharedClasses.Game.PlayerColor.WHITE.
String ver14.SharedClasses.Game.Evaluation.Evaluation.getDetailedEvalStr()
Gets detailed eval str. the detailed eval str