ver14::SharedClasses::UI::dialogs::ConfirmDialogs
static boolean ver14.SharedClasses.UI.dialogs.ConfirmDialogs.confirm(Component parent, String title, String message, ImageIcon icon)
Confirm boolean. parent the parent title the title message the message icon the icon the boolean
Referenced by ver14.SharedClasses.UI.dialogs.ConfirmDialogs.main, ver14.SharedClasses.UI.MyJFrame.BooleanClosing.show, ver14.SharedClasses.UI.MyJFrame.StringClosing.show.
static void ver14.SharedClasses.UI.dialogs.ConfirmDialogs.main(String[] args)
The entry point of application. args the input arguments
References ver14.SharedClasses.UI.dialogs.ConfirmDialogs.confirm.
static String ver14.SharedClasses.UI.dialogs.ConfirmDialogs.confirm(Component parent, String title, String header, String message, ImageIcon icon, String initialValue)
Confirm string. parent the parent header the header message the message title the title icon the icon initialValue the initial value the string