ver14::SharedClasses::DBActions::Table::SwitchCase
final Condition ver14.SharedClasses.DBActions.Table.SwitchCase.condition
The Condition.
final Col ver14.SharedClasses.DBActions.Table.SwitchCase.ifTrue
The If true.
ver14.SharedClasses.DBActions.Table.SwitchCase.SwitchCase(Condition condition, Col ifTrue)
Instantiates a new Switch case. condition the condition ifTrue the if true
Referenced by ver14.SharedClasses.DBActions.Table.SwitchCase.defaultCase, ver14.SharedClasses.DBActions.Table.SwitchCase.equals.
Condition ver14.SharedClasses.DBActions.Table.SwitchCase.condition()
Condition condition. the condition
Col ver14.SharedClasses.DBActions.Table.SwitchCase.ifTrue()
If true col. the col
String ver14.SharedClasses.DBActions.Table.SwitchCase.toString()
To string string. the string
static SwitchCase ver14.SharedClasses.DBActions.Table.SwitchCase.equals(Col col, String value, Col ifTrue)
Equals switch case. col the col value the value ifTrue the if true the switch case
References ver14.SharedClasses.DBActions.Condition.equals, ver14.SharedClasses.DBActions.Table.SwitchCase.SwitchCase.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.
static SwitchCase ver14.SharedClasses.DBActions.Table.SwitchCase.defaultCase(Col ifTrue)
Default case switch case. ifTrue the if true the switch case
References ver14.SharedClasses.DBActions.Table.SwitchCase.SwitchCase.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.