ver14::SharedClasses::DBActions::Statements::SQLStatement
final DBRequest.Type ver14.SharedClasses.DBActions.Statements.SQLStatement.type
The request Type.
Referenced by ver14.SharedClasses.DBActions.Statements.CustomStatement.CustomStatement, ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest, ver14.SharedClasses.DBActions.Statements.SQLStatement.SQLStatement, ver14.SharedClasses.DBActions.Statements.SQLStatement.toString.
String ver14.SharedClasses.DBActions.Statements.SQLStatement.statement
The Statement.
ver14.SharedClasses.DBActions.Statements.SQLStatement.SQLStatement(DBRequest.Type type)
Instantiates a new Sql statement. type the type
References ver14.SharedClasses.DBActions.Statements.SQLStatement.type.
void ver14.SharedClasses.DBActions.Statements.SQLStatement.replace(String replacing, String replaceWith)
Replace. replacing the replacing replaceWith the replace with
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build.
String ver14.SharedClasses.DBActions.Statements.SQLStatement.getStatement()
Gets statement. the statement
Referenced by ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest, ver14.SharedClasses.DBActions.Statements.Selection.nestMe.
String ver14.SharedClasses.DBActions.Statements.SQLStatement.toString()
To string string. the string
References ver14.SharedClasses.DBActions.Statements.SQLStatement.type.
String ver14.SharedClasses.DBActions.Statements.SQLStatement.createIfNotCreated()
Create if not created string. the string
abstract String ver14.SharedClasses.DBActions.Statements.SQLStatement.createStatement()
Create statement string. the string