ver14::SharedClasses::DBActions::Condition
final Object [] ver14.SharedClasses.DBActions.Condition.parms
The condition parameters.
String ver14.SharedClasses.DBActions.Condition.str
The Str.
ver14.SharedClasses.DBActions.Condition.Condition(String str, Object... parms)
Instantiates a new Condition. str the str parms the parms
References ver14.SharedClasses.Utils.StrUtils.countMatches.
Referenced by ver14.SharedClasses.DBActions.Condition.between, ver14.SharedClasses.DBActions.Condition.equals, ver14.SharedClasses.DBActions.Condition.noNulls, ver14.SharedClasses.DBActions.Condition.notEquals.
Condition ver14.SharedClasses.DBActions.Condition.noNulls()
No nulls condition. the condition
References ver14.SharedClasses.DBActions.Condition.add, ver14.SharedClasses.DBActions.Condition.Relation.AND, ver14.SharedClasses.DBActions.Condition.Condition, ver14.SharedClasses.Utils.StrUtils.splitArr.
Condition ver14.SharedClasses.DBActions.Condition.add(Condition condition, Relation relation)
Add condition. condition the condition relation the relation the condition
References ver14.SharedClasses.DBActions.Condition.add.
Referenced by ver14.SharedClasses.DBActions.Condition.add, ver14.SharedClasses.DBActions.Condition.and, ver14.SharedClasses.DBActions.Condition.noNulls.
Condition ver14.SharedClasses.DBActions.Condition.add(Condition condition, Relation relation, boolean wrap)
Add condition. condition the condition relation the relation wrap the wrap THIS condition
References ver14.SharedClasses.DBActions.Condition.wrap.
void ver14.SharedClasses.DBActions.Condition.wrap()
Wrap.
Referenced by ver14.SharedClasses.DBActions.Condition.add, ver14.SharedClasses.DBActions.Condition.between.
Condition ver14.SharedClasses.DBActions.Condition.and(Condition condition)
wraps condition the condition condition
References ver14.SharedClasses.DBActions.Condition.add, ver14.SharedClasses.DBActions.Condition.Relation.AND.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.RequestBuilder.top.
String ver14.SharedClasses.DBActions.Condition.getStr()
Gets str. the str
void ver14.SharedClasses.DBActions.Condition.setStr(String str)
Sets str. str the str
String ver14.SharedClasses.DBActions.Condition.toString()
To string string. the string
static String ver14.SharedClasses.DBActions.Condition.createValueStr(Object value)
Create value str string. value the value the string
static Condition ver14.SharedClasses.DBActions.Condition.equals(Object col, Object value)
Equals condition. col the col value the value the condition
References ver14.SharedClasses.DBActions.Condition.Condition.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changePassword, ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic, ver14.SharedClasses.DBActions.Table.SwitchCase.equals, ver14.SharedClasses.DBActions.RequestBuilder.top.
static Condition ver14.SharedClasses.DBActions.Condition.math(Object col, @MagicConstant(stringValues={">", ">=", "<", "<="}) String operation, Object value)
Math condition. col the col operation the operation value the value the condition
static Condition ver14.SharedClasses.DBActions.Condition.between(Object col, Object start, Object end)
Between condition. col the col start the start end the end the condition
References ver14.SharedClasses.DBActions.Condition.Condition, ver14.SharedClasses.DBActions.Condition.wrap.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.
static Condition ver14.SharedClasses.DBActions.Condition.notEquals(Object col, Object value)
Not equals condition. col the col value the value the condition
References ver14.SharedClasses.DBActions.Condition.Condition.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.