ver14::SharedClasses::Game::Moves::BasicMove
Location ver14.SharedClasses.Game.Moves.BasicMove.movingFrom
The Moving from.
Location ver14.SharedClasses.Game.Moves.BasicMove.movingTo
The Moving to.
ver14.SharedClasses.Game.Moves.BasicMove.BasicMove(BasicMove other)
Copy constructor. other the other
Referenced by ver14.SharedClasses.Game.Moves.Move.castling, ver14.SharedClasses.Game.Moves.BasicMove.cp, ver14.SharedClasses.Game.Moves.BasicMove.createBatch, ver14.SharedClasses.Game.Moves.BasicMove.getFlipped, ver14.SharedClasses.Game.Moves.Move.Move.
ver14.SharedClasses.Game.Moves.BasicMove.BasicMove(Location movingFrom, Location movingTo)
Instantiates a new Basic move. movingFrom the moving from movingTo the moving to
ver14.SharedClasses.Game.Moves.BasicMove.BasicMove(String move)
Instantiates a new Basic move. move the move
References ver14.SharedClasses.Game.Location.getLoc.
void ver14.SharedClasses.Game.Moves.BasicMove.flip()
Flips the source and destination.
Referenced by ver14.SharedClasses.Game.Moves.Move.flipMove, ver14.SharedClasses.Game.Moves.BasicMove.getFlipped.
Location ver14.SharedClasses.Game.Moves.BasicMove.getMovingFrom()
Gets moving from. aka source the moving from
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate.
void ver14.SharedClasses.Game.Moves.BasicMove.setMovingFrom(Location movingFrom)
Sets moving from. movingFrom the moving from
Location ver14.SharedClasses.Game.Moves.BasicMove.getMovingTo()
Gets moving to. the moving to
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate.
void ver14.SharedClasses.Game.Moves.BasicMove.setMovingTo(Location movingTo)
Sets moving to. movingTo the moving to
int ver14.SharedClasses.Game.Moves.BasicMove.hashCode()
Hash code int. the int
boolean ver14.SharedClasses.Game.Moves.BasicMove.equals(Object o)
Equals boolean. o the o the boolean
Referenced by ver14.SharedClasses.Game.Moves.Move.equals.
String ver14.SharedClasses.Game.Moves.BasicMove.toString()
To string string. the string
References ver14.SharedClasses.Game.Moves.BasicMove.getBasicMoveAnnotation.
String ver14.SharedClasses.Game.Moves.BasicMove.getBasicMoveAnnotation()
Gets basic move annotation. the basic move annotation
References ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate.
Referenced by ver14.SharedClasses.Game.Moves.BasicMove.toString.
BasicMove ver14.SharedClasses.Game.Moves.BasicMove.cp()
copies this move. the new copy
References ver14.SharedClasses.Game.Moves.BasicMove.BasicMove.
static BasicMove[] ver14.SharedClasses.Game.Moves.BasicMove.createBatch(Location... locs)
Create batch basic move [ ]. locs the locs the basic move [ ]
References ver14.SharedClasses.Game.Moves.BasicMove.BasicMove.
static BasicMove ver14.SharedClasses.Game.Moves.BasicMove.getFlipped(BasicMove basicMove)
Gets a copy of the provided move with the source and destination flipped basicMove the original move the flipped move
References ver14.SharedClasses.Game.Moves.BasicMove.BasicMove, ver14.SharedClasses.Game.Moves.BasicMove.flip.