ver14::SharedClasses::DBActions::Arg::Arg
final IDsGenerator ver14.SharedClasses.DBActions.Arg.Arg.ids
final String ver14.SharedClasses.DBActions.Arg.Arg.repInStr
The Rep in str.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build, ver14.SharedClasses.DBActions.RequestBuilder.changePassword, ver14.SharedClasses.DBActions.RequestBuilder.deleteAllUnFinishedGames, ver14.SharedClasses.DBActions.Arg.Arg.equals, ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.RequestBuilder.statsByTimeOfDay, ver14.SharedClasses.DBActions.RequestBuilder.top, ver14.SharedClasses.DBActions.Arg.Arg.toString.
final boolean ver14.SharedClasses.DBActions.Arg.Arg.escape
The Escape.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.Arg, ver14.SharedClasses.DBActions.Arg.Arg.createVal.
final ArgType ver14.SharedClasses.DBActions.Arg.Arg.argType
The Arg type.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.Arg.
final Config<?> ver14.SharedClasses.DBActions.Arg.Arg.config
The Config.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.Arg, ver14.SharedClasses.DBActions.Arg.Arg.createVal.
boolean ver14.SharedClasses.DBActions.Arg.Arg.isUserInput
ver14.SharedClasses.DBActions.Arg.Arg.[static initializer]
ver14.SharedClasses.DBActions.Arg.Arg.Arg(ArgType argType)
Instantiates a new Arg. argType the arg type
References ver14.SharedClasses.DBActions.Arg.Arg.argType.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.equals.
ver14.SharedClasses.DBActions.Arg.Arg.Arg(ArgType argType, Config<?> config)
Instantiates a new Arg. argType the arg type config the config
References ver14.SharedClasses.DBActions.Arg.Arg.argType, ver14.SharedClasses.DBActions.Arg.Arg.config.
ver14.SharedClasses.DBActions.Arg.Arg.Arg(ArgType argType, boolean escape, Config<?> config)
Instantiates a new Arg. argType the arg type escape the escape config the config
References ver14.SharedClasses.DBActions.Arg.Arg.argType, ver14.SharedClasses.DBActions.Arg.Arg.config, ver14.SharedClasses.DBActions.Arg.Arg.escape, ver14.SharedClasses.Misc.IDsGenerator.generate, ver14.SharedClasses.DBActions.Arg.ArgType.isUserInput.
boolean ver14.SharedClasses.DBActions.Arg.Arg.isUserInput()
Is user input boolean. the boolean
void ver14.SharedClasses.DBActions.Arg.Arg.setUserInput(boolean userInput)
Sets user input. userInput the user input
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changePassword.
boolean ver14.SharedClasses.DBActions.Arg.Arg.equals(Object o)
Equals boolean. o the o the boolean
References ver14.SharedClasses.DBActions.Arg.Arg.Arg, ver14.SharedClasses.DBActions.Arg.Arg.equals, ver14.SharedClasses.DBActions.Arg.Arg.repInStr.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.equals.
String ver14.SharedClasses.DBActions.Arg.Arg.toString()
To string string. the string
References ver14.SharedClasses.DBActions.Arg.Arg.repInStr.
String ver14.SharedClasses.DBActions.Arg.Arg.createVal(Object val)
Create val string. val the val the string
References ver14.SharedClasses.DBActions.Arg.Config< V >.canUseDefault, ver14.SharedClasses.DBActions.Arg.Arg.config, ver14.SharedClasses.DBActions.Arg.Arg.escape, ver14.SharedClasses.Utils.StrUtils.formatDateSQL, ver14.SharedClasses.DBActions.Arg.Config< V >.getDefault.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build.
static String ver14.SharedClasses.DBActions.Arg.Arg.wrap(String wrapping)