ver14::SharedClasses::Networking::MessagesHandler
final AppSocket ver14.SharedClasses.Networking.MessagesHandler.socket
The Socket.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.MessagesHandler, ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest, ver14.SharedClasses.Networking.MessagesHandler.onAnyDisconnection, ver14.SharedClasses.Networking.MessagesHandler.onInterrupt, ver14.SharedClasses.Networking.MessagesHandler.onIsAlive.
final Vector<CompletableFuture<Message> > ver14.SharedClasses.Networking.MessagesHandler.waiting
The Waiting.
final Map<MessageType, MessageCallback> ver14.SharedClasses.Networking.MessagesHandler.defaultCallbacks
The Default callbacks.
final Stack<Message> ver14.SharedClasses.Networking.MessagesHandler.receivedMessages
The Received messages.
final Map<String, MessageCallback> ver14.SharedClasses.Networking.MessagesHandler.customCallbacks
The Custom callbacks.
final Semaphore ver14.SharedClasses.Networking.MessagesHandler.chronologicalSemaphore
The Chronological semaphore.
boolean ver14.SharedClasses.Networking.MessagesHandler.isExpectingDisconnect
The Is expecting disconnect.
boolean ver14.SharedClasses.Networking.MessagesHandler.didDisconnect
The Did disconnect.
ver14.SharedClasses.Networking.MessagesHandler.[instance initializer]
ver14.SharedClasses.Networking.MessagesHandler.MessagesHandler(AppSocket socket)
Instantiates a new Messages handler. socket the socket
References ver14.SharedClasses.Networking.MessagesHandler.socket.
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onCancelQuestion()
On cancel question message callback. the message callback
void ver14.SharedClasses.Networking.MessagesHandler.interruptBlocking(MyError err)
Interrupt blocking. err the err
References ver14.SharedClasses.Networking.Messages.Message.throwError.
Referenced by ver14.SharedClasses.Networking.AppSocket.interruptListener.
Message ver14.SharedClasses.Networking.MessagesHandler.blockTilRes(Message request)
Block til res message. request the request the message
References ver14.SharedClasses.Networking.Messages.Message.getMessageType, ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest, ver14.SharedClasses.Callbacks.MessageCallback.onMsg.
Referenced by ver14.SharedClasses.Networking.AppSocket.requestMessage.
void ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest(Message request, MessageCallback onRes)
No block request. request the request onRes the on res
References ver14.SharedClasses.Networking.Messages.Message.messageID, ver14.SharedClasses.Networking.MessagesHandler.socket, ver14.SharedClasses.Networking.AppSocket.writeMessage.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.blockTilRes, ver14.SharedClasses.Networking.AppSocket.requestMessage.
void ver14.SharedClasses.Networking.MessagesHandler.receivedMessage(Message message)
Received message. message the message
References ver14.SharedClasses.Threads.ThreadsManager.createThread, ver14.SharedClasses.Networking.Messages.Message.getMessageType, ver14.SharedClasses.Networking.MessagesHandler.prepareForDisconnect.
Referenced by ver14.SharedClasses.Networking.AppSocket.handledRun.
void ver14.SharedClasses.Networking.MessagesHandler.prepareForDisconnect()
Prepare for disconnect.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onBye, ver14.SharedClasses.Networking.MessagesHandler.receivedMessage, ver14.SharedClasses.Networking.AppSocket.writeMessage.
void ver14.SharedClasses.Networking.MessagesHandler.onAnyMsg(Message message)
On any msg. message the message
final void ver14.SharedClasses.Networking.MessagesHandler.onDisconnected()
On disconnected.
References ver14.SharedClasses.Networking.MessagesHandler.onAnyDisconnection, ver14.SharedClasses.Networking.MessagesHandler.onPlannedDisconnect, ver14.SharedClasses.Networking.MessagesHandler.onUnplannedDisconnect.
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onLogin()
On login message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onResign()
On resign message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onAddTime()
On add time message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onOfferDraw()
On offer draw message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onWelcomeMessage()
On welcome message message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onGetGameSettings()
On get game settings message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onWaitForMatch()
On wait for match message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onInitGame()
On init game message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onWaitTurn()
On wait turn message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onGetMove()
On get move message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onUpdateByMove()
On update by move message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onGameOver()
On game over message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onError()
On error message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onQuestion()
On question message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onBye()
On bye message callback. the message callback
References ver14.SharedClasses.Networking.MessagesHandler.prepareForDisconnect.
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onUsernameAvailability()
On username availability message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onDBRequest()
On db request message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onDBResponse()
On db response message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onUpdateSyncedList()
On update synced list message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onInterrupt()
On interrupt message callback. the message callback
References ver14.SharedClasses.Networking.Messages.Message.interrupt, ver14.SharedClasses.Networking.Messages.Message.isResponse, ver14.SharedClasses.Networking.AppSocket.respond, ver14.SharedClasses.Networking.MessagesHandler.socket.
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onIsAlive()
On is alive message callback. the message callback
References ver14.SharedClasses.Networking.Messages.Message.interrupt, ver14.SharedClasses.Networking.AppSocket.respond, ver14.SharedClasses.Networking.MessagesHandler.socket.
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onAlive()
On alive message callback. the message callback
MessageCallback ver14.SharedClasses.Networking.MessagesHandler.onThrowError()
On throw error message callback. the message callback
void ver14.SharedClasses.Networking.MessagesHandler.processMessage(Message message)
Process message. message the message
void ver14.SharedClasses.Networking.MessagesHandler.onAnyDisconnection()
On any disconnection.
References ver14.SharedClasses.Networking.AppSocket.close, ver14.SharedClasses.Networking.MessagesHandler.socket.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onDisconnected.
void ver14.SharedClasses.Networking.MessagesHandler.onPlannedDisconnect()
On planned disconnect.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onDisconnected.
void ver14.SharedClasses.Networking.MessagesHandler.onUnplannedDisconnect()
On unplanned disconnect.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onDisconnected.
MyError.DisconnectedError ver14.SharedClasses.Networking.MessagesHandler.createDisconnectedError()
Create disconnected error my error . disconnected error. the my error . disconnected error
Referenced by ver14.SharedClasses.Networking.AppSocket.close.