ver14::SharedClasses::Misc::Question
final Question ver14.SharedClasses.Misc.Question.Threefold
The constant Threefold.
final Question ver14.SharedClasses.Misc.Question.Rematch
The constant Rematch.
final String ver14.SharedClasses.Misc.Question.questionStr
The Question str.
Referenced by ver14.SharedClasses.Misc.Question.equals, ver14.SharedClasses.Misc.Question.getQuestionStr, ver14.SharedClasses.Misc.Question.Question, ver14.SharedClasses.Misc.Question.toString.
final QuestionType ver14.SharedClasses.Misc.Question.questionType
The Question type.
Referenced by ver14.SharedClasses.Misc.Question.equals, ver14.SharedClasses.Misc.Question.Question, ver14.SharedClasses.Misc.Question.toString.
final Answer [] ver14.SharedClasses.Misc.Question.possibleAnswers
The Possible answers.
Answer ver14.SharedClasses.Misc.Question.defaultAnswer
The Default answer.
ver14.SharedClasses.Misc.Question.Question(String questionStr, Answer... possibleAnswers)
Instantiates a new Question. questionStr the question str possibleAnswers the possible answers
References ver14.SharedClasses.Misc.Question.QuestionType.NO_TYPE, ver14.SharedClasses.Misc.Question.questionStr.
Referenced by ver14.SharedClasses.Misc.Question.drawOffer.
ver14.SharedClasses.Misc.Question.Question(String questionStr, QuestionType questionType, Answer... possibleAnswers)
Instantiates a new Question. questionStr the question str questionType the question type possibleAnswers the possible answers
References ver14.SharedClasses.Utils.ArrUtils.exists, ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Misc.Question.questionStr, ver14.SharedClasses.Misc.Question.questionType.
Answer ver14.SharedClasses.Misc.Question.getDefaultAnswer()
Gets default answer. the default answer
void ver14.SharedClasses.Misc.Question.setDefaultAnswer(Answer defaultAnswer)
Sets default answer. defaultAnswer the default answer
String ver14.SharedClasses.Misc.Question.getQuestionStr()
Gets question str. the question str
References ver14.SharedClasses.Misc.Question.questionStr.
Answer[] ver14.SharedClasses.Misc.Question.getPossibleAnswers()
Get possible answers answer [ ]. the answer [ ]
boolean ver14.SharedClasses.Misc.Question.equals(Object o)
Equals boolean. o the o the boolean
References ver14.SharedClasses.Misc.Question.questionStr, ver14.SharedClasses.Misc.Question.questionType.
String ver14.SharedClasses.Misc.Question.toString()
To string string. the string
References ver14.SharedClasses.Misc.Question.questionStr, ver14.SharedClasses.Misc.Question.questionType.
record ver14.SharedClasses.Misc.Question.Answer(String answerStr) implements Serializable
Answer. Bezalel Avrahami (bezalel3250@gmail.com)
References ver14.SharedClasses.Misc.Question.Answer.
Referenced by ver14.SharedClasses.Misc.Question.Answer, ver14.SharedClasses.Misc.Question.drawOffer.
static Question ver14.SharedClasses.Misc.Question.drawOffer(String offeringPlayer)
Draw offer question. offeringPlayer the offering player the question
References ver14.SharedClasses.Misc.Question.Answer, ver14.SharedClasses.Misc.Question.QuestionType.DRAW_OFFER, ver14.SharedClasses.Misc.Question.Question.