ver14::SharedClasses::Game::GameSetup::BoardSetup::Board
final String ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingFen
The constant startingFen.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingPos.
final Board ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.example
The constant example.
final Map<Location, Square> ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.boardMap
ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board(Board other)
Instantiates a new Board. other the other
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setPiece.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board()
Instantiates a new Board.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingPos.
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setPiece(Location loc, Piece piece)
Sets piece. loc the loc piece the piece
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setPiece.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup.
Square ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare(Location loc)
Gets square. loc the loc the square
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getRow, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.isSquareEmpty, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setPiece, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setSquareEmpty, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.toString.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board(String fen)
Instantiates a new Board. fen the fen
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup.
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup(String fen)
Fen setup. fen the fen
References ver14.SharedClasses.Game.Location.getLoc, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceFromFen, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setPiece, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingFen.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingPos.
Square[] ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getRow(int row, boolean flipLocs)
Get row square [ ]. row the row flipLocs the flip locs the square [ ]
References ver14.SharedClasses.Game.Location.getLoc, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare.
Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece(Location loc, boolean notNull)
Gets piece. loc the loc notNull the not null the piece
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece.
Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece(Location loc)
Gets piece. loc the loc the piece
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getPiece, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare.
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.print()
Print.
Iterator< Square > ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.iterator()
Iterator iterator. the iterator
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setSquareEmpty(Location loc)
Sets square empty. loc the loc
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setEmpty.
boolean ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.isSquareEmpty(Location loc)
Is square empty boolean. loc the loc the boolean
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.isEmpty.
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.toString()
To string string. the string
References ver14.SharedClasses.Game.Location.getLoc, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getSquare, ver14.SharedClasses.Game.Location.toString.
static Board ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingPos()
Starting pos board. the board
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.Board, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.startingFen.