ver14::SharedClasses::DBActions::DBResponse::TableDBResponse
final int [] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.calcedLengths
The Calced lengths.
String [] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns
The Columns.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumnIndex, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumns, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.toString.
String [][] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows
The Rows.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getCell, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getFirstRow, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getRows, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.isAnyData, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.numOfRows, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.toString.
ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse(String[] columns, String[][] rows, DBRequest request)
Instantiates a new Table db response. columns the columns rows the rows request the request
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns, ver14.SharedClasses.DBActions.DBResponse.DBResponse.request, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows, ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status.SUCCESS.
ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse(String[] columns, String[][] rows, Status status, DBRequest request)
Instantiates a new Table db response. columns the columns rows the rows status the status request the request
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns, ver14.SharedClasses.DBActions.DBResponse.DBResponse.request, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows, ver14.SharedClasses.DBActions.DBResponse.DBResponse.status.
int ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.numOfRows()
Num of rows int. the int
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
String[] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getFirstRow()
Get first row string [ ]. the string [ ]
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
String ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getCell(int row, String col)
Gets cell. row the row col the col the cell
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumnIndex, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
String ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getCell(int row, Col col)
Gets cell. row the row col the col the cell
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumnIndex, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
boolean ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.isAnyData()
Is any data boolean. the boolean
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
TableDBResponse ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean()
Clean table db response. the table db response
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes, ver14.SharedClasses.DBActions.DBResponse.DBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns, ver14.SharedClasses.DBActions.DBResponse.DBResponse.request, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows, ver14.SharedClasses.DBActions.DBResponse.DBResponse.setAddedRes, ver14.SharedClasses.DBActions.DBResponse.DBResponse.status, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean.
String ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.toString()
To string string. the string
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.addedRes, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows, ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rowToString.
String ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rowToString(String[] row)
Row to string string. row the row the string
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.toString.
String[] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumns()
Get columns string [ ]. the string [ ]
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns.
String[][] ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getRows()
Get rows string [ ] [ ]. the string [ ] [ ]
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.rows.
int ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.calcMaxLength(int colIndex)
Calc max length int. colIndex the col index the int
int ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumnIndex(Col col)
Gets column index. col the col the column index
int ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.maxLength(int colIndex)
Max length int. colIndex the col index the int
ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.TableDBResponse()
Instantiates a new Table db response.
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.Status.SUCCESS.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.clean.
int ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getColumnIndex(String column)
Gets column index. column the column the column index
References ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.columns.
Referenced by ver14.SharedClasses.DBActions.DBResponse.TableDBResponse.getCell.