ver14::SharedClasses::Game::GameSetup::BoardSetup::Square
final Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.EMPTY_PIECE
The constant EMPTY_PIECE.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.isEmpty, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setEmpty.
final String ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.EMPTY_PIECE_STR
The constant EMPTY_PIECE_STR.
final Location ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.loc
The constant loc.
Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.piece
The Piece.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.Square(Location loc)
Instantiates a new Square. loc the loc
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setEmpty.
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setEmpty()
Sets empty.
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.EMPTY_PIECE, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setPiece.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setSquareEmpty, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.Square.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.Square(Piece piece, Location loc)
Instantiates a new Square. piece the piece loc the loc
Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getPiece()
Gets piece. the piece
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getPiece.
void ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setPiece(Piece piece)
Sets piece. piece the piece
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.setEmpty, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.setPiece.
Location ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getLoc()
Gets loc. the loc
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.toString()
To string string. the string
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getFen.
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getFen()
Gets fen. the fen
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getFen, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.isEmpty.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.toString.
boolean ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.isEmpty()
Is empty boolean. the boolean
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.EMPTY_PIECE.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getFen, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getPieceIcon, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.isSquareEmpty.
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getPieceIcon()
Gets piece icon. the piece icon
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceIcon, ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.isEmpty.