ver14::SharedClasses::DBActions::Table::Col
final Col ver14.SharedClasses.DBActions.Table.Col.GameID
The constant GameID.
final Col ver14.SharedClasses.DBActions.Table.Col.SavedGame
The constant SavedGame.
final Col ver14.SharedClasses.DBActions.Table.Col.Password
The constant Password.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changePassword.
final Col ver14.SharedClasses.DBActions.Table.Col.Player1
The constant Player1.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.
final Col ver14.SharedClasses.DBActions.Table.Col.Player2
The constant Player2.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.
final Col ver14.SharedClasses.DBActions.Table.Col.Username
The constant Username.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changePassword, ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic, ver14.SharedClasses.DBActions.RequestBuilder.top.
final Col ver14.SharedClasses.DBActions.Table.Col.Winner
The constant Winner.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
final Col ver14.SharedClasses.DBActions.Table.Col.PlayerToMove
The constant PlayerToMove.
final Col ver14.SharedClasses.DBActions.Table.Col.CreatedDateTime
The constant CreatedDateTime.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.Table.Table.Table.
final Col ver14.SharedClasses.DBActions.Table.Col.ProfilePic
The constant ProfilePic.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.changeProfilePic.
final String ver14.SharedClasses.DBActions.Table.Col.alias
The column's Alias.
String ver14.SharedClasses.DBActions.Table.Col.colName
The Col name.
boolean ver14.SharedClasses.DBActions.Table.Col.isWrapped
Is wrapped in parentheses.
ver14.SharedClasses.DBActions.Table.Col.Col(Col col)
Instantiates a new Col. col the col
Referenced by ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.count, ver14.SharedClasses.DBActions.Table.Col.countIf, ver14.SharedClasses.DBActions.Table.Col.date, ver14.SharedClasses.DBActions.Table.Col.of, ver14.SharedClasses.DBActions.Table.Col.replace, ver14.SharedClasses.DBActions.Table.Col.switchCase, ver14.SharedClasses.DBActions.Table.Col.time.
ver14.SharedClasses.DBActions.Table.Col.Col(String colName, String alias)
Instantiates a new Col. colName the col name alias the alias
References ver14.SharedClasses.Utils.StrUtils.format.
ver14.SharedClasses.DBActions.Table.Col.Col(String colName)
Instantiates a new Col. colName the col name
String ver14.SharedClasses.DBActions.Table.Col.label()
Label string. the string
Referenced by ver14.SharedClasses.DBActions.Table.Col.nested, ver14.SharedClasses.DBActions.Table.Math.str, ver14.SharedClasses.DBActions.Table.Col.sum, ver14.SharedClasses.DBActions.RequestBuilder.top.
void ver14.SharedClasses.DBActions.Table.Col.wrap()
Wrap.
Referenced by ver14.SharedClasses.DBActions.Table.Col.switchCase.
Col ver14.SharedClasses.DBActions.Table.Col.time()
Time col. a new col representing time
References ver14.SharedClasses.DBActions.Table.Col.Col, ver14.SharedClasses.DBActions.Table.Col.date, ver14.SharedClasses.DBActions.Table.Col.setWrapped.
Col ver14.SharedClasses.DBActions.Table.Col.date()
Date col. a new col representing datetime
References ver14.SharedClasses.DBActions.Table.Col.Col, ver14.SharedClasses.DBActions.Table.Col.setWrapped.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.Table.Col.time.
void ver14.SharedClasses.DBActions.Table.Col.setWrapped(boolean wrapped)
Sets wrapped. wrapped the wrapped
Referenced by ver14.SharedClasses.DBActions.Table.Col.date, ver14.SharedClasses.DBActions.Table.Col.time.
Col ver14.SharedClasses.DBActions.Table.Col.as()
As own name. practically keeps the name's case. the col
References ver14.SharedClasses.DBActions.Table.Col.as.
Referenced by ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.count, ver14.SharedClasses.DBActions.Table.Col.countIf, ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.Statements.Selection.Selection, ver14.SharedClasses.DBActions.Table.Col.sum, ver14.SharedClasses.DBActions.Table.Col.switchCase, ver14.SharedClasses.DBActions.RequestBuilder.top.
Col ver14.SharedClasses.DBActions.Table.Col.as(String alias)
creates a new column with the given alias as its alias alias the alias the col
References ver14.SharedClasses.DBActions.Table.Col.Col.
void ver14.SharedClasses.DBActions.Table.Col.setColName(String colName)
Sets col name. colName the col name
Referenced by ver14.SharedClasses.DBActions.Table.Math.simpleOperation, ver14.SharedClasses.DBActions.Table.Math.zeroIfNull.
String ver14.SharedClasses.DBActions.Table.Col.colName()
Col name string. the string
Col ver14.SharedClasses.DBActions.Table.Col.of(Table table)
new col like this that belongs to the given table table the table the col
References ver14.SharedClasses.DBActions.Table.Col.of.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games, ver14.SharedClasses.DBActions.Table.Col.of, ver14.SharedClasses.DBActions.RequestBuilder.top.
Col ver14.SharedClasses.DBActions.Table.Col.of(String ofWhom)
new col like this that belongs to the given owner ofWhom the of whom the col
References ver14.SharedClasses.DBActions.Table.Col.Col.
Col ver14.SharedClasses.DBActions.Table.Col.replace(String replacing, String replaceWith)
Replace col. replacing the replacing replaceWith the replace with the col
References ver14.SharedClasses.DBActions.Table.Col.Col.
String ver14.SharedClasses.DBActions.Table.Col.nested()
Nested string. the string
References ver14.SharedClasses.DBActions.Table.Col.label.
Referenced by ver14.SharedClasses.DBActions.Statements.Selection.nestMe.
Col ver14.SharedClasses.DBActions.Table.Col.math(Math operation, Object value)
Math col. operation the operation value the value the col
References ver14.SharedClasses.DBActions.Table.Col.math.
Referenced by ver14.SharedClasses.DBActions.Table.Col.math, ver14.SharedClasses.DBActions.RequestBuilder.top.
Col ver14.SharedClasses.DBActions.Table.Col.math(Math operation, Object value, boolean changeSelf)
Math col. operation the operation value the value changeSelf the change self the col
References ver14.SharedClasses.DBActions.Table.Math.execute.
String ver14.SharedClasses.DBActions.Table.Col.toString()
To string string. the string
Referenced by ver14.SharedClasses.DBActions.Statements.Selection.Selection.
static Col ver14.SharedClasses.DBActions.Table.Col.count(String as)
Count col. counts every row (*) as the alias the col
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.count.
Referenced by ver14.SharedClasses.DBActions.Table.Col.count, ver14.SharedClasses.DBActions.RequestBuilder.top.
static Col ver14.SharedClasses.DBActions.Table.Col.count(String as, Object countWhat)
Count col. as the alias countWhat the count what the col
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.Col.
static Col ver14.SharedClasses.DBActions.Table.Col.countIf(String as, Condition condition)
Count if col. only counts if the given condition is true as the as condition the condition the col
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.Col.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
static CustomCol ver14.SharedClasses.DBActions.Table.Col.sum(String as, Col... colsToSum)
Sum cols. as the alias colsToSum the cols to sum the custom col
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.label, ver14.SharedClasses.Utils.StrUtils.splitArr.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
static Col ver14.SharedClasses.DBActions.Table.Col.switchCase(String as, SwitchCase... cases)
Switch case col. as the as cases the cases the col
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.Table.Col.Col, ver14.SharedClasses.Utils.StrUtils.splitArr, ver14.SharedClasses.DBActions.Table.Col.wrap.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.games.