ver14::SharedClasses::Login::LoginInfo
String ver14.SharedClasses.Login.LoginInfo.username
The Username.
String ver14.SharedClasses.Login.LoginInfo.password
The Password.
LoginType ver14.SharedClasses.Login.LoginInfo.loginType
The Login type.
String ver14.SharedClasses.Login.LoginInfo.profilePic
The Profile pic.
ver14.SharedClasses.Login.LoginInfo.LoginInfo()
Instantiates a new Login info.
References ver14.SharedClasses.Login.LoginType.NOT_SET_YET.
ver14.SharedClasses.Login.LoginInfo.LoginInfo(String username, String password, LoginType loginType)
Instantiates a new Login info. username the username password the password loginType the login type
ver14.SharedClasses.Login.LoginInfo.LoginInfo(LoginType loginType)
Instantiates a new Login info. loginType the login type
String ver14.SharedClasses.Login.LoginInfo.getProfilePic()
Gets profile pic. the profile pic
void ver14.SharedClasses.Login.LoginInfo.setProfilePic(String profilePic)
Sets profile pic. profilePic the profile pic
boolean ver14.SharedClasses.Login.LoginInfo.isGuest()
Is guest boolean. the boolean
References ver14.SharedClasses.Login.LoginType.GUEST.
LoginType ver14.SharedClasses.Login.LoginInfo.getLoginType()
Gets login type. the login type
void ver14.SharedClasses.Login.LoginInfo.setLoginType(LoginType loginType)
Sets login type. loginType the login type
Referenced by ver14.SharedClasses.Login.LoginInfo.initDebugLoginValues.
String ver14.SharedClasses.Login.LoginInfo.getUsername()
Gets username. the username
void ver14.SharedClasses.Login.LoginInfo.setUsername(String username)
Sets username. username the username
Referenced by ver14.SharedClasses.Login.LoginInfo.initDebugLoginValues.
String ver14.SharedClasses.Login.LoginInfo.getPassword()
Gets password. the password
void ver14.SharedClasses.Login.LoginInfo.setPassword(String password)
Sets password. password the password
Referenced by ver14.SharedClasses.Login.LoginInfo.initDebugLoginValues.
String ver14.SharedClasses.Login.LoginInfo.toString()
To string string. the string
boolean ver14.SharedClasses.Login.LoginInfo.asUser()
As user boolean. the boolean
References ver14.SharedClasses.Login.LoginType.asUser.
void ver14.SharedClasses.Login.LoginInfo.initDebugLoginValues()
Init debug login values.
References ver14.SharedClasses.Login.LoginType.LOGIN, ver14.SharedClasses.Login.LoginInfo.setLoginType, ver14.SharedClasses.Login.LoginInfo.setPassword, ver14.SharedClasses.Login.LoginInfo.setUsername.