ver14::SharedClasses::Game::Moves::MoveAnnotation
final String ver14.SharedClasses.Game.Moves.MoveAnnotation.CAPTURE_ANN
The constant CAPTURE_ANN.
static String ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate(Move move, Piece movingPiece)
Annotate move. move the move movingPiece the moving piece the annotation
References ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate.
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate.
static String ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate(Move move, Piece movingPiece, String unique)
Annotate move with a unique string. move the move movingPiece the moving piece unique the unique string the string
References ver14.SharedClasses.Game.Moves.Move.MoveFlag.castlingSide, ver14.SharedClasses.Utils.StrUtils.dontCapFull, ver14.SharedClasses.Game.Location.getColString, ver14.SharedClasses.Game.Moves.Move.getMoveFlag, ver14.SharedClasses.Game.Moves.BasicMove.getMovingFrom, ver14.SharedClasses.Game.Moves.BasicMove.getMovingTo, ver14.SharedClasses.Game.Moves.Move.getPromotingTo, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.getWhitePieceFen, ver14.SharedClasses.Game.Moves.Move.isCapturing, ver14.SharedClasses.Game.Moves.Move.MoveFlag.isCastling, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.PAWN, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.pieceType, ver14.SharedClasses.Game.Moves.Move.MoveFlag.Promotion, ver14.SharedClasses.Game.Location.toString.
static String ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate(BasicMove move)
Basic annotate a move. just the source and destination. move the move the string
References ver14.SharedClasses.Utils.StrUtils.dontCapWord, ver14.SharedClasses.Game.Moves.BasicMove.getMovingFrom, ver14.SharedClasses.Game.Moves.BasicMove.getMovingTo.
Referenced by ver14.SharedClasses.Game.Moves.Move.getAnnotation, ver14.SharedClasses.Game.Moves.BasicMove.getBasicMoveAnnotation.