ver14::SharedClasses::DBActions::Statements::Selection
final Object [] ver14.SharedClasses.DBActions.Statements.Selection.select
The objects to Select.
final Condition ver14.SharedClasses.DBActions.Statements.Selection.condition
The Condition.
String ver14.SharedClasses.DBActions.Statements.Selection.selectPrefix
The Selection prefix.
String ver14.SharedClasses.DBActions.Statements.Selection.selectFrom
The Select from.
String ver14.SharedClasses.DBActions.Statements.Selection.postFix
The selection Post fix.
ver14.SharedClasses.DBActions.Statements.Selection.Selection(Object selectFrom, Object[] select)
Instantiates a new Selection. selectFrom the select from select the select
Referenced by ver14.SharedClasses.DBActions.Statements.Selection.nestMe.
ver14.SharedClasses.DBActions.Statements.Selection.Selection(Object selectFrom, Condition condition, Object[] select)
Instantiates a new Selection. selectFrom the select from condition the condition select the select
References ver14.SharedClasses.DBActions.Table.Col.as, ver14.SharedClasses.DBActions.DBRequest.DBRequest.Type.Query, ver14.SharedClasses.DBActions.Table.Col.toString.
Selection ver14.SharedClasses.DBActions.Statements.Selection.nestMe(Col... outerSelect)
Nest me selection. outerSelect the outer select the selection
References ver14.SharedClasses.DBActions.Statements.SQLStatement.getStatement, ver14.SharedClasses.DBActions.Table.Col.nested, ver14.SharedClasses.DBActions.Statements.Selection.Selection.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
void ver14.SharedClasses.DBActions.Statements.Selection.top(Object top)
Top. top the top
References ver14.SharedClasses.DBActions.Statements.Selection.top.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top, ver14.SharedClasses.DBActions.Statements.Selection.top.
void ver14.SharedClasses.DBActions.Statements.Selection.join( @Join String joinType, Table joinWith, Condition condition, Col... groupBy)
Join. joinType the join type joinWith the join with condition the condition groupBy the group by
References ver14.SharedClasses.Utils.StrUtils.splitArr.
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
void ver14.SharedClasses.DBActions.Statements.Selection.orderBy(Col col, @Order String order)
Order by. col the col order the order
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.top.
String ver14.SharedClasses.DBActions.Statements.Selection.createStatement()
Create statement string. the string
References ver14.SharedClasses.Utils.StrUtils.splitArr.