ver14::SharedClasses::Networking::Messages::Message
final IDsGenerator ver14.SharedClasses.Networking.Messages.Message.messagesIds
final String ver14.SharedClasses.Networking.Messages.Message.messageID
The Message id.
Referenced by ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest, ver14.SharedClasses.Networking.Messages.Message.setRespondingTo.
final MessageType ver14.SharedClasses.Networking.Messages.Message.messageType
final String ver14.SharedClasses.Networking.Messages.Message.subject
String ver14.SharedClasses.Networking.Messages.Message.respondingToMsgId
String ver14.SharedClasses.Networking.Messages.Message.username
String ver14.SharedClasses.Networking.Messages.Message.cancelingQuestionCause
String ver14.SharedClasses.Networking.Messages.Message.otherPlayer
Boolean ver14.SharedClasses.Networking.Messages.Message.available
ArrayList<String> ver14.SharedClasses.Networking.Messages.Message.usernameSuggestions
PlayerColor ver14.SharedClasses.Networking.Messages.Message.playerColor
GameTime ver14.SharedClasses.Networking.Messages.Message.gameTime
LoginInfo ver14.SharedClasses.Networking.Messages.Message.loginInfo
Move ver14.SharedClasses.Networking.Messages.Message.move
GameSettings ver14.SharedClasses.Networking.Messages.Message.gameSettings
MovesList ver14.SharedClasses.Networking.Messages.Message.possibleMoves
Board ver14.SharedClasses.Networking.Messages.Message.board
GameStatus ver14.SharedClasses.Networking.Messages.Message.gameStatus
Question ver14.SharedClasses.Networking.Messages.Message.question
Question.Answer ver14.SharedClasses.Networking.Messages.Message.answer
ArrayList<Move> ver14.SharedClasses.Networking.Messages.Message.preMoves
SyncedItems<?> [] ver14.SharedClasses.Networking.Messages.Message.syncedLists
Stack<Move> ver14.SharedClasses.Networking.Messages.Message.moveStack
DBResponse ver14.SharedClasses.Networking.Messages.Message.dbResponse
DBRequest ver14.SharedClasses.Networking.Messages.Message.dbRequest
MyError ver14.SharedClasses.Networking.Messages.Message.error
ver14.SharedClasses.Networking.Messages.Message.Message(MessageType messageType)
Instantiates a new Message. messageType the message type
Referenced by ver14.SharedClasses.Networking.Messages.Message.answerQuestion, ver14.SharedClasses.Networking.Messages.Message.askForGameSettings, ver14.SharedClasses.Networking.Messages.Message.askForLogin, ver14.SharedClasses.Networking.Messages.Message.askQuestion, ver14.SharedClasses.Networking.Messages.Message.bye, ver14.SharedClasses.Networking.Messages.Message.checkUsernameAvailability, ver14.SharedClasses.Networking.Messages.Message.dbRequest, ver14.SharedClasses.Networking.Messages.Message.error, ver14.SharedClasses.Networking.Messages.Message.gameOver, ver14.SharedClasses.Networking.Messages.Message.initGame, ver14.SharedClasses.Networking.Messages.Message.interrupt, ver14.SharedClasses.Networking.Messages.Message.returnDBResponse, ver14.SharedClasses.Networking.Messages.Message.returnGameSettings, ver14.SharedClasses.Networking.Messages.Message.returnLogin, ver14.SharedClasses.Networking.Messages.Message.returnMove, ver14.SharedClasses.Networking.Messages.Message.returnUsernameAvailable, ver14.SharedClasses.Networking.Messages.Message.returnUsernameNotAvailable, ver14.SharedClasses.Networking.Messages.Message.syncLists, ver14.SharedClasses.Networking.Messages.Message.throwError, ver14.SharedClasses.Networking.Messages.Message.updateByMove, ver14.SharedClasses.Networking.Messages.Message.waitForMatch, ver14.SharedClasses.Networking.Messages.Message.waitForYourTurn, ver14.SharedClasses.Networking.Messages.Message.welcomeMessage.
ver14.SharedClasses.Networking.Messages.Message.Message(MessageType messageType, String subject, String respondingToMsgId)
Instantiates a new Message. messageType the message type subject the subject respondingToMsgId the responding to msg id
References ver14.SharedClasses.Misc.IDsGenerator.generate.
ver14.SharedClasses.Networking.Messages.Message.Message(MessageType messageType, Message respondingTo)
Instantiates a new Message. messageType the message type respondingTo the responding to
References ver14.SharedClasses.Networking.Messages.Message.messageID.
ver14.SharedClasses.Networking.Messages.Message.Message(MessageType messageType, String subject)
Instantiates a new Message. messageType the message type subject the subject
void ver14.SharedClasses.Networking.Messages.Message.setDbRequest(DBRequest dbRequest)
Sets db request. dbRequest the db request
Referenced by ver14.SharedClasses.Networking.Messages.Message.dbRequest.
String ver14.SharedClasses.Networking.Messages.Message.getCancelingQuestionCause()
void ver14.SharedClasses.Networking.Messages.Message.setCancelingQuestionCause(String cancelingQuestionCause)
Question.Answer ver14.SharedClasses.Networking.Messages.Message.getAnswer()
void ver14.SharedClasses.Networking.Messages.Message.setAnswer(Question.Answer answer)
MyError ver14.SharedClasses.Networking.Messages.Message.getError()
Gets error. the error
void ver14.SharedClasses.Networking.Messages.Message.setError(MyError error)
Sets error. error the error
Referenced by ver14.SharedClasses.Networking.Messages.Message.throwError.
DBRequest ver14.SharedClasses.Networking.Messages.Message.getDBRequest()
Gets db request. the db request
ArrayList< String > ver14.SharedClasses.Networking.Messages.Message.getUsernameSuggestions()
Gets username suggestions. the username suggestions
void ver14.SharedClasses.Networking.Messages.Message.setUsernameSuggestions(ArrayList< String > usernameSuggestions)
Sets username suggestions. usernameSuggestions the username suggestions
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnUsernameNotAvailable.
DBResponse ver14.SharedClasses.Networking.Messages.Message.getDBResponse()
Gets db response. the db response
void ver14.SharedClasses.Networking.Messages.Message.setDBResponse(DBResponse requestedStats)
Sets db response. requestedStats the requested stats
References ver14.SharedClasses.DBActions.DBResponse.DBResponse.clean.
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnDBResponse.
Stack< Move > ver14.SharedClasses.Networking.Messages.Message.getMoveStack()
Gets move stack. the move stack
void ver14.SharedClasses.Networking.Messages.Message.setMoveStack(Stack< Move > moveStack)
Sets move stack. moveStack the move stack
Referenced by ver14.SharedClasses.Networking.Messages.Message.initGame.
SyncedItems<?>[] ver14.SharedClasses.Networking.Messages.Message.getSyncedLists()
Get synced lists synced items [ ]. the synced items [ ]
void ver14.SharedClasses.Networking.Messages.Message.setSyncedLists(SyncedItems<?>... syncedLists)
Sets synced lists. syncedLists the synced lists
Referenced by ver14.SharedClasses.Networking.Messages.Message.askForGameSettings, ver14.SharedClasses.Networking.Messages.Message.syncLists.
String ver14.SharedClasses.Networking.Messages.Message.getRespondingToMsgId()
Gets responding to msg id. the responding to msg id
void ver14.SharedClasses.Networking.Messages.Message.setRespondingToMsgId(String respondingToMsgId)
Sets responding to msg id. respondingToMsgId the responding to msg id
Referenced by ver14.SharedClasses.Networking.Messages.Message.setRespondingTo.
void ver14.SharedClasses.Networking.Messages.Message.setRespondingTo(Message msg)
Sets responding to. msg the msg
References ver14.SharedClasses.Networking.Messages.Message.messageID, ver14.SharedClasses.Networking.Messages.Message.setRespondingToMsgId.
Referenced by ver14.SharedClasses.Networking.AppSocket.respond.
boolean ver14.SharedClasses.Networking.Messages.Message.isResponse()
Is response boolean. the boolean
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onInterrupt.
String ver14.SharedClasses.Networking.Messages.Message.getOtherPlayer()
Gets other player. the other player
void ver14.SharedClasses.Networking.Messages.Message.setOtherPlayer(String otherPlayer)
Sets other player. otherPlayer the other player
Referenced by ver14.SharedClasses.Networking.Messages.Message.initGame.
Question ver14.SharedClasses.Networking.Messages.Message.getQuestion()
Gets question. the question
void ver14.SharedClasses.Networking.Messages.Message.setQuestion(Question question)
Sets question. question the question
Referenced by ver14.SharedClasses.Networking.Messages.Message.askQuestion.
Boolean ver14.SharedClasses.Networking.Messages.Message.getAvailable()
Gets available. the available
void ver14.SharedClasses.Networking.Messages.Message.setAvailable(Boolean available)
Sets available. available the available
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnUsernameAvailable, ver14.SharedClasses.Networking.Messages.Message.returnUsernameNotAvailable.
String ver14.SharedClasses.Networking.Messages.Message.getUsername()
Gets username. the username
void ver14.SharedClasses.Networking.Messages.Message.setUsername(String username)
Sets username. username the username
Referenced by ver14.SharedClasses.Networking.Messages.Message.checkUsernameAvailability.
GameSettings ver14.SharedClasses.Networking.Messages.Message.getGameSettings()
Gets game settings. the game settings
void ver14.SharedClasses.Networking.Messages.Message.setGameSettings(GameSettings gameSettings)
Sets game settings. gameSettings the game settings
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnGameSettings.
ArrayList< Move > ver14.SharedClasses.Networking.Messages.Message.getPreMoves()
Gets pre moves. the pre moves
void ver14.SharedClasses.Networking.Messages.Message.setPreMoves(ArrayList< Move > preMoves)
Sets pre moves. preMoves the pre moves
Referenced by ver14.SharedClasses.Networking.Messages.Message.waitForYourTurn.
String ver14.SharedClasses.Networking.Messages.Message.getSubject()
Gets subject. the subject
PlayerColor ver14.SharedClasses.Networking.Messages.Message.getPlayerColor()
Gets player color. the player color
void ver14.SharedClasses.Networking.Messages.Message.setPlayerColor(PlayerColor playerColor)
Sets player color. playerColor the player color
Referenced by ver14.SharedClasses.Networking.Messages.Message.initGame.
Move ver14.SharedClasses.Networking.Messages.Message.getMove()
Gets move. the move
void ver14.SharedClasses.Networking.Messages.Message.setMove(Move move)
Sets move. move the move
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnMove, ver14.SharedClasses.Networking.Messages.Message.updateByMove.
GameTime ver14.SharedClasses.Networking.Messages.Message.getGameTime()
Gets game time. the game time
void ver14.SharedClasses.Networking.Messages.Message.setGameTime(GameTime gameTime)
Sets game time. gameTime the game time
Referenced by ver14.SharedClasses.Networking.Messages.Message.initGame, ver14.SharedClasses.Networking.Messages.Message.updateByMove, ver14.SharedClasses.Networking.Messages.Message.waitForYourTurn.
GameStatus ver14.SharedClasses.Networking.Messages.Message.getGameStatus()
Gets game status. the game status
void ver14.SharedClasses.Networking.Messages.Message.setGameStatus(GameStatus gameStatus)
Sets game status. gameStatus the game status
Referenced by ver14.SharedClasses.Networking.Messages.Message.gameOver.
MovesList ver14.SharedClasses.Networking.Messages.Message.getPossibleMoves()
Gets possible moves. the possible moves
void ver14.SharedClasses.Networking.Messages.Message.setPossibleMoves(MovesList possibleMoves)
Sets possible moves. possibleMoves the possible moves
References ver14.SharedClasses.Game.Moves.Move.copyMove, ver14.SharedClasses.Game.Moves.Move.getIntermediateMove.
Board ver14.SharedClasses.Networking.Messages.Message.getBoard()
Gets board. the board
void ver14.SharedClasses.Networking.Messages.Message.setBoard(Board board)
Sets board. board the board
Referenced by ver14.SharedClasses.Networking.Messages.Message.initGame.
LoginInfo ver14.SharedClasses.Networking.Messages.Message.getLoginInfo()
Gets login info. the login info
void ver14.SharedClasses.Networking.Messages.Message.setLoginInfo(LoginInfo loginInfo)
Sets login info. loginInfo the login info
Referenced by ver14.SharedClasses.Networking.Messages.Message.returnLogin, ver14.SharedClasses.Networking.Messages.Message.welcomeMessage.
String ver14.SharedClasses.Networking.Messages.Message.toString()
MessageType ver14.SharedClasses.Networking.Messages.Message.getMessageType()
Gets message type. the message type
Referenced by ver14.SharedClasses.Networking.MessagesHandler.blockTilRes, ver14.SharedClasses.Networking.MessagesHandler.receivedMessage, ver14.SharedClasses.Networking.AppSocket.writeMessage.
boolean ver14.SharedClasses.Networking.Messages.Message.isSubject()
Is subject boolean. the boolean
References ver14.SharedClasses.Utils.StrUtils.isEmpty.
static Message ver14.SharedClasses.Networking.Messages.Message.askForLogin()
Ask for login message. the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
static Message ver14.SharedClasses.Networking.Messages.Message.returnLogin(LoginInfo loginInfo, Message respondingTo)
Return login message. loginInfo the login info respondingTo the responding to the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setLoginInfo.
static Message ver14.SharedClasses.Networking.Messages.Message.cancelQuestion(Question question, String cause)
static Message ver14.SharedClasses.Networking.Messages.Message.welcomeMessage(String str, LoginInfo loginInfo)
Welcome message message. str the str loginInfo the login info the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setLoginInfo.
static Message ver14.SharedClasses.Networking.Messages.Message.initGame(Board board, String opponent, PlayerColor player, GameTime gameTime, Stack< Move > moveStack)
Init game message. board the board opponent the opponent player the player gameTime the game time moveStack the move stack the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setBoard, ver14.SharedClasses.Networking.Messages.Message.setGameTime, ver14.SharedClasses.Networking.Messages.Message.setMoveStack, ver14.SharedClasses.Networking.Messages.Message.setOtherPlayer, ver14.SharedClasses.Networking.Messages.Message.setPlayerColor.
static Message ver14.SharedClasses.Networking.Messages.Message.throwError(MyError error)
Throw error message. error if null interrupts the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setError.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.interruptBlocking.
static Message ver14.SharedClasses.Networking.Messages.Message.askForMove(MovesList possibleMoves, GameTime gameTime)
static Message ver14.SharedClasses.Networking.Messages.Message.updateByMove(Move move, GameTime gameTime)
Update by move message. move the move gameTime the game time the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setGameTime, ver14.SharedClasses.Networking.Messages.Message.setMove.
static Message ver14.SharedClasses.Networking.Messages.Message.waitForYourTurn(String waitingForName, GameTime gameTime)
Wait for your turn message. waitingForName the waiting for name gameTime the game time the message
References ver14.SharedClasses.Utils.StrUtils.dontCapWord, ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setGameTime, ver14.SharedClasses.Networking.Messages.Message.setPreMoves.
static Message ver14.SharedClasses.Networking.Messages.Message.waitForMatch()
Wait for match message. the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
static Message ver14.SharedClasses.Networking.Messages.Message.gameOver(GameStatus gameStatus)
Game over message. gameStatus the game status the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setGameStatus, ver14.SharedClasses.Game.Evaluation.GameStatus.toString.
static Message ver14.SharedClasses.Networking.Messages.Message.askForGameSettings(SyncedItems joinableGames, SyncedItems resumableGames)
Ask for game settings message. joinableGames the joinable games resumableGames the resumable games the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setSyncedLists.
static Message ver14.SharedClasses.Networking.Messages.Message.returnGameSettings(GameSettings gameSettings, Message respondingTo)
Return game settings message. gameSettings the game settings respondingTo the responding to the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setGameSettings.
static Message ver14.SharedClasses.Networking.Messages.Message.interrupt()
Interrupt message. the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onInterrupt, ver14.SharedClasses.Networking.MessagesHandler.onIsAlive.
static Message ver14.SharedClasses.Networking.Messages.Message.bye(String subject)
Bye message. subject the subject the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
static Message ver14.SharedClasses.Networking.Messages.Message.error(String err)
Error message. err the err the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
static Message ver14.SharedClasses.Networking.Messages.Message.returnMove(Move move, Message respondingTo)
Return move message. move the move respondingTo the responding to the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setMove.
static Message ver14.SharedClasses.Networking.Messages.Message.answerQuestion(Question.Answer answer, Message respondingTo)
Answer question message. respondingTo the responding to the message
References ver14.SharedClasses.Networking.Messages.Message.Message.
static Message ver14.SharedClasses.Networking.Messages.Message.askQuestion(Question question)
Ask question message. question the question the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setQuestion.
static Message ver14.SharedClasses.Networking.Messages.Message.checkUsernameAvailability(String username)
Check username availability message. username the username the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setUsername.
static Message ver14.SharedClasses.Networking.Messages.Message.returnUsernameNotAvailable(ArrayList< String > usernameSuggestions, Message request)
Return username not available message. usernameSuggestions the username suggestions request the request the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setAvailable, ver14.SharedClasses.Networking.Messages.Message.setUsernameSuggestions.
static Message ver14.SharedClasses.Networking.Messages.Message.returnUsernameAvailable(Message request)
Return username available message. request the request the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setAvailable.
static Message ver14.SharedClasses.Networking.Messages.Message.dbRequest(DBRequest dbRequest)
Db request message. dbRequest the db request the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setDbRequest.
static Message ver14.SharedClasses.Networking.Messages.Message.returnDBResponse(DBResponse DBResponse, Message request)
Return db response message. DBResponse the db response request the request the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setDBResponse.
static Message ver14.SharedClasses.Networking.Messages.Message.syncLists(SyncedItems<?>... syncedLists)
Sync lists message. syncedLists the synced lists the message
References ver14.SharedClasses.Networking.Messages.Message.Message, ver14.SharedClasses.Networking.Messages.Message.setSyncedLists.