ver14::SharedClasses::Game::Evaluation::GameStatus
final PlayerColor ver14.SharedClasses.Game.Evaluation.GameStatus.winningPlayerColor
The Winning player color.
final SpecificStatus ver14.SharedClasses.Game.Evaluation.GameStatus.specificStatus
The Specific game status.
int ver14.SharedClasses.Game.Evaluation.GameStatus.depth
The status's Depth.
Location ver14.SharedClasses.Game.Evaluation.GameStatus.checkedKingLoc
The Checked king loc.
GameStatusType ver14.SharedClasses.Game.Evaluation.GameStatus.gameStatusType
The Game status type.
String ver14.SharedClasses.Game.Evaluation.GameStatus.customStr
The Custom description str.
ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatus(SpecificStatus specificStatus)
Instantiates a new Game status. specificStatus the specific status
ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatus(PlayerColor winningPlayerColor, SpecificStatus specificStatus)
Instantiates a new Game status. winningPlayerColor the winning player color specificStatus the specific status
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.checkmate(PlayerColor winningPlayerColor, Location matedKing)
Checkmate game status. winningPlayerColor the winning player color matedKing the mated king the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.Checkmate.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.gameGoesOn()
Game goes on game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.GameGoesOn.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.tieByAgreement()
Tie by agreement game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.TieByAgreement.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.stalemate()
Stalemate game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.Stalemate.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.fiftyMoveRule()
Fifty move rule game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.FiftyMoveRule.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.serverStoppedGame(String cause)
Server stopped game game status. cause the cause the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.ServerStoppedGame, ver14.SharedClasses.Game.Evaluation.GameStatus.setCustomStr.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.threeFoldRepetition()
Three fold repetition game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.ThreeFoldRepetition.
Referenced by ver14.SharedClasses.Game.Moves.Move.getMoveEvaluation.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.insufficientMaterial()
Insufficient material game status. the game status
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.InsufficientMaterial.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.playerDisconnected(PlayerColor disconnectedPlayer, boolean isVsAi)
Player disconnected game status. disconnectedPlayer the disconnected player isVsAi the is vs ai the game status
References ver14.SharedClasses.Game.PlayerColor.getOpponent, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.PlayerDisconnectedVsAi, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.PlayerDisconnectedVsReal.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.timedOut(PlayerColor timedOutPlayer, boolean isSufficientMaterial)
Timed out game status. timedOutPlayer the timed out player isSufficientMaterial the is sufficient material the game status
References ver14.SharedClasses.Game.PlayerColor.getOpponent, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.TimedOut, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.TimedOutVsInsufficientMaterial.
static GameStatus ver14.SharedClasses.Game.Evaluation.GameStatus.playerResigned(PlayerColor resignedPlayer)
Player resigned game status. resignedPlayer the resigned player the game status
References ver14.SharedClasses.Game.PlayerColor.getOpponent, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.Resignation.
void ver14.SharedClasses.Game.Evaluation.GameStatus.setCustomStr(String customStr)
Sets custom str. customStr the custom str
Referenced by ver14.SharedClasses.Game.Evaluation.GameStatus.serverStoppedGame.
boolean ver14.SharedClasses.Game.Evaluation.GameStatus.isDisconnected()
Is disconnected boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.PlayerDisconnectedVsAi, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.PlayerDisconnectedVsReal, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.ServerStoppedGame.
Location ver14.SharedClasses.Game.Evaluation.GameStatus.getCheckedKingLoc()
Gets checked king loc. the checked king loc
PlayerColor ver14.SharedClasses.Game.Evaluation.GameStatus.getWinningColor()
Gets winning color. the winning color
GameStatusType ver14.SharedClasses.Game.Evaluation.GameStatus.getGameStatusType()
Gets game status type. the game status type
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.Evaluation.
void ver14.SharedClasses.Game.Evaluation.GameStatus.setInCheck(Location checkedKingLoc)
Sets in check. checkedKingLoc the checked king loc
References ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatusType.CHECK.
boolean ver14.SharedClasses.Game.Evaluation.GameStatus.isCheck()
Is check boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatusType.CHECK.
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.isCheck.
String ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr()
Gets detailed str. the detailed str
References ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr.
Referenced by ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr.
String ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr(Map< PlayerColor, String > playerUsernamesMap)
Gets detailed str. playerUsernamesMap the player usernames map the detailed str
References ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatusType.gameOverStr, ver14.SharedClasses.Game.PlayerColor.getName, ver14.SharedClasses.Utils.StrUtils.isEmpty, ver14.SharedClasses.Game.Evaluation.GameStatus.isGameOver.
boolean ver14.SharedClasses.Game.Evaluation.GameStatus.isGameOver()
Is game over boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatusType.isGameOver.
Referenced by ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr, ver14.SharedClasses.Game.Evaluation.Evaluation.isGameOver.
String ver14.SharedClasses.Game.Evaluation.GameStatus.toString()
To string string. the string
References ver14.SharedClasses.Game.Evaluation.GameStatus.GameStatusType.annotation.
Referenced by ver14.SharedClasses.Networking.Messages.Message.gameOver.
void ver14.SharedClasses.Game.Evaluation.GameStatus.setDepth(int depth)
Sets depth. depth the depth
Referenced by ver14.SharedClasses.Game.Evaluation.Evaluation.setEvaluationDepth.
SpecificStatus ver14.SharedClasses.Game.Evaluation.GameStatus.getSpecificStatus()
Gets specific status. the specific status
void ver14.SharedClasses.Game.Evaluation.GameStatus.setCheckedKingLoc(Location checkedKingLoc)
Sets checked king loc. checkedKingLoc the checked king loc