ver14::SharedClasses::DBActions::DBRequest::DBRequest
final Type ver14.SharedClasses.DBActions.DBRequest.DBRequest.type
The Type.
Referenced by ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest, ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
final String ver14.SharedClasses.DBActions.DBRequest.DBRequest.request
The Request.
final RequestBuilder ver14.SharedClasses.DBActions.DBRequest.DBRequest.builder
The Builder.
DBRequest ver14.SharedClasses.DBActions.DBRequest.DBRequest.subRequest
The Sub request.
ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest(SQLStatement sqlStatement)
Instantiates a new Db request. sqlStatement the sql statement
References ver14.SharedClasses.DBActions.Statements.SQLStatement.getStatement, ver14.SharedClasses.DBActions.Statements.SQLStatement.type.
ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest(Type type, String request, RequestBuilder builder)
Instantiates a new Db request. type the type request the request builder the builder
References ver14.SharedClasses.DBActions.DBRequest.DBRequest.type.
ver14.SharedClasses.DBActions.DBRequest.DBRequest.DBRequest(SQLStatement sqlStatement, RequestBuilder builder)
Instantiates a new Db request. sqlStatement the sql statement builder the builder
References ver14.SharedClasses.DBActions.Statements.SQLStatement.getStatement, ver14.SharedClasses.DBActions.Statements.SQLStatement.type.
RequestBuilder ver14.SharedClasses.DBActions.DBRequest.DBRequest.getBuilder()
Gets builder. the builder
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder.
DBRequest ver14.SharedClasses.DBActions.DBRequest.DBRequest.getSubRequest()
Gets sub request. the sub request
void ver14.SharedClasses.DBActions.DBRequest.DBRequest.setSubRequest(DBRequest subRequest)
Sets sub request. subRequest the sub request
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.build.
String ver14.SharedClasses.DBActions.DBRequest.DBRequest.toString()
To string string. the string
References ver14.SharedClasses.DBActions.DBRequest.DBRequest.getRequest.
String ver14.SharedClasses.DBActions.DBRequest.DBRequest.getRequest()
Gets request. the request
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.RequestBuilder, ver14.SharedClasses.DBActions.DBRequest.DBRequest.toString.