ver14::SharedClasses::Game::SavedGames::GameInfo
final String ver14.SharedClasses.Game.SavedGames.GameInfo.gameId
The Game id.
Referenced by ver14.SharedClasses.Game.SavedGames.ArchivedGameInfo.ArchivedGameInfo, ver14.SharedClasses.Game.SavedGames.CreatedGame.CreatedGame, ver14.SharedClasses.Game.SavedGames.GameInfo.equals, ver14.SharedClasses.Game.SavedGames.EstablishedGameInfo.EstablishedGameInfo, ver14.SharedClasses.Game.SavedGames.GameInfo.GameInfo, ver14.SharedClasses.Game.SavedGames.CreatedGame.getGameDesc, ver14.SharedClasses.Game.SavedGames.GameInfo.ID, ver14.SharedClasses.Game.SavedGames.UnfinishedGame.UnfinishedGame.
final String ver14.SharedClasses.Game.SavedGames.GameInfo.creatorUsername
The Creator username.
Referenced by ver14.SharedClasses.Game.SavedGames.ArchivedGameInfo.ArchivedGameInfo, ver14.SharedClasses.Game.SavedGames.CreatedGame.CreatedGame, ver14.SharedClasses.Game.SavedGames.EstablishedGameInfo.EstablishedGameInfo, ver14.SharedClasses.Game.SavedGames.GameInfo.GameInfo, ver14.SharedClasses.Game.SavedGames.CreatedGame.getGameDesc, ver14.SharedClasses.Game.SavedGames.EstablishedGameInfo.getGameDesc, ver14.SharedClasses.Game.SavedGames.GameInfo.isCreator, ver14.SharedClasses.Game.SavedGames.UnfinishedGame.UnfinishedGame.
final GameSettings ver14.SharedClasses.Game.SavedGames.GameInfo.gameSettings
The Game settings.
Referenced by ver14.SharedClasses.Game.SavedGames.ArchivedGameInfo.ArchivedGameInfo, ver14.SharedClasses.Game.SavedGames.CreatedGame.CreatedGame, ver14.SharedClasses.Game.SavedGames.EstablishedGameInfo.EstablishedGameInfo, ver14.SharedClasses.Game.SavedGames.GameInfo.GameInfo, ver14.SharedClasses.Game.SavedGames.GameInfo.getStartingColor, ver14.SharedClasses.Game.SavedGames.UnfinishedGame.UnfinishedGame.
ver14.SharedClasses.Game.SavedGames.GameInfo.GameInfo(String gameId, String creatorUsername, GameSettings gameSettings)
Instantiates a new Game info. gameId the game id creatorUsername the creator username gameSettings the game settings
References ver14.SharedClasses.Game.SavedGames.GameInfo.creatorUsername, ver14.SharedClasses.Game.SavedGames.GameInfo.gameId, ver14.SharedClasses.Game.SavedGames.GameInfo.gameSettings.
Referenced by ver14.SharedClasses.Game.SavedGames.GameInfo.equals.
static GameInfo ver14.SharedClasses.Game.SavedGames.GameInfo.example()
Example game info. the game info
boolean ver14.SharedClasses.Game.SavedGames.GameInfo.isCreator(String username)
Is creator boolean. username the username the boolean
References ver14.SharedClasses.Game.SavedGames.GameInfo.creatorUsername.
Referenced by ver14.SharedClasses.Game.SavedGames.UnfinishedGame.isCreatorToMove.
String ver14.SharedClasses.Game.SavedGames.GameInfo.ID()
Id string. the string
References ver14.SharedClasses.Game.SavedGames.GameInfo.gameId.
boolean ver14.SharedClasses.Game.SavedGames.GameInfo.equals(Object o)
Equals boolean. o the o the boolean
References ver14.SharedClasses.Game.SavedGames.GameInfo.gameId, ver14.SharedClasses.Game.SavedGames.GameInfo.GameInfo.
String ver14.SharedClasses.Game.SavedGames.GameInfo.toString()
To string string. the string
References ver14.SharedClasses.Game.SavedGames.GameInfo.getGameDesc.
abstract String ver14.SharedClasses.Game.SavedGames.GameInfo.getGameDesc()
Gets game desc. the game desc
Referenced by ver14.SharedClasses.Game.SavedGames.GameInfo.toString.
PlayerColor ver14.SharedClasses.Game.SavedGames.GameInfo.getJoiningPlayerColor()
Gets joining player color. the joining player color
References ver14.SharedClasses.Game.PlayerColor.getOpponent, ver14.SharedClasses.Game.SavedGames.GameInfo.getStartingColor.
Referenced by ver14.SharedClasses.Game.SavedGames.CreatedGame.getGameDesc.
PlayerColor ver14.SharedClasses.Game.SavedGames.GameInfo.getStartingColor()
Gets starting color. the starting color
References ver14.SharedClasses.Game.SavedGames.GameInfo.gameSettings.
Referenced by ver14.SharedClasses.Game.SavedGames.GameInfo.getJoiningPlayerColor.