ver14::SharedClasses::Game::Moves::CastlingRights
final String ver14.SharedClasses.Game.Moves.CastlingRights.NO_CASTLING_ABILITY
The constant NO_CASTLING_ABILITY.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.createFromStr, ver14.SharedClasses.Game.Moves.CastlingRights.toString.
final byte [] ver14.SharedClasses.Game.Moves.CastlingRights.RIGHTS
The constant RIGHTS.
final byte [] ver14.SharedClasses.Game.Moves.CastlingRights.PLAYER_MASKS
The constant PLAYER_MASKS.
final String [] ver14.SharedClasses.Game.Moves.CastlingRights.FENS
The constant FENS.
byte ver14.SharedClasses.Game.Moves.CastlingRights.rights
The Rights.
ver14.SharedClasses.Game.Moves.CastlingRights.[static initializer]
ver14.SharedClasses.Game.Moves.CastlingRights.CastlingRights(byte rights)
Instantiates a new Castling rights. rights the rights
ver14.SharedClasses.Game.Moves.CastlingRights.CastlingRights()
Instantiates a new Castling rights.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.createFromStr.
ver14.SharedClasses.Game.Moves.CastlingRights.CastlingRights(CastlingRights other)
Instantiates a new Castling rights. other the other
void ver14.SharedClasses.Game.Moves.CastlingRights.enableCastling(PlayerColor playerColor, Side side)
Enable castling. playerColor the player color side the side
References ver14.SharedClasses.Game.Moves.CastlingRights.getRights.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.createFromStr.
String ver14.SharedClasses.Game.Moves.CastlingRights.toString()
To string string. the string
References ver14.SharedClasses.Game.Moves.CastlingRights.isEnabled, ver14.SharedClasses.Game.Moves.CastlingRights.Side.KING, ver14.SharedClasses.Game.Moves.CastlingRights.NO_CASTLING_ABILITY, ver14.SharedClasses.Game.PlayerColor.PLAYER_COLORS, ver14.SharedClasses.Game.Moves.CastlingRights.Side.QUEEN, ver14.SharedClasses.Game.PlayerColor.WHITE.
boolean ver14.SharedClasses.Game.Moves.CastlingRights.isEnabled(PlayerColor playerColor, Side side)
Is enabled boolean. playerColor the player color side the side the boolean
References ver14.SharedClasses.Game.Moves.CastlingRights.getRights.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.toString.
byte ver14.SharedClasses.Game.Moves.CastlingRights.disableCastling(PlayerColor playerColor)
byte ver14.SharedClasses.Game.Moves.CastlingRights.disableCastling(PlayerColor playerColor, Side side)
Disable castling byte. playerColor the player color side the side the byte
byte ver14.SharedClasses.Game.Moves.CastlingRights.getRights()
Gets rights. the rights
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.enableCastling, ver14.SharedClasses.Game.Moves.CastlingRights.isEnabled.
void ver14.SharedClasses.Game.Moves.CastlingRights.enable(byte b)
Enable. b the b
boolean ver14.SharedClasses.Game.Moves.CastlingRights.hasAny(PlayerColor playerColor)
Has any boolean. playerColor the player color the boolean
References ver14.SharedClasses.Game.Moves.CastlingRights.getPlayersCastling.
byte ver14.SharedClasses.Game.Moves.CastlingRights.getPlayersCastling(PlayerColor playerColor)
Gets players castling. playerColor the player color the players castling
References ver14.SharedClasses.Game.PlayerColor.asInt.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.hasAny.
static CastlingRights ver14.SharedClasses.Game.Moves.CastlingRights.createFromStr(String castlingAbilityStr)
Create from str castling rights. castlingAbilityStr the castling ability str the castling rights
References ver14.SharedClasses.Game.PlayerColor.BLACK, ver14.SharedClasses.Game.Moves.CastlingRights.CastlingRights, ver14.SharedClasses.Game.Moves.CastlingRights.enableCastling, ver14.SharedClasses.Game.Moves.CastlingRights.Side.KING, ver14.SharedClasses.Game.Moves.CastlingRights.NO_CASTLING_ABILITY, ver14.SharedClasses.Game.Moves.CastlingRights.Side.QUEEN, ver14.SharedClasses.Game.PlayerColor.WHITE.
static void ver14.SharedClasses.Game.Moves.CastlingRights.main(String[] args)
The entry point of application. args the input arguments
static PlayerColor ver14.SharedClasses.Game.Moves.CastlingRights.whosCastling(byte castlingRights)
Whos castling player color. castlingRights the castling rights the player color
References ver14.SharedClasses.Game.PlayerColor.BLACK, ver14.SharedClasses.Game.PlayerColor.WHITE.
static byte ver14.SharedClasses.Game.Moves.CastlingRights.getRights(PlayerColor playerColor, Side side)
Gets rights. playerColor the player color side the side the rights
static int ver14.SharedClasses.Game.Moves.CastlingRights.getPlayerAndSideIndex(PlayerColor playerColor, Side side)
Gets player and side index. playerColor the player color side the side the player and side index