ver14::SharedClasses::Utils::RegEx
final RegEx ver14.SharedClasses.Utils.RegEx.Fen
The constant Fen.
final RegEx ver14.SharedClasses.Utils.RegEx.Username
The constant Username.
final RegEx ver14.SharedClasses.Utils.RegEx.Password
The constant Password.
final RegEx ver14.SharedClasses.Utils.RegEx.Icon
The constant Icon.
final RegEx ver14.SharedClasses.Utils.RegEx.StrUtilSkip
The constant StrUtilSkip.
Referenced by ver14.SharedClasses.Utils.StrUtils.format.
final RegEx ver14.SharedClasses.Utils.RegEx.Numbers
The constant Numbers.
final RegEx ver14.SharedClasses.Utils.RegEx.URL
The constant URL.
Referenced by ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Utils.StrUtils.parseURLS.
final RegEx ver14.SharedClasses.Utils.RegEx.DontSaveGame
The constant DontSaveGame.
final RegEx ver14.SharedClasses.Utils.RegEx.IPPAddress
The constant IPPAddress.
final RegEx ver14.SharedClasses.Utils.RegEx.Any
The constant Any.
final String [] ver14.SharedClasses.Utils.RegEx.dontMatch
The Dont match.
Referenced by ver14.SharedClasses.Utils.RegEx.canBeEmpty, ver14.SharedClasses.Utils.RegEx.check, ver14.SharedClasses.Utils.RegEx.get, ver14.SharedClasses.Utils.RegEx.getDetails, ver14.SharedClasses.Utils.RegEx.RegEx.
final String ver14.SharedClasses.Utils.RegEx.details
The Details.
final String ver14.SharedClasses.Utils.RegEx.regEx
The Reg ex.
boolean ver14.SharedClasses.Utils.RegEx.useDontMatch
The Use dont match.
ver14.SharedClasses.Utils.RegEx.RegEx(@Language("RegExp") String regEx, String details, String... dontMatch)
Instantiates a new Reg ex. regEx the reg ex details the details dontMatch the dont match
References ver14.SharedClasses.Utils.RegEx.dontMatch.
Referenced by ver14.SharedClasses.Utils.RegEx.canBeEmpty, ver14.SharedClasses.Utils.RegEx.get.
ver14.SharedClasses.Utils.RegEx.RegEx(@Language("RegExp") String regEx, String details, boolean useDontMatch, String... dontMatch)
Instantiates a new Reg ex. regEx the reg ex details the details useDontMatch the use dont match dontMatch the dont match
References ver14.SharedClasses.Utils.RegEx.dontMatch.
RegEx ver14.SharedClasses.Utils.RegEx.canBeEmpty(boolean bool, String emptyDetails)
Can be empty reg ex. bool the bool emptyDetails the empty details the reg ex
References ver14.SharedClasses.Utils.RegEx.dontMatch, ver14.SharedClasses.Utils.RegEx.RegEx.
RegEx ver14.SharedClasses.Utils.RegEx.get(boolean useDontMatch)
Get reg ex. useDontMatch the use dont match the reg ex
References ver14.SharedClasses.Utils.RegEx.dontMatch, ver14.SharedClasses.Utils.RegEx.RegEx, ver14.SharedClasses.Utils.RegEx.setUseDontMatch.
void ver14.SharedClasses.Utils.RegEx.setUseDontMatch(boolean useDontMatch)
Sets use dont match. useDontMatch the use dont match
Referenced by ver14.SharedClasses.Utils.RegEx.get.
String ver14.SharedClasses.Utils.RegEx.getDetails()
Gets details. the details
References ver14.SharedClasses.Utils.RegEx.dontMatch.
boolean ver14.SharedClasses.Utils.RegEx.check(String str)
Check boolean. str the str the boolean
References ver14.SharedClasses.Utils.RegEx.dontMatch.
Referenced by ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Utils.StrUtils.parseURLS.
String ver14.SharedClasses.Utils.RegEx.getRegex()
Gets regex. the regex
static boolean ver14.SharedClasses.Utils.RegEx.isSavedDate(String str)
Is saved date boolean. str the str the boolean