ver14::SharedClasses::Networking::AppSocket
final Socket ver14.SharedClasses.Networking.AppSocket.msgSocket
The Msg socket.
final ObjectOutputStream ver14.SharedClasses.Networking.AppSocket.msgOS
The Msg os.
final ObjectInputStream ver14.SharedClasses.Networking.AppSocket.msgIS
The Msg is.
MessagesHandler ver14.SharedClasses.Networking.AppSocket.messagesHandler
boolean ver14.SharedClasses.Networking.AppSocket.didDisconnect
ver14.SharedClasses.Networking.AppSocket.AppSocket(String ip, int port)
Instantiates a new App socket. ip the ip port the port IOException the io exception
ver14.SharedClasses.Networking.AppSocket.AppSocket(Socket socket)
Instantiates a new App socket. socket the socket IOException the io exception
References ver14.SharedClasses.Networking.AppSocket.close.
void ver14.SharedClasses.Networking.AppSocket.close()
Close.
References ver14.SharedClasses.Networking.MessagesHandler.createDisconnectedError.
Referenced by ver14.SharedClasses.Networking.AppSocket.AppSocket, ver14.SharedClasses.Networking.MessagesHandler.onAnyDisconnection.
void ver14.SharedClasses.Networking.AppSocket.close(MyError err)
Close. err the error
References ver14.SharedClasses.Threads.ErrorHandling.ErrorHandler< E extends MyError >.ignore.
void ver14.SharedClasses.Networking.AppSocket.interruptListener(MyError err)
Interrupt listener. err the err to interrupt with
References ver14.SharedClasses.Networking.MessagesHandler.interruptBlocking.
void ver14.SharedClasses.Networking.AppSocket.requestMessage(Message requestMsg, MessageCallback onRes)
Request message. requestMsg the request msg onRes the on res
References ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest.
MessagesHandler ver14.SharedClasses.Networking.AppSocket.getMessagesHandler()
Gets messages handler. the messages handler
void ver14.SharedClasses.Networking.AppSocket.setMessagesHandler(MessagesHandler messagesHandler)
Sets messages handler. messagesHandler the messages handler
void ver14.SharedClasses.Networking.AppSocket.respond(Message msg, Message respondingTo)
Respond. msg the msg respondingTo the responding to
References ver14.SharedClasses.Networking.Messages.Message.setRespondingTo.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.onInterrupt, ver14.SharedClasses.Networking.MessagesHandler.onIsAlive.
synchronized void ver14.SharedClasses.Networking.AppSocket.writeMessage(Message msg)
Write message. msg the msg
References ver14.SharedClasses.Networking.Messages.Message.getMessageType, ver14.SharedClasses.Networking.MessagesHandler.prepareForDisconnect.
Referenced by ver14.SharedClasses.Networking.MessagesHandler.noBlockRequest.
boolean ver14.SharedClasses.Networking.AppSocket.isConnected()
Is connected boolean. the boolean
String ver14.SharedClasses.Networking.AppSocket.getLocalAddress()
Gets local address. the local address
String ver14.SharedClasses.Networking.AppSocket.getRemoteAddress()
Gets remote address. the remote address
boolean ver14.SharedClasses.Networking.AppSocket.isClosed()
Is closed boolean. the boolean
Message ver14.SharedClasses.Networking.AppSocket.requestMessage(Message requestMsg)
sending request and blocking til res requestMsg = "can i have x message?" response
References ver14.SharedClasses.Networking.MessagesHandler.blockTilRes.
void ver14.SharedClasses.Networking.AppSocket.stopReading()
Stop reading.
void ver14.SharedClasses.Networking.AppSocket.handledRun()
Handled run.
References ver14.SharedClasses.Networking.MessagesHandler.receivedMessage.