ver14::SharedClasses::Misc::IDsGenerator
final HashMap<String, Object> ver14.SharedClasses.Misc.IDsGenerator.map
The crated ids.
synchronized String ver14.SharedClasses.Misc.IDsGenerator.generate()
Generate id. the string
References ver14.SharedClasses.Misc.IDsGenerator.canUseId.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.Arg, ver14.SharedClasses.Networking.Messages.Message.Message.
boolean ver14.SharedClasses.Misc.IDsGenerator.canUseId(String id)
Can use id boolean. id the id the boolean
Referenced by ver14.SharedClasses.Misc.IDsGenerator.generate.