ver14::SharedClasses::Game::Moves::Move
final PieceType ver14.SharedClasses.Game.Moves.Move.NOT_CAPTURING
The constant NOT_CAPTURING.
BasicMove ver14.SharedClasses.Game.Moves.Move.intermediateMove
an Intermediate move, like moving the rook in a castling.
MovesList ver14.SharedClasses.Game.Moves.Move.creatorList
The list that created this move.
String ver14.SharedClasses.Game.Moves.Move.moveAnnotation
The Move annotation.
ThreefoldStatus ver14.SharedClasses.Game.Moves.Move.threefoldStatus
The Threefold status.
PieceType ver14.SharedClasses.Game.Moves.Move.capturingPieceType
the type of the piece this move captured.
Location ver14.SharedClasses.Game.Moves.Move.enPassantLoc
the en passant location just created (this move is a double pawn push)
PieceType ver14.SharedClasses.Game.Moves.Move.promotingTo
The Piece type this move is Promoting to.
boolean ver14.SharedClasses.Game.Moves.Move.isReversible
Is this move reversible.
Evaluation ver14.SharedClasses.Game.Moves.Move.moveEvaluation
ths Move's evaluation.
MoveFlag ver14.SharedClasses.Game.Moves.Move.moveFlag
The Move flag.
PlayerColor ver14.SharedClasses.Game.Moves.Move.movingPlayerColor
The Moving player color.
byte ver14.SharedClasses.Game.Moves.Move.disabledCastling
The castling rights this move disabled.
int ver14.SharedClasses.Game.Moves.Move.prevFullMoveClock
The full move clock before making this move
int ver14.SharedClasses.Game.Moves.Move.prevHalfMoveClock
The half move clock before making this move
ver14.SharedClasses.Game.Moves.Move.Move(Location movingFrom, Location movingTo, PieceType capturingPieceType)
Instantiates a new Move. movingFrom the moving from movingTo the moving to capturingPieceType the capturing piece type
Referenced by ver14.SharedClasses.Game.Moves.Move.castling, ver14.SharedClasses.Game.Moves.Move.copyMove, ver14.SharedClasses.Game.Moves.Move.threefoldClaim.
ver14.SharedClasses.Game.Moves.Move.Move(Location movingFrom, Location movingTo)
Instantiates a new Move. movingFrom the moving from movingTo the moving to
References ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus.NONE, ver14.SharedClasses.Game.Moves.Move.MoveFlag.NormalMove.
ver14.SharedClasses.Game.Moves.Move.Move(ThreefoldStatus threefoldStatus)
Instantiates a new Move. threefoldStatus the threefold status
ver14.SharedClasses.Game.Moves.Move.Move(Move other)
Instantiates a new Move. other the other
References ver14.SharedClasses.Game.Moves.BasicMove.BasicMove.
MovesList ver14.SharedClasses.Game.Moves.Move.getCreatorList()
Gets creator list. the creator list
void ver14.SharedClasses.Game.Moves.Move.setCreatorList(MovesList creatorList)
Sets creator list. creatorList the creator list
void ver14.SharedClasses.Game.Moves.Move.setMoveAnnotation(String moveAnnotation)
Sets move annotation. moveAnnotation the move annotation
byte ver14.SharedClasses.Game.Moves.Move.getDisabledCastling()
Gets disabled castling. the disabled castling
void ver14.SharedClasses.Game.Moves.Move.setDisabledCastling(byte disabledCastling)
Sets disabled castling. disabledCastling the disabled castling
void ver14.SharedClasses.Game.Moves.Move.setThreefoldOption()
Sets threefold option.
References ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus.CAN_CLAIM.
PlayerColor ver14.SharedClasses.Game.Moves.Move.getMovingColor()
Gets moving color. the moving color
void ver14.SharedClasses.Game.Moves.Move.setMovingColor(PlayerColor movingPlayerColor)
Sets moving color. movingPlayerColor the moving player color
int ver14.SharedClasses.Game.Moves.Move.getPrevFullMoveClock()
Gets prev full move clock. the prev full move clock
void ver14.SharedClasses.Game.Moves.Move.setPrevFullMoveClock(int prevFullMoveClock)
Sets prev full move clock. prevFullMoveClock the prev full move clock
int ver14.SharedClasses.Game.Moves.Move.getPrevHalfMoveClock()
Gets prev half move clock. the prev half move clock
void ver14.SharedClasses.Game.Moves.Move.setPrevHalfMoveClock(int prevHalfMoveClock)
Sets prev half move clock. prevHalfMoveClock the prev half move clock
PieceType ver14.SharedClasses.Game.Moves.Move.getPromotingTo()
Gets promoting to. the promoting to
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate.
void ver14.SharedClasses.Game.Moves.Move.setPromotingTo(PieceType promotingTo)
Sets promoting to. promotingTo the promoting to
References ver14.SharedClasses.Game.Moves.Move.MoveFlag.Promotion.
BasicMove ver14.SharedClasses.Game.Moves.Move.getIntermediateMove()
Gets intermediate move. the intermediate move
Referenced by ver14.SharedClasses.Networking.Messages.Message.setPossibleMoves.
void ver14.SharedClasses.Game.Moves.Move.setIntermediateMove(BasicMove intermediateMove)
Sets intermediate move. intermediateMove the intermediate move
boolean ver14.SharedClasses.Game.Moves.Move.isCheck()
Is check boolean. the boolean
References ver14.SharedClasses.Game.Evaluation.Evaluation.isCheck.
Evaluation ver14.SharedClasses.Game.Moves.Move.getMoveEvaluation()
Gets move evaluation. the move evaluation
References ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus.CLAIMED, ver14.SharedClasses.Game.Evaluation.GameStatus.threeFoldRepetition, ver14.SharedClasses.Game.PlayerColor.WHITE.
void ver14.SharedClasses.Game.Moves.Move.setMoveEvaluation(Evaluation moveEvaluation)
Sets move evaluation. moveEvaluation the move evaluation
PieceType ver14.SharedClasses.Game.Moves.Move.getCapturingPieceType()
Gets capturing piece type. the capturing piece type
boolean ver14.SharedClasses.Game.Moves.Move.isReversible()
Is reversible boolean. the boolean
void ver14.SharedClasses.Game.Moves.Move.setReversible(boolean reversible)
Sets reversible. reversible the reversible
boolean ver14.SharedClasses.Game.Moves.Move.isCapturing()
Is capturing boolean. the boolean
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate.
void ver14.SharedClasses.Game.Moves.Move.setCapturing(PieceType pieceType)
Sets capturing. pieceType the piece type
boolean ver14.SharedClasses.Game.Moves.Move.equals(Object o)
Equals boolean. o the o the boolean
References ver14.SharedClasses.Game.Moves.BasicMove.equals.
String ver14.SharedClasses.Game.Moves.Move.toString()
To string string. the string
References ver14.SharedClasses.Game.Moves.Move.getAnnotation.
String ver14.SharedClasses.Game.Moves.Move.getAnnotation()
Gets annotation. the annotation
References ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate.
Referenced by ver14.SharedClasses.Game.Moves.Move.toString.
boolean ver14.SharedClasses.Game.Moves.Move.strictEquals(Move move)
checks source and destination equals and move flags equals. move the move the boolean
References ver14.SharedClasses.Game.Moves.Move.MoveFlag.equals, ver14.SharedClasses.Game.Moves.Move.getMoveFlag.
MoveFlag ver14.SharedClasses.Game.Moves.Move.getMoveFlag()
Gets move flag. the move flag
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Game.Moves.Move.MoveFlag.equals, ver14.SharedClasses.Game.Moves.Move.strictEquals.
void ver14.SharedClasses.Game.Moves.Move.setMoveFlag(MoveFlag moveFlag)
Sets move flag. moveFlag the move flag
Referenced by ver14.SharedClasses.Game.Moves.Move.castling.
int ver14.SharedClasses.Game.Moves.Move.compareTo(Move o)
Compare to another move. o the other move the comparison result
References ver14.SharedClasses.Game.Evaluation.Evaluation.getEval.
Location ver14.SharedClasses.Game.Moves.Move.getEnPassantLoc()
Gets en passant loc. the en passant loc
void ver14.SharedClasses.Game.Moves.Move.setEnPassantLoc(Location epsnLoc)
Sets en passant loc. epsnLoc the epsn loc
ThreefoldStatus ver14.SharedClasses.Game.Moves.Move.getThreefoldStatus()
void ver14.SharedClasses.Game.Moves.Move.setThreefoldStatus(ThreefoldStatus threefoldStatus)
String ver14.SharedClasses.Game.Moves.Move.getGameStatusStr()
static Move ver14.SharedClasses.Game.Moves.Move.castling(Location movingFrom, Location movingTo, CastlingRights.Side side)
creates a Castling move. movingFrom the moving from movingTo the moving to side the castling side the move
References ver14.SharedClasses.Game.Moves.BasicMove.BasicMove, ver14.SharedClasses.Game.Moves.Move.MoveFlag.CASTLING_FLAGS, ver14.SharedClasses.Game.Location.getLoc, ver14.SharedClasses.Game.Moves.Move.Move, ver14.SharedClasses.Game.Location.row, ver14.SharedClasses.Game.Moves.Move.setMoveFlag.
static Move ver14.SharedClasses.Game.Moves.Move.threefoldClaim()
Threefold claim move. the move
References ver14.SharedClasses.Game.Moves.Move.ThreefoldStatus.CLAIMED, ver14.SharedClasses.Game.Moves.Move.Move.
static Move ver14.SharedClasses.Game.Moves.Move.flipMove(Move move)
Flip move move. move the move the move
References ver14.SharedClasses.Game.Moves.Move.copyMove, ver14.SharedClasses.Game.Moves.BasicMove.flip.
static Move ver14.SharedClasses.Game.Moves.Move.copyMove(Move move)
Copy move. move the move the move
References ver14.SharedClasses.Game.Moves.Move.Move.
Referenced by ver14.SharedClasses.Game.SavedGames.EstablishedGameInfo.EstablishedGameInfo, ver14.SharedClasses.Game.Moves.Move.flipMove, ver14.SharedClasses.Game.Moves.MinimaxMove.MinimaxMove, ver14.SharedClasses.Game.Moves.MinimaxMove.setMove, ver14.SharedClasses.Networking.Messages.Message.setPossibleMoves.
double ver14.SharedClasses.Game.Moves.Move.guessEval()
Guess eval double. used to estimate how good (or bad) a move can be, in order to sort the moves before making any of them, in some situations in the minimax the double