ver14::SharedClasses::Utils::StrUtils
static String ver14.SharedClasses.Utils.StrUtils.dontCapFull(String str)
Dont cap full string. str the str the string
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Threads.ErrorHandling.MyError.errToString.
static String ver14.SharedClasses.Utils.StrUtils.htmlNewLines(String str)
Html new lines string. str the str the string
static int ver14.SharedClasses.Utils.StrUtils.countMatches(String str, @Language("RegExp") String match)
Count matches int. str the str match the match the int
Referenced by ver14.SharedClasses.DBActions.Condition.Condition.
static String[][] ver14.SharedClasses.Utils.StrUtils.format(String[][] mat)
Format string [ ] [ ]. mat the mat the string [ ] [ ]
References ver14.SharedClasses.Utils.StrUtils.format.
Referenced by ver14.SharedClasses.DBActions.Table.Col.Col, ver14.SharedClasses.Utils.StrUtils.createTimeGreeting, ver14.SharedClasses.Utils.StrUtils.createTimeStr, ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Utils.StrUtils.formatDate, ver14.SharedClasses.Game.PlayerColor.getName, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.getPieceName, ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton, ver14.SharedClasses.Misc.Question.Question, ver14.SharedClasses.UI.Buttons.MyJButton.setText, ver14.SharedClasses.Utils.StrUtils.splitArr, ver14.SharedClasses.Game.Evaluation.GameStatus.SpecificStatus.toString.
static String[] ver14.SharedClasses.Utils.StrUtils.format(String[] arr)
Format string [ ]. arr the arr the string [ ]
References ver14.SharedClasses.Utils.StrUtils.format.
static String ver14.SharedClasses.Utils.StrUtils.format(String str)
Format string. str the str the string
References ver14.SharedClasses.Utils.RegEx.check, ver14.SharedClasses.Utils.StrUtils.formatDate, ver14.SharedClasses.Utils.StrUtils.isEmpty, ver14.SharedClasses.Utils.RegEx.StrUtilSkip, ver14.SharedClasses.Utils.RegEx.URL.
static boolean ver14.SharedClasses.Utils.StrUtils.isEmpty(String str)
Is empty boolean. str the str the boolean
Referenced by ver14.SharedClasses.DBActions.RequestBuilder.createResponse, ver14.SharedClasses.Utils.ArgsUtil.equalsSign, ver14.SharedClasses.Utils.StrUtils.fixHtml, ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Game.Evaluation.GameStatus.getDetailedStr, ver14.SharedClasses.Networking.Messages.Message.isSubject, ver14.SharedClasses.Utils.ArgsUtil.OptionalArg.
static String ver14.SharedClasses.Utils.StrUtils.formatDate(String longStr)
Format date string. longStr the long str the string
References ver14.SharedClasses.Utils.StrUtils.formatDate.
Referenced by ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.Utils.StrUtils.formatDate, ver14.SharedClasses.Utils.StrUtils.formatDateSQL.
static String ver14.SharedClasses.Utils.StrUtils.formatDate(Date date)
Format date string. date the date the string
References ver14.SharedClasses.Utils.StrUtils.formatDate.
static String ver14.SharedClasses.Utils.StrUtils.formatDate(Date date, String format)
Format date string. date the date format the format the string
References ver14.SharedClasses.Utils.StrUtils.format.
static String ver14.SharedClasses.Utils.StrUtils.parseURLS(String str)
Parse urls string. str the str the string
References ver14.SharedClasses.Utils.RegEx.check, ver14.SharedClasses.Utils.RegEx.URL.
static String ver14.SharedClasses.Utils.StrUtils.uppercase(String str)
Uppercase string. str the str the string
References ver14.SharedClasses.Utils.StrUtils.dontCapWord.
static String ver14.SharedClasses.Utils.StrUtils.dontCapWord(String str)
Dont cap word string. str the str the string
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.basicAnnotate, ver14.SharedClasses.Utils.StrUtils.uppercase, ver14.SharedClasses.Networking.Messages.Message.waitForYourTurn.
static String ver14.SharedClasses.Utils.StrUtils.formatDateSQL(Date date)
Format date sql string. date the date the string
References ver14.SharedClasses.Utils.StrUtils.formatDate.
Referenced by ver14.SharedClasses.DBActions.Arg.Arg.createVal.
static int ver14.SharedClasses.Utils.StrUtils.getPort(Socket socket)
Gets port. socket the socket the port
References ver14.SharedClasses.Utils.StrUtils.getPort.
Referenced by ver14.SharedClasses.Utils.StrUtils.getPort.
static int ver14.SharedClasses.Utils.StrUtils.getPort(SocketAddress socketAddress)
Gets port. socketAddress the socket address the port
static String ver14.SharedClasses.Utils.StrUtils.getUrl(Socket socket)
Gets url. socket the socket the url
References ver14.SharedClasses.Utils.StrUtils.getUrl.
Referenced by ver14.SharedClasses.Utils.StrUtils.getUrl.
static String ver14.SharedClasses.Utils.StrUtils.getUrl(SocketAddress socketAddress)
Gets url. socketAddress the socket address the url
static String ver14.SharedClasses.Utils.StrUtils.fitInside(String str, JComponent comp)
Fit inside string. str the str comp the comp the string
static String ver14.SharedClasses.Utils.StrUtils.fixHtml(String str)
Fix html string. str the str the string
References ver14.SharedClasses.Utils.StrUtils.isEmpty.
static String ver14.SharedClasses.Utils.StrUtils.strINN(Object... objs)
Str inn string. objs the objs the string
static String ver14.SharedClasses.Utils.StrUtils.splitArr(Object[] arr)
Split arr string. arr the arr the string
References ver14.SharedClasses.Utils.StrUtils.splitArr.
Referenced by ver14.SharedClasses.DBActions.Statements.Selection.createStatement, ver14.SharedClasses.DBActions.Statements.Update.createStatement, ver14.SharedClasses.DBActions.Statements.Selection.join, ver14.SharedClasses.DBActions.Condition.noNulls, ver14.SharedClasses.Utils.StrUtils.splitArr, ver14.SharedClasses.DBActions.Table.Col.sum, ver14.SharedClasses.DBActions.Table.Col.switchCase.
static String ver14.SharedClasses.Utils.StrUtils.splitArr(String divide, Object[] arr)
Split arr string. divide the divide arr the arr the string
References ver14.SharedClasses.Utils.StrUtils.splitArr.
static String ver14.SharedClasses.Utils.StrUtils.splitArr(String divide, Object[] arr, boolean format)
Split arr string. divide the divide arr the arr format the format the string
References ver14.SharedClasses.Utils.StrUtils.format.
static String ver14.SharedClasses.Utils.StrUtils.clean(String str)
Clean string. str the str the string
Referenced by ver14.SharedClasses.DBActions.Table.Table.escapeValues, ver14.SharedClasses.DBActions.Table.Table.tableAndValues.
static String ver14.SharedClasses.Utils.StrUtils.createTimeGreeting()
Create time greeting string. the string
References ver14.SharedClasses.Utils.StrUtils.format.
static void ver14.SharedClasses.Utils.StrUtils.main(String[] args)
The entry point of application. args the input arguments
References ver14.SharedClasses.Utils.StrUtils.createTimeStr.
static String ver14.SharedClasses.Utils.StrUtils.createTimeStr(long millis)
Create time str string. millis the millis the string
References ver14.SharedClasses.Utils.StrUtils.format.
Referenced by ver14.SharedClasses.Utils.StrUtils.main.
static String ver14.SharedClasses.Utils.StrUtils.awful(String og)
Awful string. og the og the string
static String ver14.SharedClasses.Utils.StrUtils.dateTimePrefix(String str)
Date time prefix string. str the str the string
static String ver14.SharedClasses.Utils.StrUtils.repeat(IterationThingy< String > iterationThingy, int numOfIterations)
Repeat string. iterationThingy the iteration thingy numOfIterations the num of iterations the string
References ver14.SharedClasses.Utils.StrUtils.IterationThingy< T >.iteration.
Referenced by ver14.SharedClasses.Game.Moves.CastlingRights.Side.Side.
static String ver14.SharedClasses.Utils.StrUtils.prefixToWord(String str, String prefix)
Prefix to word string. str the str prefix the prefix the string