ver14::SharedClasses::UI::Buttons::MyJButton
String ver14.SharedClasses.UI.Buttons.MyJButton.ogTxt
The Og txt.
VoidCallback ver14.SharedClasses.UI.Buttons.MyJButton.ogOnClick
The Og on click.
VoidCallback ver14.SharedClasses.UI.Buttons.MyJButton.onClick
The On click.
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton(String text, VoidCallback callback)
Instantiates a new My j button. text the text callback the callback
References ver14.SharedClasses.UI.Buttons.MyJButton.setOnClick.
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton(String text)
Instantiates a new My j button. text the text
References ver14.SharedClasses.Utils.StrUtils.format, ver14.SharedClasses.UI.Buttons.MyJButton.setText.
void ver14.SharedClasses.UI.Buttons.MyJButton.setOnClick(VoidCallback onClick)
Sets on click. onClick the on click
Referenced by ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton, ver14.SharedClasses.UI.Buttons.MyJButton.replaceWithCancel.
void ver14.SharedClasses.UI.Buttons.MyJButton.setText(String text)
Sets text. text the text
References ver14.SharedClasses.Utils.StrUtils.format.
Referenced by ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton, ver14.SharedClasses.UI.Buttons.MyJButton.resetState.
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton()
Instantiates a new My j button.
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton(String text, Font font, VoidCallback onClick, JPanel addTo)
Instantiates a new My j button. text the text font the font onClick the on click addTo the add to
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton(String text, Font font, VoidCallback onClick)
Instantiates a new My j button. text the text font the font onClick the on click
References ver14.SharedClasses.UI.Buttons.MyJButton.setOnClick.
ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton(String text, Font font)
Instantiates a new My j button. text the text font the font
References ver14.SharedClasses.UI.Buttons.MyJButton.setFont.
void ver14.SharedClasses.UI.Buttons.MyJButton.setFont(Font font)
Sets font. font the font
Referenced by ver14.SharedClasses.UI.Buttons.MyJButton.MyJButton.
int ver14.SharedClasses.UI.Buttons.MyJButton.getMinSize()
Gets min size. the min size
void ver14.SharedClasses.UI.Buttons.MyJButton.replaceWithCancel(VoidCallback onCancelled)
Replace with cancel. onCancelled the on cancelled
References ver14.SharedClasses.UI.Buttons.MyJButton.setOnClick.
void ver14.SharedClasses.UI.Buttons.MyJButton.resetState(boolean e)
Reset state. e the e
References ver14.SharedClasses.UI.Buttons.MyJButton.setText.
void ver14.SharedClasses.UI.Buttons.MyJButton.onClick()
On click.
void ver14.SharedClasses.UI.Buttons.MyJButton.replaceText(String replacement)
Replace text. replacement the replacement