ver14::SharedClasses::Game::GameSetup::BoardSetup::Pieces::Piece
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_P
represents a White p piece.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_R
represents a White Rook.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_B
represents a White Bishop.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_N
represents a White Knight.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_Q
represents a White Queen.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.W_K
represents a White King.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_P
represents a Black p piece.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_R
represents a Black Rook.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_B
represents a Black Bishop.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_N
represents a Black Knight.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_Q
represents a Black Queen.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.B_K
represents a Black King.
final PieceType ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.pieceType
The Piece type.
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceIcon.
final PlayerColor ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.playerColor
The Player color.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceIcon, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.isOnMyTeam.
final Piece [] ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.ALL_PIECES
The constant ALL_PIECES.
final Piece [][] ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.piecesMap
final String [][] ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.PIECES_ICONS
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.[static initializer]
static Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceFromFen(char c)
Gets piece from fen. c the c the piece from fen
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.BISHOP, ver14.SharedClasses.Game.PlayerColor.BLACK, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.KING, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.KNIGHT, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.PAWN, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.QUEEN, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.ROOK, ver14.SharedClasses.Game.PlayerColor.WHITE.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup.
static Piece ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPiece(PieceType pieceType, PlayerColor playerColor)
Gets piece. pieceType the piece type playerColor the player color the piece
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.asInt, ver14.SharedClasses.Game.PlayerColor.asInt.
static String ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceIcon(Piece piece)
Gets piece icon. piece the piece the piece icon
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.asInt, ver14.SharedClasses.Game.PlayerColor.asInt, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.pieceType, ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.playerColor.
ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.Piece(PieceType pieceType, PlayerColor playerColor)
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getPieceIcon()
Gets piece icon. the piece icon
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getPieceIcon.
String ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.getFen()
Gets fen. the fen
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.getWhitePieceFen, ver14.SharedClasses.Game.PlayerColor.WHITE.
Referenced by ver14.SharedClasses.Game.GameSetup.BoardSetup.Square.getFen.
boolean ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.isOnMyTeam(Piece otherPiece)
Is on my team boolean. otherPiece the other piece the boolean
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.playerColor.
boolean ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.Piece.isOnMyTeam(PlayerColor otherPlayerColor)
Is on my team boolean. otherPlayerColor the other player color the boolean