ver14::SharedClasses::Game::Location
ver14.SharedClasses.Game.Location.A8
ver14.SharedClasses.Game.Location.B8
ver14.SharedClasses.Game.Location.C8
ver14.SharedClasses.Game.Location.D8
ver14.SharedClasses.Game.Location.E8
ver14.SharedClasses.Game.Location.F8
ver14.SharedClasses.Game.Location.G8
ver14.SharedClasses.Game.Location.H8
ver14.SharedClasses.Game.Location.A7
ver14.SharedClasses.Game.Location.B7
ver14.SharedClasses.Game.Location.C7
ver14.SharedClasses.Game.Location.D7
ver14.SharedClasses.Game.Location.E7
ver14.SharedClasses.Game.Location.F7
ver14.SharedClasses.Game.Location.G7
ver14.SharedClasses.Game.Location.H7
ver14.SharedClasses.Game.Location.A6
ver14.SharedClasses.Game.Location.B6
ver14.SharedClasses.Game.Location.C6
ver14.SharedClasses.Game.Location.D6
ver14.SharedClasses.Game.Location.E6
ver14.SharedClasses.Game.Location.F6
ver14.SharedClasses.Game.Location.G6
ver14.SharedClasses.Game.Location.H6
ver14.SharedClasses.Game.Location.A5
ver14.SharedClasses.Game.Location.B5
ver14.SharedClasses.Game.Location.C5
ver14.SharedClasses.Game.Location.D5
ver14.SharedClasses.Game.Location.E5
ver14.SharedClasses.Game.Location.F5
ver14.SharedClasses.Game.Location.G5
ver14.SharedClasses.Game.Location.H5
ver14.SharedClasses.Game.Location.A4
ver14.SharedClasses.Game.Location.B4
ver14.SharedClasses.Game.Location.C4
ver14.SharedClasses.Game.Location.D4
ver14.SharedClasses.Game.Location.E4
ver14.SharedClasses.Game.Location.F4
ver14.SharedClasses.Game.Location.G4
ver14.SharedClasses.Game.Location.H4
ver14.SharedClasses.Game.Location.A3
ver14.SharedClasses.Game.Location.B3
ver14.SharedClasses.Game.Location.C3
ver14.SharedClasses.Game.Location.D3
ver14.SharedClasses.Game.Location.E3
ver14.SharedClasses.Game.Location.F3
ver14.SharedClasses.Game.Location.G3
ver14.SharedClasses.Game.Location.H3
ver14.SharedClasses.Game.Location.A2
ver14.SharedClasses.Game.Location.B2
ver14.SharedClasses.Game.Location.C2
ver14.SharedClasses.Game.Location.D2
ver14.SharedClasses.Game.Location.E2
ver14.SharedClasses.Game.Location.F2
ver14.SharedClasses.Game.Location.G2
ver14.SharedClasses.Game.Location.H2
ver14.SharedClasses.Game.Location.A1
ver14.SharedClasses.Game.Location.B1
ver14.SharedClasses.Game.Location.C1
ver14.SharedClasses.Game.Location.D1
ver14.SharedClasses.Game.Location.E1
ver14.SharedClasses.Game.Location.F1
ver14.SharedClasses.Game.Location.G1
ver14.SharedClasses.Game.Location.H1
final long ver14.SharedClasses.Game.Location.asLong
a long value with a bit set on this location
final int ver14.SharedClasses.Game.Location.asInt
the calculated index
Referenced by ver14.SharedClasses.Game.Location.getLoc, ver14.SharedClasses.Game.Moves.Direction.getRelative.
final int ver14.SharedClasses.Game.Location.row
this location's row
Referenced by ver14.SharedClasses.Game.Moves.Move.castling, ver14.SharedClasses.Game.Location.getMaxDistance.
final int ver14.SharedClasses.Game.Location.col
this location's column
Referenced by ver14.SharedClasses.Game.Location.getMaxDistance.
final int ver14.SharedClasses.Game.Location.A
final int ver14.SharedClasses.Game.Location.B
final int ver14.SharedClasses.Game.Location.C
final int ver14.SharedClasses.Game.Location.D
final int ver14.SharedClasses.Game.Location.E
final int ver14.SharedClasses.Game.Location.F
final int ver14.SharedClasses.Game.Location.G
final int ver14.SharedClasses.Game.Location.H
final ArrayList<Location> ver14.SharedClasses.Game.Location.ALL_LOCS
final int ver14.SharedClasses.Game.Location.NUM_OF_SQUARES
final int ver14.SharedClasses.Game.Location.KING_STARTING_COL
final int ver14.SharedClasses.Game.Location.WHITE_STARTING_ROW
final int ver14.SharedClasses.Game.Location.BLACK_STARTING_ROW
final int ver14.SharedClasses.Game.Location.WHITE_DIFF
final int ver14.SharedClasses.Game.Location.BLACK_DIFF
final PlayerColor ver14.SharedClasses.Game.Location.normalPerspective
final Map<Integer, Location> ver14.SharedClasses.Game.Location.map
final long ver14.SharedClasses.Game.Location.whiteSquares
final long ver14.SharedClasses.Game.Location.blackSquares
ver14.SharedClasses.Game.Location.[static initializer]
static String ver14.SharedClasses.Game.Location.locsMatStr()
Locs mat str string. the string
static Location[][] ver14.SharedClasses.Game.Location.locsMat()
Locs mat location [ ] [ ]. the location [ ] [ ]
static String ver14.SharedClasses.Game.Location.createMatIndicesStr()
Create mat indices str string. the string
static Location ver14.SharedClasses.Game.Location.getLoc(Location loc, Direction direction)
Gets the location relative to loc in the direction loc the loc direction the direction the location if the calculated index is inside the bounds(0...63). null otherwise
Referenced by ver14.SharedClasses.Game.Moves.BasicMove.BasicMove, ver14.SharedClasses.Game.Moves.Move.castling, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.fenSetup, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.getRow, ver14.SharedClasses.Game.Moves.CastlingRights.Side.kingFinalLoc, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.toString.
static Location ver14.SharedClasses.Game.Location.getLoc(Location loc, int numOfMult, Direction direction)
Gets the location relative to loc in the direction given and the distance is determined by the numOfMult loc the loc numOfMult the num of mult direction the direction the location if the calculated index is inside the bounds(0...63). null otherwise
References ver14.SharedClasses.Game.Moves.Direction.offset.
static Location ver14.SharedClasses.Game.Location.getLoc(Location loc, int add)
Gets the location that is exactly add squares from loc NOTE: add should be in bitboard format loc the loc add the number of squares to add the location if the calculated index is inside the bounds(0...63). null otherwise ver14.Model.Bitboard
References ver14.SharedClasses.Game.Location.asInt.
static Location ver14.SharedClasses.Game.Location.getLoc(int locIndex)
Gets location corresponding to the locIndex provided (0..63) locIndex the locIndex the location if the provided index is inside the bounds(0...63). null otherwise
static Location ver14.SharedClasses.Game.Location.valueOf(int locIndex)
Value of location. locIndex the locIndex the location if the provided index is inside the bounds(0...63). null otherwise
static Location ver14.SharedClasses.Game.Location.getLoc(String str)
gets the location corresponding to the provided location string. str the square's coordinate according to the Algebraic notation the loc if given str is valid. null otherwise ...
static Location ver14.SharedClasses.Game.Location.getLoc(int row, int col)
Gets loc. row the row col the col the loc
static Location ver14.SharedClasses.Game.Location.getLoc(int row, int col, boolean flip)
Gets loc. row the row col the col flip the flip the loc
static int ver14.SharedClasses.Game.Location.flip(int num)
Flip int. num the num the int
static boolean ver14.SharedClasses.Game.Location.isInBounds(Location loc)
Is in bounds boolean. loc the loc the boolean
ver14.SharedClasses.Game.Location.Location()
Instantiates a new Location.
String ver14.SharedClasses.Game.Location.matrixStr()
Matrix str string. the string
String ver14.SharedClasses.Game.Location.getColString()
Gets col string. the col string
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate.
Location ver14.SharedClasses.Game.Location.flip()
Flip location. the location
boolean ver14.SharedClasses.Game.Location.isBlackSquare()
Is black square boolean. the boolean
boolean ver14.SharedClasses.Game.Location.isWhiteSquare()
Is white square boolean. the boolean
String ver14.SharedClasses.Game.Location.toString()
To string string. the string
Referenced by ver14.SharedClasses.Game.Moves.MoveAnnotation.annotate, ver14.SharedClasses.Game.GameSetup.BoardSetup.Board.toString.
int ver14.SharedClasses.Game.Location.getMaxDistance(Location other)
Gets max distance. other the other the max distance
References ver14.SharedClasses.Game.Location.col, ver14.SharedClasses.Game.Location.row.
String ver14.SharedClasses.Game.Location.getRowString()
Gets row string. the row string
int ver14.SharedClasses.Game.Location.hash(PieceType pieceType)
Hash int. pieceType the piece type the int
References ver14.SharedClasses.Game.GameSetup.BoardSetup.Pieces.PieceType.asInt.