ver14::SharedClasses::UI::MyJFrame::Closing
String ver14.SharedClasses.UI.MyJFrame.Closing< T >.title
The constant title.
String ver14.SharedClasses.UI.MyJFrame.Closing< T >.header
The constant header.
ImageIcon ver14.SharedClasses.UI.MyJFrame.Closing< T >.icon
The constant icon.
default void ver14.SharedClasses.UI.MyJFrame.Closing< T >.tryClose()
Try close.
References ver14.SharedClasses.UI.MyJFrame.Closing< T >.checkClosingVal, ver14.SharedClasses.UI.MyJFrame.Closing< T >.closing, ver14.SharedClasses.UI.MyJFrame.Closing< T >.show.
Referenced by ver14.SharedClasses.UI.MyJFrame.doXClick.
T ver14.SharedClasses.UI.MyJFrame.Closing< T >.show()
Show t. the t
Referenced by ver14.SharedClasses.UI.MyJFrame.Closing< T >.tryClose.
boolean ver14.SharedClasses.UI.MyJFrame.Closing< T >.checkClosingVal(T val)
Check closing val boolean. val the val the boolean
Referenced by ver14.SharedClasses.UI.MyJFrame.Closing< T >.tryClose.
void ver14.SharedClasses.UI.MyJFrame.Closing< T >.closing(T val)
Closing. val the val
Referenced by ver14.SharedClasses.UI.MyJFrame.Closing< T >.tryClose.